### ISSUE TITLE
"Invalid NEST response built from a null ApiCall which is highly exceptional, please open a bug if you see this\r\n"

### ISSUE THREAD

**Issue by WarrenFerrell** [elastic/elasticsearch-net#5284] opened 2021-01-22 19:57 UTC
**NEST/Elasticsearch.Net version**: 7.0.0.0

**Elasticsearch version**: v7.8.0

**Description of the problem including expected versus actual behavior**:
Getting "Invalid NEST response built from a null ApiCall which is highly exceptional, please open a bug if you see this" trying to call taskResponse.GetResponse<ReindexOnServer>()

**Steps to reproduce**:
 1. Have these methods 
 ```Csharp
        public static async Task ReindexAsync(this ElasticClient client, string oldIndexName, string newIndexName)
        {
            await client.UpsertRoutingPipelineAsync();

            ReindexOnServerResponse reindexResponse = await client.ReindexOnServerAsync(r => r
                .Source(s => s.Index(oldIndexName))
                .Destination(d => d
                    .Index(newIndexName)
                    .Routing(ReindexRouting.Discard)
                    .Pipeline(IdConstants.RoutingPipelineId)
                )
                .WaitForCompletion(false)
            ).ThrowIfFail();

            TaskId taskId = reindexResponse.Task;
            var done = false;
            while (!done)
            {
                var taskResponse = await client.Tasks.GetTaskAsync(taskId).ThrowIfFail();
                if (taskResponse.Completed)
                {
                    done = true;
var responseStr = System.Text.Encoding.UTF8.GetString(taskResponse.ApiCall.ResponseBodyInBytes);
                    _ = taskResponse.GetResponse<ReindexOnServerResponse>()
                        .ThrowIfFail();
                }
                else
                {
                    var waitDelay = TimeSpan.FromSeconds(20);
                    Console.WriteLine($"waiting {waitDelay} for reindex {taskId} to complete.");
                    await Task.Delay(waitDelay);
                }
            }
        }
        public static async Task UpsertRoutingPipelineAsync(this ElasticClient client)
        {
            var pipelineResponse = await client.Ingest.PutPipelineAsync(IdConstants.RoutingPipelineId, p => p
                .Processors(ps => ps
                        .Script(s => s
                            .Lang("painless")
                            .Source("ctx._routing = ctx.customerId")
                    )
                )
            ).ThrowIfFail();
        }
        public static T ThrowIfFail<T>(this T response, string requestName = "") 
            where T : ResponseBase
        {
            if (!response.IsValid)
                throw new ElasticResponseException(requestName, response);
            return response;
        }
        
        public static async Task<T> ThrowIfFail<T>(this Task<T> request, string requestName = "")
            where T : ResponseBase
        {
            var response = await request;
            return response.ThrowIfFail();
        }
```

 2. This second line throws an exception
```Csharp
var responseStr = System.Text.Encoding.UTF8.GetString(taskResponse.ApiCall.ResponseBodyInBytes);
_ = taskResponse.GetResponse<ReindexOnServerResponse>()
                        .ThrowIfFail();
```
responseStr has a value of 
```
{"completed":true,"task":{"node":"3FqvMjmhSMawAxRi9aTV6Q","id":40420,"type":"transport","action":"indices:data/write/reindex","status":{"total":335,"updated":0,"created":335,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0},"description":"reindex from [search_case_sharded_2021-01-21_19_10] to [search_case_sharded_2021-01-22_19_43][_doc]","start_time_in_millis":1611344608120,"running_time_in_nanos":274641996,"cancellable":true,"headers":{}},"response":{"took":272,"timed_out":false,"total":335,"updated":0,"created":335,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled":"0s","throttled_millis":0,"requests_per_second":-1.0,"throttled_until":"0s","throttled_until_millis":0,"failures":[]}}
```

**Expected behavior**
Successful deserialization of taskResponse to ReindexOnServerResponse 

`taskResponse.GetResponse<ReindexOnServerResponse>()`
returns response with
```
  | Name | Value | Type
-- | -- | -- | --
◢ | response | {Invalid NEST response built from a } | Nest.ReindexOnServerResponse
  | ApiCall | null | Elasticsearch.Net.IApiCallDetails
  | Batches | 1 | long
  | Created | 335 | long
  | DebugInformation | "Invalid NEST response built from a null ApiCall which is highly exceptional, please open a bug if you see this\r\n" | string
  | Failures | {Nest.BulkIndexByScrollFailure[0]} | System.Collections.Generic.IReadOnlyCollection<Nest.BulkIndexByScrollFailure> {Nest.BulkIndexByScrollFailure[]}
  | IsValid | false | bool
  | Noops | 0 | long
  | ▶ OriginalException | null | System.Exception
  | ▶ Retries | {Nest.Retries} | Nest.Retries
  | ServerError | null | Elasticsearch.Net.ServerError
  | SliceId | null | int?
  | Task | null | Nest.TaskId
  | TimedOut | false | bool
  | ▶ Took | {272ms} | Nest.Time
  | Total | 335 | long
  | Updated | 0 | long
  | VersionConflicts | 0 | long
```

**Comment by stevejgordon** [comment] 2021-01-23 18:21
Hi @WarrenFerrell. I've had a quick look and I'm unable to reproduce using the latest 7.10.1 client. Are you able to try using the latest package to see if that solves the issue. It's possible this is a bug which was fixed since 7.0.0.

**Comment by stevejgordon** [comment] 2021-01-23 19:29
@WarrenFerrell I may have misunderstood the issue and I can see now what you're referring to. `GetResponse` will not result in `ApiCallDetails` on the produced response. As its comment states, you therefore cannot use its `IsValid` method either. However, the `ReindexOnServerResponse` properties should be successfully deserialised. They are in my local repro for this issue. 

After using `GetResponse` you should simply ignore the `ApiCallDetails`, `DebugInformation` and `IsValid` properties since those are not relevant. The TaskResponse itself includes the details of the actual API call. I'll close this issue as it's working as designed. I'll review whether we can improve our documentation around this though.

**Closed by stevejgordon** 2021-01-23 19:29 UTC
Labels: Awaiting Response, Bug

**Comment by WarrenFerrell** [comment] 2021-01-25 16:53
@stevejgordon thanks for the clarification. Would you suggest checking the OriginalException or ServerError if I want to check for response errors?

**Comment by stevejgordon** [comment] 2021-01-26 07:33
@WarrenFerrell Yes, you should probably validate both are null. The `ServerError` will be most useful. If the reindex request is invalid for example (perhaps reindexing from a non-existent index), then the `ServerErrror` will provide that information.
