### ISSUE TITLE
elasticClient.Index() or Bulk() when index doesn't exist throws exception - no such index

### ISSUE THREAD

**Issue by mikewanguk** [elastic/elasticsearch-net#2205] opened 2016-08-11 09:12 UTC
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:
in elasticsearch 2.3.4, calling elasticClient.Index() or Bulk() with a new index when index doesn't exist throws exception - no such index, whereas in early version of elasticsearch e.g. 2.3.1, elasticsearch will automatically create index if it doesn't exist

**Steps to reproduce**:
1. call elasticClient.Index() or Bulk() for a new index
2. receive server error  - no such index
3. Index() or Bulk() will automatically create index if it doesn't exists, with early version elasticSearch e.g. 2.3.1

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment] 2017-01-10 02:54
Hey @mikewanguk, apologies it taken some time to respond to this. I've just tried this running NEST 2.5.0 against Elasticsearch 2.3.4 and 2.3.5 and don't see this issue. Here's a reproduction

```c#
void Main()
{
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
	var defaultIndex = "default-index";
	var connectionSettings = new ConnectionSettings(pool)
			.DefaultIndex(defaultIndex)
			.PrettyJson()
			.DisableDirectStreaming()
			.OnRequestCompleted(response =>
				{
					// log out the request
					if (response.RequestBodyInBytes != null)
					{
						Console.WriteLine(
							$"{response.HttpMethod} {response.Uri} \n" +
							$"{Encoding.UTF8.GetString(response.RequestBodyInBytes)}");
					}
					else
					{
						Console.WriteLine($"{response.HttpMethod} {response.Uri}");
					}
                    
                    Console.WriteLine();

					// log out the response
					if (response.ResponseBodyInBytes != null)
					{
						Console.WriteLine($"Status: {response.HttpStatusCode}\n" +
								 $"{Encoding.UTF8.GetString(response.ResponseBodyInBytes)}\n" +
								 $"{new string('-', 30)}\n");
					}
					else
					{
						Console.WriteLine($"Status: {response.HttpStatusCode}\n" +
								 $"{new string('-', 30)}\n");
					}
				});
				
	var client = new ElasticClient(connectionSettings);
    
    if (client.IndexExists("bar").Exists)
        client.DeleteIndex("bar");

    if (client.IndexExists("baz").Exists)
        client.DeleteIndex("baz");

    client.Index(new Document { Field = "foo" }, i => i.Index("bar"));

    client.Bulk(b => b
        .IndexMany(new[] { new Document { Field = "foo" } })
        .Index("baz")
    );
}

public class Document
{
    public string Field { get; set; }
}
```

which returns

```json
HEAD http://localhost:9200/bar?pretty=true

Status: 404

------------------------------

HEAD http://localhost:9200/baz?pretty=true

Status: 404

------------------------------

POST http://localhost:9200/bar/document?pretty=true 
{
  "field": "foo"
}

Status: 201
{
  "_index" : "bar",
  "_type" : "document",
  "_id" : "AVmGRX0EVdpPHEynTpAb",
  "_version" : 1,
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}

------------------------------

POST http://localhost:9200/baz/_bulk?pretty=true 
{"index":{"_type":"document","_id":null}}
{"field":"foo"}


Status: 200
{
  "took" : 282,
  "errors" : false,
  "items" : [ {
    "create" : {
      "_index" : "baz",
      "_type" : "document",
      "_id" : "AVmGRX4vVdpPHEynTpAc",
      "_version" : 1,
      "_shards" : {
        "total" : 2,
        "successful" : 1,
        "failed" : 0
      },
      "status" : 201
    }
  } ]
}

------------------------------
``` 

Is it possible that [automatic index creation has been set to `false`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-index_.html#index-creation) on the cluster?

**Comment by Mpdreamz** [comment] 2017-01-18 11:21
Closing this due to failure to reproduce, @mikewanguk still looking forward to hear back from though! 👍

**Closed by Mpdreamz** 2017-01-18 11:21 UTC
