### ISSUE TITLE
DateTime range query not working

### ISSUE THREAD

**Issue by keodime** [elastic/elasticsearch-net#7093] opened 2022-12-10 00:54 UTC
**Elastic.Clients.Elasticsearch version**: 8.0.2

**Elasticsearch version**: 8.5.2

**.NET runtime version**: 6

**Operating system version**: --

**Description of the problem including expected versus actual behavior**:
While trying todo a date time range query nothing we could find works properly. Either we get the wrong number of hits or none or we get syntax errors.

On searchQuery DateRange and Range fonction do not exist. We tried multitude of ways to write it with a query string, but we can't seems to find the proper way to do so.

**Expected behavior**
Filter over dateTime should work.

**Comment by stevejgordon** [comment] 2022-12-13 13:20
Duplicate of #7050.

**Closed by stevejgordon** 2022-12-13 13:20 UTC
Labels: 8.x
