### ISSUE TITLE
Correct Elasticsearch Errors not getting propagated via NEST

### ISSUE THREAD

**Issue by sumithub** [elastic/elasticsearch-net#2388] opened 2016-11-16 01:29 UTC
**NEST/Elasticsearch.Net version**: 2.4.4

**Elasticsearch version**: 2.4.1

**Description of the problem including expected versus actual behavior**: We send bulk requests to ES that are quite big in size. In that case, sometimes ES throws OutOfMemory error or ContentLength exceeded errors that are treated differently inside our error handling code. But surprisingly, NEST only notifies about "Connection Closed" error by not propagating the actual error thrown by ES. Please refer to below error stack trace for the actual error reported by NEST and ES.

Our requirement is to correctly get the actual error thrown by ES, so that we could error handle it differently. But at this stage it's not possible.

**Steps to reproduce**:
 1. Java heap space - OutOfMemoryError Create a batch of documents having large files and send the bulk to elasticsearch
 2. HTTP content length exceeded : Send a 200 MB file to Elasticsearch to exceed it's default 100 MB content length.

- **NEST ERROR**

# FailureReason: BadResponse while attempting POST http://172.30.209.52:9200/_bulk?refresh=false
# Audit trail of this API call:
- [1] BadResponse: Node: http://172.30.209.52:9200/ Took: 00:00:03.5589871
- [2] SniffOnFail: Took: 00:00:00.0039999
- [3] AllNodesDead: Took: 00:00:00
- [4] Resurrection: Node: http://172.30.209.52:9200/ Took: 00:00:00
- [5] SniffSuccess: Node: http://172.30.209.52:9200/ Took: 00:00:00.0035002
# OriginalException: System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 141
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Inner Exception: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 141
# Exception:
Elasticsearch.Net.ElasticsearchClientException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 141
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.BadResponse[TReturn](ElasticsearchResponse`1& response, RequestData data, List`1 pipelineExceptions) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 482
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 103
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[T](PostData`1 body, Func`2 requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 32
   at Nest.LowLevelDispatch.BulkDispatch[T](IRequest`1 p, PostData`1 body) in C:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 0
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 56
   at Fti.Infinity.Data.ElasticRepository`1.BulkIndex(String toIndex, IEnumerable`1 model, Boolean refresh, Func`4 bulkDescriptorDelegate, Func`5 bulkDescriptorDelegateForItemsWithErrors, Action`2 onItemsFailed) in C:\TFS_DATA\Infinity\Dev\Main\source\Fti.Infinity\Data\ElasticRepository.cs:line 216

- **ES Error for Java heap space - OutOfMemoryError**

RemoteTransportException[[Juggernaut][172.30.209.52:9300][indices:data/read/search[phase/fetch/id]]]; nested: ElasticsearchException[Java heap space]; nested: OutOfMemoryError[Java heap space];
Caused by: ElasticsearchException[Java heap space]; nested: OutOfMemoryError[Java heap space];
        at org.elasticsearch.ExceptionsHelper.convertToRuntime(ExceptionsHelper.java:50)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:604)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.readField(CompressingStoredFieldsReader.java:214)
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.visitDocument(CompressingStoredFieldsReader.java:595)
        at org.apache.lucene.index.CodecReader.document(CodecReader.java:81)
        at org.apache.lucene.index.FilterLeafReader.document(FilterLeafReader.java:405)
        at org.elasticsearch.search.fetch.FetchPhase.loadStoredFields(FetchPhase.java:413)
        at org.elasticsearch.search.fetch.FetchPhase.createSearchHit(FetchPhase.java:213)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:178)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:592)

- **ES error for HTTP content length exceeded**   

                      
[2016-11-16 10:26:29,377][WARN ][http.netty               ] [Hercules] Caught exception while handling client http traffic, closing connection [id: 0x1c1c5ee8, /172.30.209.52:49614 => /172.30.209.52:9200]
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by gmarz** [comment] 2016-11-16 16:38
NEST can only handle errors that are returned in the REST layer.  In the case of an OOM exception where the node becomes unresponsive, there's not much we can really do.  The exception in this case accurate since we can't communicate with the node.  There's no way for us to propagate JVM errors in the log file up to the client.

As for the content-length exception.  What behavior are you expecting?  The exception is pretty clear that the content-length has been exceeded.

**Comment by Mpdreamz** [comment] 2016-11-21 15:33
@sumithub closing this as I am not seeing anything actionable on our end, please let us know if you feel there are ways we could propagate this.

**Closed** 2016-11-21 15:32 UTC

**Comment by sumithub** [comment] 2016-11-21 21:24
@gmarz @Mpdreamz apologies for replying late. 
In case of content-length exception we get "System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server." error which is not expected. 
The correct behavior would be to propagate  "HTTP content length exceeded 104857600 bytes." thrown by elastic-search to the REST layer which is not happening at the moment.

**Comment by bharathap** [comment] 2016-11-23 03:27
Have you found a solution for this? 
I am facing the same issue with regard to content length exceeded exception. NEST throws a ElasticsearchClientException with a message "The underlying connection was closed", but ES console shows the correct error.

**Comment by gmarz** [comment] 2016-12-20 15:28
@sumithub sorry for the delayed response.  I'm trying to reproduce this but I observing the correct behavior in the client.  Purposely setting `http.max_content_length` to 1 byte and sending any request (specifically _bulk) bubbles the expected exception:

```
Elasticsearch.Net.ElasticsearchClientException
The remote server returned an error: (413) Request Entity Too Large.
   at Elasticsearch.Net.RequestPipeline.BadResponse[TReturn](ElasticsearchResponse`1& response, RequestData data, List`1 pipelineExceptions) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 482
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 101
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[T](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 61
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[T](PostData`1 body, Func`2 requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 33
   at Nest.LowLevelDispatch.BulkDispatch[T](IRequest`1 p, PostData`1 body) in C:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 27
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 57
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch) in C:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 47
   at Nest.ElasticClient.Bulk(IBulkRequest request) in C:\code\elasticsearch-net\src\Nest\Document\Multiple\Bulk\ElasticClient-Bulk.cs:line 33
   at Nest.IndexManyExtensions.IndexMany[T](IElasticClient client, IEnumerable`1 objects, IndexName index, TypeName type) in C:\code\elasticsearch-net\src\Nest\Document\Multiple\Bulk\ElasticClient-IndexMany.cs:line 25
   at Tests.Reproduce.ExceedingContentLength.ExceedContentLength() in C:\code\elasticsearch-net\src\Tests\Reproduce\ExceedingContentLength.cs:line 16

System.Net.WebException
The remote server returned an error: (413) Request Entity Too Large.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 143
```

Can you maybe share your connection settings, or perhaps try and create a reproducible test?

**Comment by sumithub** [comment] 2016-12-29 00:34
Thanks @gmarz. Did you try this with Nest 5.0? We're in a process to upgrade to NEST 5.0 and try to reproduce the same problem again.
