### ISSUE TITLE
[tests] XPack: Tests.XPack.Watcher.AcknowledgeWatch.AcknowledgeWatchApiTests

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4288] opened 2019-12-18 09:13 UTC
https://dev.azure.com/azure3/elasticsearch-net/_build/results?buildId=2691&view=logs&j=af1244d0-ddd1-5499-9483-8c2268ee60c5&t=e48b7b35-0818-5a16-4e6d-76f8e5477019

**Comment by Mpdreamz** [comment] 2019-12-18 09:23
Does not reproduce but will leave this open as an issue to improve our test output in cases like this.

> build.bat seed:21826 integrate-one 7.5.0 xpack acknowledgewatch

**Comment by russcam** [comment] 2020-02-24 04:42
Gonna close this one for now as not seen this again and cannot reproduce it. Will reopen if it surfaces again 👍

**Closed by russcam** 2020-02-24 04:42 UTC
Labels: Flakey test
