### ISSUE TITLE
Alias + Filter not generating correct json

### ISSUE THREAD

**Issue by wilcraig** [elastic/elasticsearch-net#3573] opened 2019-02-13 23:00 UTC
**NEST/Elasticsearch.Net version**: 6.3.1/6.3.1

**Elasticsearch version**: N/A

**Description of the problem including expected versus actual behavior**:
When creating a filter on an alias the expected JSON is not generated to send to ElasticSearch.

**Steps to reproduce**:
```
public class MyObject 
{
	public DateTimeOffset StartDate { get; set; }
	public DateTimeOffset EndDate { get; set; }
}

var createdIndexResponse = client.CreateIndex(_myIndexName, index =>
	index.Mappings(mappings => mappings
			.Map<MyObject>(obj => obj
				.AutoMap()
			)
		).Aliases(aliases => aliases
			.Alias(_myAliasName, a => a
				.Filter<BoolQueryDescriptor<DateRange>>(filterSelector => filterSelector
					.Bool(filter => filter
						.Must(query => query
							.DateRange(selector => selector
								.Name("startDate")
								.LessThan(DateMath.Now.Add("1d"))
							)
						).Must(query => query
							.DateRange(selector => selector
								.Name("endDate")
								.GreaterThan(DateMath.Now)
							)
						)
					)
				)
			)
		)
	);
```

This generates the following json (roughly - adapted from my actual example):
```
{
"aliases": {
        "aliasName": {}
    },
    "mappings": {
        "defaultObjectName": {
            "properties": {
                "startDate": {
                    "type": "date"
                },
                "endDate": {
                    "type": "date"
                },
            }
        }
    }
}
```

When I expected something like this instead:
```
"aliases": {
        "aliasName": {
              "filter": {
                    "bool": {
                        "must": [
                            {
                                "range": {
                                    "startDate": {
                                        "lt": "now+1d/d"
                                    }
                                }
                            },
                            {
                                "range": {
                                    "endDate": {
                                        "gt": "now/d"
                                    }
                                }
                            }
                        ]
                    }
                }
      }
    },
    "mappings": {
        "defaultObjectName": {
            "properties": {
                "startDate": {
                    "type": "date"
                },
                "endDate": {
                    "type": "date"
                },
            }
        }
    }
}
```

**Comment by wilcraig** [comment] 2019-02-13 23:10
Also tried BoolQueryDescriptor<DateRangeQuery>, BoolQueryDescriptor<DateRangeExpressionDescriptor>, BoolQueryDescriptor<DateRangeExpression> BoolQuery, BooleanPropertyDescriptor<DateRange>, BooleanPropertyDescriptor<DateRangeExpression>, BooleanPropertyDescriptor<DateRangeExpressionDescriptor> and a host of other combinations

**Comment by russcam** [comment] 2019-02-13 23:34
The issue is that both `DateRange` queries don't specify a field to execute against; `.Name()` is to name a query so that in cases of compound queries, you can ascertain which queries a document was a match for. You want to use `.Field()` here instead, which is the field to target. Here's an example

```c#
var client = new ElasticClient();

var _myAliasName = "my-alias"; 
var _myIndexName = "myIndexName";

var createdIndexResponse = client.CreateIndex(_myIndexName, index => index
    .Mappings(mappings => mappings
        .Map<MyObject>(obj => obj
            .AutoMap()
        )
    )
    .Aliases(aliases => aliases
        .Alias(_myAliasName, a => a
            .Filter<MyObject>(f => f
                .DateRange(selector => selector
                    .Field("startDate")
                    .LessThan(DateMath.Now.Add("1d"))
                    .GreaterThan(DateMath.Now)
                )
            )
        )
    )
);
```

which emits the following request JSON

```json
{
  "aliases": {
    "my-alias": {
      "filter": {
        "range": {
          "startDate": {
            "gt": "now",
            "lt": "now+1d"
          }
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "startDate": {
          "type": "date"
        },
        "endDate": {
          "type": "date"
        }
      }
    }
  }
}
```

I've combined both range operators into one query too as it's semantically identical and easier to write :)

Hope this helps. I'm going to close this 👍

**Closed by russcam** 2019-02-13 23:34 UTC

**Comment by russcam** [comment] 2019-02-13 23:37
Also forgot to say; Latest NEST 6.x nuget package is tested and supported to work with all versions of Elasticsearch 6.x. Newer package versions may contain newer APIs not available in the Elasticsearch version you are targeting, and we try our best to call these out in XML docs. But more importantly, newer package versions also include bug fixes, so recommend updating to newer versions in the same major, whenever you get a chance.

**Comment by wilcraig** [comment] 2019-02-14 17:17
Thank you thank you thank you!
