### ISSUE TITLE
The result of the Sql Translate Api is incorrect.

### ISSUE THREAD

**Issue by xiedeyou** [elastic/elasticsearch-net#4110] opened 2019-09-30 03:40 UTC
If you use greater than or less than when calling the Sql Translate Api, the result is incorrect.

**NEST/Elasticsearch.Net version**:7.3

**Elasticsearch version**:7.3.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
1.test data
```
PUT userindicators/_doc/1
{
  "LoginDays":10
}
PUT userindicators/_doc/2
{
  "LoginDays":11
}
``` 
2.Execution code
```C#
var result = ElasticClientProxy.Instance.Sql.Translate(s => s.Query("select * from userindicators where LoginDays>10"));
var query = result.Result.Query;
var p = query.GetType().GetField("_range", BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);
var v = (TermRangeQuery)p.GetValue(query);

if (v.GreaterThan == "10")
{

}
```
 3.The result of hope is v.GreaterThan == "10"
but in fact v.GreaterThan ==  null

**Comment by xiedeyou** [comment] 2019-09-30 03:44
I got the result of the call in the kibana console:
```
{
  "size" : 1000,
  "query" : {
    "range" : {
      "LoginDays" : {
        "from" : 10,
        "to" : null,
        "include_lower" : false,
        "include_upper" : false,
        "boost" : 1.0
      }
    }
  },
  "_source" : false,
  "stored_fields" : "_none_",
  "docvalue_fields" : [
    {
      "field" : "FirstAddBlogTime",
      "format" : "epoch_millis"
    },
    {
      "field" : "LoginDays"
    }
  ],
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}
```
It seems that there are some problems with the Elasticsearch.Net client segment range conversion.

**Comment by russcam** [comment] 2019-09-30 04:25
I don't think the range query should be returning `"from"` and `"to"` fields. The [docs for range query](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl-range-query.html) use

- `gt`
- `gte`
- `lt` 
- `lte`

which the client understands and supports.

Internally, `"from"` and `"to"` fields are supported, including `"include_lower"` and `"include_upper"`, but this is not consistent with the documentation. Thoughts @astefan?

**Comment by codebrain** [comment] 2020-02-24 03:58
Reading through https://github.com/elastic/elasticsearch/issues/48538 it would appear that the properties `from` and `to` are going to be removed, and should have been deprecated and removed some time ago.

@russcam is correct in that the client maps the correct fields according to the documentation, the issue is in the server.

In this instance it might make sense to use the low-level client and deal with the JSON response directly, so that you can obtain the value - with the caveat that the server response is very likely to change when the referenced PR is merged in.

**Closed by codebrain** 2020-02-24 03:58 UTC
