### ISSUE TITLE
ThrowExceptions(true) does not seem to cause the document update api to throw an exception on 404 NotFound

### ISSUE THREAD

**Issue by dtirschek** [elastic/elasticsearch-net#5441] opened 2021-03-23 13:48 UTC
**NEST/Elasticsearch.Net version**: NEST 7.10.1

**Elasticsearch version**: 7.10.0

**Description of the problem including expected versus actual behavior**:
In the connection settings, I have set ThrowsExceptions to true. This seems to work in general, and exceptions are thrown on error responses.
However, in the case of a scripted document update, if the document does not exist, the code fails silently without throwing anything.

**Steps to reproduce**:
 1. Create a elastic client with ThrowExceptions set to true
 2. Send a scripted update request using a document path corresponding to a document that does not exist in the index,
 3. Capture the result and set a breakpoint. The breakpoint will be reached and the result will show a 404 error response. The breakpoint, however, should not have been reached if an exception was thrown as expected.

**Expected behavior**
The call to the update API should have thrown an exception.

**Provide `ConnectionSettings` (if relevant)**:
DisableStreaming: true
ThrowsExceptions: true

**Provide `DebugInformation` (if relevant)**:
```
Invalid NEST response built from a successful (404) low level call on POST: /statistics-oculusassetreferenceimpressions-46-9/_update/29d37987-89f0-4692-aabd-5b7506be6356
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://127.0.0.1:9200/ Took: 00:00:01.2901552
# Request:
{"script":{"source":"++ctx._source.clicks"}}
# Response:
{"error":{"root_cause":[{"type":"document_missing_exception","reason":"[_doc][29d37987-89f0-4692-aabd-5b7506be6356]: document missing","index_uuid":"DaccTD56RGe_skKP39p5HQ","shard":"0","index":"statistics-oculusassetreferenceimpressions-46-9"}],"type":"document_missing_exception","reason":"[_doc][29d37987-89f0-4692-aabd-5b7506be6356]: document missing","index_uuid":"DaccTD56RGe_skKP39p5HQ","shard":"0","index":"statistics-oculusassetreferenceimpressions-46-9"},"status":404}
```

**Comment by stevejgordon** [comment] 2021-03-23 15:31
@dtirschek This is a duplicate of #5227.

Per that issue:
>This was a by-design change, documented in NEST Breaking Changes for 7.0.0. The document describes the reasoning behind this behaviour. The behaviour you are identifying here is therefore not a bug and is functioning correctly. Based on that, I'll close this issue. Thanks.

**Closed by stevejgordon** 2021-03-23 15:31 UTC
Labels: Bug

**Comment by dtirschek** [comment] 2021-03-23 16:01
Thank you,

yes I already employed a work-around very similar to that.

**Comment by dtirschek** [comment] 2021-03-23 16:05
Thank you.

Yes, that is indeed a nice alternative.

To work around, I previously added a check for the response object and threw an exception there, but that would be required in any method this might happen in, so this will be less error.prone for sure.
