### ISSUE TITLE
Highlight on Suggest options

### ISSUE THREAD

**Issue by AIsaac08** [elastic/elasticsearch-net#1602] opened 2015-10-30 15:03 UTC
I think this useful since Elasticsearch itself provide a way to return the suggested coincidences highlighted.

/* Elastic call example */
// CALL
```JSON
GET index_name/_suggest
{
    "suggest_name": {
    "text": "text mispeled",
    "phrase": {
      "field": "field_name",
      "highlight": {
        "pre_tag": "<strong>",
        "post_tag": "</strong>"
      }
    }
  }
}
```

//OUTPUT
```JSON
{
   "suggest_name": [
      {
         "text": "text mispeled",
         "offset": 0,
         "length": 13,
         "options": [
            {
               "text": "text misspelled",
               "highlighted": "text <strong>misspelled</strong>",
               "score": 0.015801122
            }
         ]
      }
   ]
}
```

/* NEST call example */
```C#
var suggest = ElasticClient.Suggest(sa => sa
        .Phrase("suggest_name", ps => ps
        .Text("text mispeled")
        .OnField("field_name")
        .Highlight(h => h
            .PreTag("<strong>")
            .PostTag("</strong>")
        )
    )
);
```
So, in the output from that call, among the options, the highlighted text is missing, I have dug among the documentation, and other sources and by this moment I haven't seen any similar using NEST.

So, is it possible to add this?
Thanks for reading.

**Comment by gmarz** [comment] 2015-11-13 16:24
Duplicate of #1595.  We plan on fixing this for the next release.

**Closed by gmarz** 2015-11-13 16:24 UTC
