### ISSUE TITLE
Nest.PropertyName constructor issue 

### ISSUE THREAD

**Issue by ljnotes** [elastic/elasticsearch-net#2378] opened 2016-11-07 09:54 UTC
**NEST/Elasticsearch.Net version**:

**5.0.0**:

**Nest.PropertyName constructor (**PropertyName(string name)**) doesn't initialize the private field _type**:

**Steps to reproduce**:
 1. Check the code at - _https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/Infer/PropertyName/PropertyName.cs_
 2. The constructor is not initializing the field - `private readonly Type _type`

**Comment by gmarz** [comment] 2016-11-08 19:59
This is by design. `_type` is only used when resolving from an [Expression](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/Infer/PropertyName/PropertyName.cs#L31), and we have necessary null checks in place.

Do you have a particular scenario where this is problematic?

**Comment by gmarz** [comment] 2016-11-14 20:03
Closing.  Feel free to re-open @ljnotes if this is still an issue.

**Closed by gmarz** 2016-11-14 20:03 UTC
