### ISSUE TITLE
ClearScroll returns "Could not parse server" error

### ISSUE THREAD

**Issue by asafc64** [elastic/elasticsearch-net#1313] opened 2015-04-16 07:36 UTC
After searching by scroll request, I wanted to call ClearScroll with the last scroll-id I've got.
But I ran into this error:
{
	StatusCode: 404, 
	Method: DELETE, 
	Url: http://localhost:9200/_search/scroll, 
	Request: c2NhbjswOzE7dG90YWxfaGl0czoxOw==, 
	Response: <Response stream not captured or already read to completion by serializer>
	ExceptionMessage: Could not parse server exception
	 StackTrace: 
}

* Note that the scroll-id is much shorter than the one that originally was sent.
* There is no error in the elasticsearch log.

Do you have any Idea what caused this, and how to fic it?

**Comment by gmarz** [comment] 2015-04-20 19:03
@asafc64 while trying to reproduce this I ran into some weird behavior and opened https://github.com/elastic/elasticsearch/issues/10651

I think you're simply scrolling until completion and thus don't need to explicitly clear the scroll as it will be cleared automatically.

**Comment by asafc64** [comment] 2015-04-22 09:33
It appears to happen only after adding multiple documents.
If I call the Refresh command after each adding, everything is working fine.
Sync issues maybe?

**Comment by gmarz** [comment] 2015-04-30 18:29
Hey @asafc64 apologies for the delay.

Hard to tell without more context or a repro, but I'm pretty sure the 404 you're getting is due to what I've described above.  It's probably not necessary to explicitly clear the scroll if you're scrolling to completion.

Mind sharing some code that can reproduce this?

**Comment by asafc64** [comment] 2015-05-04 12:19
I'm afraid I cannot do this - the code consists of several classes.
I just added and remove document immediately one after the other.

**Comment by gmarz** [comment] 2015-05-04 13:34
Ok, closing this for now then.  Feel free to re-open if you feel like there's still an issue on the client end.

**Closed by gmarz** 2015-05-04 13:34 UTC
