### ISSUE TITLE
Add support for `range` Query

### ISSUE THREAD

**Issue by kleanthis** [elastic/elasticsearch-net#7163] opened 2022-12-30 08:24 UTC
I am very surprised that the [Range query](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/query-dsl-range-query.html) didn't make it in the 8.x client. I wanted to flag it as a bug, but I see there is no mention of it in the release docs for 8.x 

In my opinion `range` is a **_vital_** query. How else does one select documents between dates (if nothing else)?

**Comment by stevejgordon** [comment] 2023-01-23 14:51
Hi, @kleanthis. This relates to defining numeric and date range queries and is a duplicate of #7050. I'll close this on that basis as we are tracking this common requirement. We will prioritise this as we agree it's very common to need this. For now, using 7.x in compatibility mode is recommended if you require this query type.

**Closed by stevejgordon** 2023-01-23 14:51 UTC
Labels: Feature

**Comment by kleanthis** [comment] 2023-01-23 16:59
Thanks, @stevejgordon — understood. I've been using the Transport layer directly.
