### ISSUE TITLE
Exception when weekly schedule trigger has "hour" or "minute" properties defined

### ISSUE THREAD

**Issue by jus0159** [elastic/elasticsearch-net#6150] opened 2022-03-09 10:48 UTC
**NEST/Elasticsearch.Net version**: 7.17.0

**Elasticsearch version**: 7.17.0

**Description of the problem including expected versus actual behavior**:
I have created following watcher trigger config (run every 5min except on Thursdays at 3 am):

```json"schedule": {
      "weekly": [
        {
          "on": [
            "SUN",
            "MON",
            "TUE",
            "WED",
            "FRI",
            "SAT"
          ],
          "at": [
            {
              "hour": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23
              ],
              "minute": [
                0,
                5,
                10,
                15,
                20,
                25,
                30,
                35,
                40,
                45,
                50,
                55
              ]
            }
          ]
        },
        {
          "on": [
            "THU"
          ],
          "at": [
            {
              "hour": [
                0,
                1,
                2,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23
              ],
              "minute": [
                0,
                5,
                10,
                15,
                20,
                25,
                30,
                35,
                40,
                45,
                50,
                55
              ]
            }
          ]
        }
      ]
    }
```
When I now try to get the Watcher using Nest it throws an Exception:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'String Begin Token', actual:'{', at offset:122893 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'String Begin Token', actual:'{', at offset:122893
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadStringSegmentCore(Byte[]& resultBytes, Int32& resultOffset, Int32& resultLength)
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadString()
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)	
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ScheduleFormatter`3.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ScheduleContainerFormatter.GetScheduleContainer[T](JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ScheduleContainerFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)	
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String productName, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)	
```
**Steps to reproduce**:

1. Create a watcher with a Weekly Schedule
2. Try to get the watcher using Client.Search\<Watch\>(...)

As a workaround I am using cron expression for now, but is there a plan that Nest also supports weekly configs such as this one?

**Comment by stevejgordon** [comment] 2022-03-21 12:58
Hi, @jus0159.

Thanks for raising this. This does look to be an issue caused by the model we use for the `TimeOfWeek`. The `At` property expects an `IEnumerable<string>` which doesn't account for data in the format you're using. `DailySchedule` accounts for this by typing `At` as:

```c#
public Union<IEnumerable<string>, IEnumerable<ITimeOfDay>> At { get; set; }
```

Time of week only works if the `at` data were in this form:

```
{ "at" : [ "midnight", "noon", "17:00" ] }
```

In 7.x this is not an easy fix because any change here would be breaking to consumers. I think it's something we'll have to tackle in 8.x and should be taken care of by our code generator and schema. Using a cron expression is probably the best workaround for now if you need to get the watcher details via the client.

Repro note:

This schedule is enough to cause the exception.

```
PUT _watcher/watch/my-watch
{
  "trigger": {
    "schedule": {
      "weekly": {
        "on": [
          "SUN"
        ],
        "at": {
          "hour": [
            0,
            12,
            17
          ],
          "minute": [
            0,
            30
          ]
        }
      }
    }
  }
}
```

```c#
var response = client.Watcher.Get("my-watch"); // Exception is thrown
```

**Comment by stevejgordon** [comment] 2022-03-26 12:26
Closing as this will need to be a breaking-change in 8.x

**Closed by stevejgordon** 2022-03-26 12:26 UTC
Labels: 7.x
