### ISSUE TITLE
Using a SearchRequest with the default constructor executes searches that do not honor the default index

### ISSUE THREAD

**Issue by StingyJack** [elastic/elasticsearch-net#3994] opened 2019-08-06 19:09 UTC
**NEST/Elasticsearch.Net version**: 6.6.0

**Elasticsearch version**:   6.6.0

**Description of the problem including expected versus actual behavior**:

Consider the scenario where we have two or more indexes for the same document fields/mappings/structure. One index is the employee's live data ("employee_data"), and there are others that are either projections of some future expectation ("employee_data_future_1", "employee_data_future_2") or were recently the live data index but are now archival data ("employee_data_as_of_20190707", "employee_data_as_of_20190606").

This code is expecting to get a specific employee record from the current live index. 
```
var httpConnection = new Elasticsearch.Net.HttpConnection();
var pool = new Elasticsearch.Net.SingleNodeConnectionPool(new Uri("EsUri"));
var config = new Nest.ConnectionSettings(pool, httpConnection)
                .DefaultIndex("employee_data"); //complete extensions omitted for brevity

var client = new ElasticClient(config);
var searchRequest = new SearchRequest
{
    Query = new TermQuery
    {
         Field = Nest.Infer.Field<EmpRecord>(f => f.EmployeeId),
         Value = employeeId
    },
    Source = sourceFilter
};

var result = await eClient.SearchAsync<EmpRecord>(searchRequest);

```

... however it does not retrieve a single record. The query that is generated and visible in the Debug information omits the default index as part of the GET request and returns results from the current live data index, as well as any EmpRecord.EmployeeId matches in the future and archival indexes. 

If we update the search result declaration like this ...
```
var searchRequest = new SearchRequest("employee_data")
{
   etc...
```
... then the correct index is used.  This seems to be inconsistent with the [product docs for index name inference](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/index-name-inference.html).  Can this be fixed please?

**Comment by russcam** [comment] 2019-08-07 03:08
In the case of the non-generic type `SearchRequest`, the parameterless constructor generates a request to `/search`

![image](https://user-images.githubusercontent.com/208231/62591780-15ef4e80-b914-11e9-8e90-0d28fcee12fb.png)

The question is whether this is surprising. @Mpdreamz, @codebrain, thoughts?

**Comment by Mpdreamz** [comment] 2019-08-07 08:29
This was done by design, with the initializer syntax the query object is in charge and in the case of the non generic `SearchRequest` the default constructor points to `/_search` since it has no further information to infer on.

**Comment by StingyJack** [comment] 2019-08-07 12:22
Clearly this is surprising. Hence the bug. 


>  the default constructor points to /_search since it has no further information to infer on.

It has the default index specified, so the default should be honored. If no index can be determined then NEST is supposed to throw an exception, not query all indexes as if a wildcard had been specified.

**Comment by StingyJack** [comment] 2019-08-07 12:39
> initializer syntax the query object is in charge 

Choice of syntax should not alter the behavior. There may be things only available via one syntax and not the other, but if the things are available to both syntaxes, the expressed intent cannot be mutated for one of those.

Nothing in a program or API should be ignoring defaults. Does the search object also require the urls and credentials to be specified since it's "in charge"? Ignoring the default index is the same.

Keep in mind this is a .net API so those are the expected conventions and patterns and not those of the wrapped program.

**Comment by Mpdreamz** [comment] 2019-08-07 14:20
I am sorry you feel this way but this was very much intentional

The non generic (search) request objects have a different behavior, it's one of the reasons they exists and we don't force you to do `SearchRequest<object>()`.

```
new SearchRequest(); //    /_search
new SearchRequest<EmpRecord>() //    /{inferred_index}/_search
new SearchDescriptor<EmpRecord>() //    /{inferred_index}/_search
```

e.g for something like delete, the nongeneric version requires you to specify `index` where the generic version does not.

```
new DeleteRequest(index, id);
new DeleteRequest<EmpRecord>(id) 
```

The generic you specify on `SearchAsync<EmpRecord>` relates to the response and by default we'll assume that's what you want to query on as well when using the fluent syntax. However if you call `client.SearchAsync<T>(ISearchRequest)` `T` has no bearings on the defaults unless `ISearchRequest` is an instance of `SearchRequest<T>()`.

**Comment by StingyJack** [comment] 2019-08-07 19:24
Something being intentional does not automagically mean it cannot be a bug or defect.  

The published documentation is aligned with the general expectation (several issues reported here for this). The nest library is counter to that for this part and requires that users now know and master one more depth of non-obvious complexity  and behavior  differences when its supposed to be making it easier. 

Every program honors the default when one is present and no override value is present. That's the convention, and this library should not be any different

**Comment by yarongolan** [comment] 2021-02-08 05:36
Very much agree. We have an index per version of data, and with SearchRequest suddenly all indices were searched, unlike SearchDescriptor.

**Comment by stevejgordon** [comment] 2021-03-23 10:38
Closing due to design. We will review the documentation around this.

**Closed by stevejgordon** 2021-03-23 10:38 UTC
Labels: Breaking, Discuss, Feature

**Comment by StingyJack** [comment] 2021-03-23 12:47
@stevejgordon all the documentation in the world won't fix or address the problem.
