### ISSUE TITLE
The interface is called hundreds of times per second, and the memory occupied by ES cannot be released. This leads to the increase of memory

### ISSUE THREAD

**Issue by NlMay** [elastic/elasticsearch-net#5482] opened 2021-03-26 01:58 UTC
The interface is called hundreds of times per second, and the memory occupied by ES cannot be released. This leads to the increase of memory

What's the solution to this

**Comment by stevejgordon** [comment] 2021-03-26 09:15
Hi @NlMay. I'm going to need some more information to be able to take this issue forward. Let's start with the following:

- Which version of Elasticsearch and the client are you using?
- Can you please share your client configuration?
- When you say "The interface is called hundreds of times per second"... Specifically, which requests are called most often in your application? How are those requests constructed?
- Have you got a profile of your application under load to understand which objects are consuming the memory? 

You could try calling this method on `ConnectionSettings` which changes the behaviour for pooling of `MemoryStreams` which might be more predictable:
```c#
settings.MemoryStreamFactory(Nest.MemoryStreamFactory.Default);
```

**Comment by NlMay** [comment] 2021-03-29 02:21
In the. NETCORE environment, I use addtransient injection. When I use it, I construct and initialize the instance，My configuration is as follows, many of them are default。
![image](https://user-images.githubusercontent.com/57248456/112778558-641c0d00-9077-11eb-8701-2c8275d2bfed.png)
I used the SearchAsyncmethod of IElasticClient and then I found that many objects of btye[] type could not be released
![image](https://user-images.githubusercontent.com/57248456/112779039-7185c700-9078-11eb-930a-d36f51e1d29e.png)

**Comment by NlMay** [comment] 2021-03-29 02:30
Because the data needs to be more real-time, it needs to be called more than once, and then the memory keeps going up

**Comment by stevejgordon** [comment] 2021-03-29 06:15
Thanks for the extra information @NlMay. Can you please confirm the OS version and .NET runtime on which your application is running?

There are a few things I would suggest here to start with.

1. Upgrade to the latest 7.12.0 client as we have introduced some performance enhancements since 7.8.x which may help.
2. Register the NEST client as a Singleton in your DI container, since it's designed to work that way. 
3. Configure the MemoryStreamFactory as per my earlier comment. By default, the factory caches `MemoryStream` instances that may be contributing to the byte[] allocations under high load. The setting I provided will not reuse the instances which may increase overall allocations but shorten their lifetime, resulting in more predictable behaviour. I'd expect this to result in a more sawtooth-like memory graph over time. Looking at the dump information, I think this may be one of the more likely causes of the retained memory.
4. Your use of EnableDebugMode will increase allocations in the application as we have to disable the direct streaming of the responses to achieve that. Additionally, your code allocates an extra string per request. The implementation of which may be allocating further byte arrays. I'd suggest running without `EnableDebugMode` under high load to see if this reduced the memory pressure.

Would you please try these suggestions, to begin with, and see if any of these improve memory usage?

If the problem continues, I'll need to reproduce the behaviour locally. If you're able to provide a simplified reproduction of your application code, including the SearchAsync method and the mapping for your index, that would be ideal. I don't need the whole app, just a portion that exhibits the memory increase.

If you have a memory graph overtime for the heap, that would also be useful to see. If you're permitted, it would be extremely useful to access the memory dump as well. If you're able to, please send it to microsoft [at] elastic.co and let me know here so I can check for it.

**Comment by NlMay** [comment] 2021-03-29 06:31
The project version is as follows：
CentOS Linux release 7.8.2003 (Core)
.NETCore 5.0

**Comment by NlMay** [comment] 2021-03-31 02:08
Use your suggestion: a slow growth of memory, but memory is still growing. Although it has been released, the rate of release can't keep up with the growth rate

**Comment by NlMay** [comment] 2021-03-31 02:10
My business is simple, the number of execution per second is more, query the data of an ES index

**Comment by stevejgordon** [comment] 2021-03-31 06:19
> Use your suggestion: a slow growth of memory, but memory is still growing. Although it has been released, the rate of release can't keep up with the growth rate

I'm glad the non-recycled `MemoryStream` is more predictable. I'm unclear if you're seeing allocated memory outliving garbage collection or simply observing that the GC is not kicking in as often as you'd expect? There will be allocations for each request and of course, 100's per second will cause that to be a potentially quite large amount. The GC should kick in and reclaim when it feels it needs to. You should expect to see a saw-tooth graph memory graph under high load. How much memory are you seeing on the heap over time? What is the peak high and low value? If you're able to share a memory graph, that would also be helpful.

The recycled memory stream is the main cause of large, long-lived byte arrays, but they could also be caused by other methods in the client, and even down to the .NET framework HTTP stack. Ideally, we need to narrow down the source and how to reproduce it in order to see if there's anything we can do to reduce the memory. 

> My business is simple, the number of execution per second is more, query the data of an ES index

Without specific details, it's going to difficult to advise further on this issue. There are many variables that might affect the memory used and I want to be sure we're attempting to reproduce the same situation that you are experiencing. More complex queries and large responses will contribute to larger memory growth. Are you using the fluent syntax or the object initializer for your search requests? How complex are the queries? How many hits/aggregations are in the responses and how large are the deserialised models. How are the searches being triggered? To investigate, I would need to ideally see a reproduction of your case that I can profile.

You may be able to utilise MultiSearch to reduce HTTP calls and therefore some allocations on a hot path if you're able to batch your search requests. For extreme performance situations, you may prefer to drop down to the low-level client and handle the requests and response bytes yourself to control how and when allocations occur.

Performance is a topic I have a great deal of passion for. I want NEST to be as performant as possible. For the next major version, I'm hoping we can reduce allocations, fairly significantly in some situations. It's all prototype code at the moment but I'm seeing some good results. Some of that work may be able to port back to 7.x as well. We have a related ticket for fixing some bugs in the serializer we use as it doesn't reuse memory as well as it could. This should not represent a memory leak though, just higher than optimal memory usage for large responses in particular.

**Comment by NlMay** [comment] 2021-03-31 09:20
Line chart of server memory:
![image](https://user-images.githubusercontent.com/57248456/113121485-4ac8bb80-9245-11eb-8a20-b26accd57011.png)

**Comment by NlMay** [comment] 2021-03-31 09:32
What I use most is the following query：
![image](https://user-images.githubusercontent.com/57248456/113123364-181fc280-9247-11eb-8fa1-62f2e5dcd637.png)

**Comment by NlMay** [comment] 2021-03-31 09:34
What I use most is the following query：
![image](https://user-images.githubusercontent.com/57248456/113123630-54ebb980-9247-11eb-9198-55624ce5aee2.png)

**Comment by NlMay** [comment] 2021-03-31 11:24
Using global dotnet counters to analyze dotnet process:
![image](https://user-images.githubusercontent.com/57248456/113137045-9f286700-9256-11eb-9395-fb882c28b48e.png)

**Comment by stevejgordon** [comment] 2021-03-31 11:41
Thanks for this @NlMay. I'll see if I can reproduce anything similar. How is your QueryList method invoked? Is it part of an ASP.NET Core app or are queries triggered from a queue (in a loop) or some other mechanism? It would be useful to know what your model for the <TDocument> looks like, specifically, does it have a large number of properties? Also, since the set of bool queries are passed in as an argument, it's hard to know how complex those are.

Are you able to monitor the allocations and memory with Visual Studio performance profiling and/or something like DotMemory? It would be useful to know the instantiation call stack for any objects which seem to be long-lived and survive GCs pushing them into Gen 1/2. Are those still of type byte[]?

I can see the slow trend up in the graph. Does the memory growth eventually even off after a period of time?

**Comment by stevejgordon** [comment] 2021-03-31 16:55
I've done some initial basic profiling which doesn't seem to have shown a reproduction of the issue so far. I spun up 20 threads, each making search requests in a tight loop. I've monitored it initially for 12 minutes and while there are allocations, they are mostly in G0. Some survive to G1. G2 is pretty stable so far. I'll run a longer profile to see if any leaks start to show.

![image](https://user-images.githubusercontent.com/3669103/113181034-443c4300-9249-11eb-9789-e2f9afa86b7a.png)

**Comment by stevejgordon** [comment] 2022-01-31 08:33
Closing due to age and lack of reproduction.

**Closed by stevejgordon** 2022-01-31 08:33 UTC
Labels: bug, Awaiting Response
