### ISSUE TITLE
 Bulk-API | Invalid NEST response built from a successful (200) low level call

### ISSUE THREAD

**Issue by neox2811** [elastic/elasticsearch-net#6154] opened 2022-03-14 10:38 UTC
**NEST/Elasticsearch.Net version**: 7.17.0

**Elasticsearch version**: 8.0.1

**.NET runtime version**:  6.0.201

**Operating system version**: Ubuntu 18.04.

**Description of the problem including expected versus actual behavior**:
Successful Bulk-API Request produces invalid NEST Response. See Debug Information.

The property `IsValid` is false, but there are no errors in the response. Maybe it's because of the missing `_type` Property in Elastic v8?

When I execute the query (see Debug-Information) directly in Elasticsearch, no error occurs. My data is in both cases (NEST-Client and direct via Elasticsearch) correctly modified.

**Expected behavior**
Request response should not be invalid.

**Provide `DebugInformation` (if relevant)**:

C# (also at similar Bulk-API requests with IndexMany and DeleteMany functions -> same error)
 ` var updateResponse = await client.BulkAsync(bd => bd
            .Index(ElasticIndex.MyIndex)
            .UpdateMany(myData, (descriptor, v) => descriptor
                .Doc(v))
        );`

NEST-Response
`Invalid NEST response built from a successful (200) low level call on POST: /my-index/_bulk
 Invalid Bulk items:
  operation[0]: update returned 200 _index: my-index _type:  _id: 9f429b8b-dec2-4da1-83b7-e411782920f3 _version: 2 error: 
 Audit trail of this API call:
  [1] HealthyResponse: Node: http://myserver:9200/ Took: 00:00:00.1292754
 Request:
{"update":{"_id":"9f429b8b-dec2-4da1-83b7-e411782920f3"}}
...doc information...
 Response:
{"took":6,"errors":false,"items":[{"update":{"_index":"my-index","_id":"9f429b8b-dec2-4da1-83b7-e411782920f3","_version":2,"result":"updated","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":1459,"_primary_term":3,"status":200}}]}
`

C# - My Connection settings
`var pool = new SingleNodeConnectionPool(new Uri(_appSettings.Elasticsearch.Url));
        var settings = new ConnectionSettings(pool,
            (builtin, settings) => new JsonNetSerializer(builtin, settings,
                () => new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All }
            ));
        settings.BasicAuthentication(_appSettings.Elasticsearch.Username, _appSettings.Elasticsearch.Password);
        settings.DisableDirectStreaming(); 
        settings.EnableApiVersioningHeader();`

**Comment by stevejgordon** [comment] 2022-03-14 11:24
Hi, @neox2811. 

Could you please try enabling our compatibility mode as described in [this document](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html) to see if that changes the response?

**Comment by julbra** [comment] 2022-03-14 14:06
We are seeing the same with NEST 7.17.0 vs. server 8.1.0. Compatibility mode is enabled with `.EnableApiVersioningHeader()`.
The `IsValid` flag is false but no further errors are reported on any items.

**Comment by stevejgordon** [comment] 2022-03-15 08:10
Thanks for checking that @neox2811 and @julbra. I'll need to investigate this and see if it's something we can accommodate in the interim before our new client is ready for GA. We do have bulk support in the [new client](https://www.nuget.org/packages/Elastic.Clients.Elasticsearch/8.0.0-alpha.1) which can be installed side-by-side with NEST. It is however an alpha release and not feature complete.

**Comment by mtbitcoin** [comment] 2022-03-27 16:23
Same here, running nest 7.17.0 and elastic 8.1 and happens with Bulk.  IsValid returns false, when the bulk insert is actually successful

**Comment by stevejgordon** [comment] 2022-03-28 08:35
Hi everyone. I wanted to provide an update. This is indeed confirmed as being caused by our check for the type on the response items. We are discussing this with the server team to identify if this can be addressed with the compatibility feature.

**Comment by MatthewIreti** [comment] 2022-03-28 22:01
Same here, running nest 7.17.0 and elastic 8.1 and happens with Bulk. IsValid returns false, when the bulk insert is actually successful

**Comment by stevejgordon** [comment] 2022-03-29 10:53
Further update. A [fix](https://github.com/elastic/elasticsearch/pull/84873) for this has been merged into the server and will be released with the next patch releases of Elasticsearch. I've validated this myself with a nightly build and can confirm that the responses are no longer reported as invalid. On that basis, I'll close this issue as there's no action to take on the client. Thanks again @neox2811 for raising this.

**Closed by stevejgordon** 2022-03-29 10:53 UTC
Labels: under-investigation

**Comment by jeaguilarc** [comment] 2022-04-01 09:09
ElasticSearch 8.1.2 has been released, but I see that the same problem continues, any idea when this issue will be resolved?

**Comment by stevejgordon** [comment] 2022-04-01 09:49
@jeaguilarc I just tested a bulk request with `8.1.2` and it appears resolved. I'm seeing `_type` on the response items.

**Comment by mtbitcoin** [comment] 2022-04-01 09:51
@stevejgordon the  elasticclient x.IsValid is returning a false (instead of true)

**Comment by stevejgordon** [comment] 2022-04-01 09:52
@mtbitcoin Is your report linked to @jeaguilarc or are these separate occurrences. I'm seeing valid on both the items and the bulk response overall for a simple bulk test. Is it possible there is an actual failure in one of your items?

**Comment by mtbitcoin** [comment] 2022-04-01 10:08
@stevejgordon it was a follow up response to @jeaguilarc , seeing the same.

**Comment by stevejgordon** [comment] 2022-04-01 10:18
@jeaguilarc As a starting point, please verify that you've enabled the compatibility mode on the client settings.

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

var settings = new ConnectionSettings(pool)
    .CertificateFingerprint("FINGERPRINT")
    .BasicAuthentication("elastic", "password")
    .EnableApiVersioningHeader();

var client = new ElasticClient(settings);
```

If that's enabled, I'd recommend enabling [DebugMode](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-mode.html) as well and verifying the request and response JSON in `DebugInformation` on the response. If you can share the response, that would be useful. When using Postman are you including the API versioning required on the Accept header?

**Comment by jeaguilarc** [comment] 2022-04-01 10:39
If I activate EnableApiVersioningHeader and DebugMode it returns this:

Invalid NEST response built from a unsuccessful () low level call on DELETE: /index1/_doc/c616b96b-fe97-40f3-b0fe-b0703861842c?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.1272744
 - [2] ProductCheckFailure: Node: http://elasticDemo:9200/ Took: 00:00:00.0617627
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code 200 from: GET /?pretty=true&error_trace=true ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
   en Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   en Elasticsearch.Net.RequestPipeline.Ping(Node node)
   en Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)
   en Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- Fin del seguimiento de la pila de la excepción interna ---
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:





I have my connection like this:

var connectionPool = context.GetUriServerCollection();

poolConnection = new SniffingConnectionPool(connectionPool);           

Before:

settings = new ConnectionSettings(poolConnection)	
	.DefaultIndex(index1)
	.DefaultMappingFor<EntityElastic>(m => m.IndexName(index1))
	.EnableHttpPipelining()
	.DisableDirectStreaming()
	;
	
Now:
settings = new ConnectionSettings(poolConnection)
	.CertificateFingerprint("FINGERPRINT")
	.DefaultIndex(index1)
	.DefaultMappingFor<EntityElastic>(m => m.IndexName(index1))
	.EnableHttpPipelining()
	.DisableDirectStreaming()
	.EnableApiVersioningHeader()
	;
	
If I change SniffingConnectionPool to SingleNodeConnectionPool, it's still the same.

**Comment by stevejgordon** [comment] 2022-04-01 10:46
@jeaguilarc You need to provide a valid `CertificateFingerprint`, my snippet was just an example. If you've disabled TLS and security as your original code suggests, you don't need to include that. New v8 clusters still with security and TLS enabled by default in which case [this document](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html) provides details on how to configure your client.

So in your case, please try:

```c#
settings = new ConnectionSettings(poolConnection)
    .DefaultIndex(index1)
    .DefaultMappingFor(m => m.IndexName(index1))
    .EnableHttpPipelining()
    .DisableDirectStreaming()
    .EnableApiVersioningHeader();
```

**Comment by stevejgordon** [comment] 2022-04-01 10:47
@mtbitcoin Have you enabled the API version header on the settings for your client?

**Comment by jeaguilarc** [comment] 2022-04-01 10:56
Removing the certificate, the result is still the same, the test server does not even have BasicAuthentication

settings = new ConnectionSettings(poolConnection)
    .DefaultIndex(index1)
    .DefaultMappingFor<EntityElastic>(m => m.IndexName(index1))
    .EnableHttpPipelining()
    .DisableDirectStreaming()
    .EnableApiVersioningHeader()
     EnableDebugMode();

**Comment by jeaguilarc** [comment] 2022-04-01 10:57
Before the bulk, I do a delete. If I activate EnableApiVersioningHeader is when it starts to give the previous error

**Comment by julbra** [comment] 2022-04-01 11:07
> @jeaguilarc I just tested a bulk request with `8.1.2` and it appears resolved. I'm seeing `_type` on the response items.

With Server 8.1.2, `BulkAsync` inserts are now working correctly: `IsValid` is `true`.
🥳

**Comment by jeaguilarc** [comment] 2022-04-01 11:11
¿como incluyo en postman para habilitar el encabezado?. Parece ser un problema de configuración de servidor entonces, cuando activo en el cliente EnableApiVersioningHeader, fallan hasta las búsquedas. Al final lo mio es porque no puedo activar EnableApiVersioningHeader.

**Comment by stevejgordon** [comment] 2022-04-01 11:18
@jeaguilarc This document explains the [REST API compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/rest-api-compatibility.html). 

I can't immediately see how enabling that is causing the error you are seeing which is a pre-flight check to the server failing. That check occurs before the first request from the client. I've added a delete call to my code and it functions as expected. 

As this no longer seems to be related to the original issue, could you please file a new one?

**Comment by jeaguilarc** [comment] 2022-04-01 11:22
Ok, I'll open another topic with this. Thank you very much.

**Comment by stevejgordon** [comment] 2022-04-01 14:34
@mtbitcoin I'd really like to try to reproduce and understand the issue. We want the experience of working with 8.x to be a good one, especially until we have the 8.x client completed. Is your error the same as @jeaguilarc or something else? I'd welcome a new issue we can work with you on.

**Comment by SzymonKatra** [comment] 2022-04-07 13:20
I am having the same issue as @jeaguilarc  and @mtbitcoin, but only on .NET Framework. Opened new issue - #6260

**Comment by stevejgordon** [comment] 2022-04-11 10:27
@SzymonKatra Thanks for raising the new issue. I have investigated this and identified the most likely cause of various issues when using API versioning for compatibility on .NET Framework. I'm testing the fix currently and will release a patch ASAP.

**Comment by stevejgordon** [comment] 2022-04-11 12:18
@jeaguilarc  and @mtbitcoin - I have released 7.17.1 today which includes the validation fix for .NET Framework.

**Comment by mtbitcoin** [comment] 2022-04-11 12:35
did a quick test...and it works! thank you

**Comment by stevejgordon** [comment] 2022-04-11 12:52
Thanks for confirming @mtbitcoin. Apologies for any blocks this issue introduced for you and your team. Yes, `EnableApiVersioningHeader` is required for correct communication with a v8 server as it ensures the server returns v7 compatible responses that the client can deserialise and validate.

**Comment by jeaguilarc** [comment] 2022-04-11 13:19
Hi @stevejgordon, I just tried it with EnableApiVersioningHeader and it works fine for me. Thank you very much!!!

**Comment by jeaguilarc** [comment] 2022-04-11 13:37
Existe alguna forma que pueda dejar configurado EnableApiVersioningHeader y conectarme a un elastic 7?. He probado activarlo y da error de sentencia. Lo pregunto porque tengo el entorno de producción con la versión 7 y el entorno de desarrollo en versión 8.

**Comment by stevejgordon** [comment] 2022-04-11 13:50
@jeaguilarc What version of Elasticsearch 7 are you using? The latest versions should support the header. 

In your case, you may find it better to use the [environment variable](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/nest-getting-started.html#_enabling_the_compatibility_mode) to configure this. We included that so that different environments could control the version header.

**Comment by jeaguilarc** [comment] 2022-04-11 14:01
I use 7.17, I review the environment variable that apparently will make things easier in the future.

**Comment by stevejgordon** [comment] 2022-04-11 15:15
> I use 7.10, I review the environment variable that apparently will make things easier in the future.
Ah, that explains it. Server support for the header was added to 7.13.

**Comment by herdemsekerci** [comment] 2023-08-18 12:27
I had the same issue, after spending a few hours to investigate, then thankfully seen this ticket. Thanks for the everyone who contributes to this feed, especially @stevejgordon .  By enabling compatibility mode using  **.EnableApiVersioningHeader()** solved the problem for my case.

```
settings = new ConnectionSettings(poolConnection)
    .DefaultIndex(index1)
    .DefaultMappingFor(m => m.IndexName(index1))
    .EnableHttpPipelining()
    .DisableDirectStreaming()
    .EnableApiVersioningHeader();
```

Thanks everyone.

**Comment by stevejgordon** [comment] 2023-08-31 13:05
@yansklyarenko There are no performance implications in either case, as this simply adds an extra header to indicate the version being used so that it can accept requests and send responses in the 7.x form. It's not necessary to enable it unless communicating from a 7.17 client to an 8.x server.

**Comment by yansklyarenko** [comment] 2023-08-31 14:00
@stevejgordon Thanks for the clarifications, Steve! It makes perfect sense!
