### ISSUE TITLE
7.0.0-alpha 1 - Wrong converting datetime fields

### ISSUE THREAD

**Issue by lukapor** [elastic/elasticsearch-net#3719] opened 2019-05-06 11:14 UTC
I upgraded es to version 7 in our product.

I have one document with CreatedDate

[Date(Store = false)]
public DateTime CreatedDate { get; set; }

Then I have some DateRange query on CreatedDate.
In some case I got error for es server, depends on Date i pass.

{"took":4,"responses":[{"error":{"root_cause":[{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":4,"index":"sprint_loop_stream2","node":"UEMUX6kGRMSHdGfJC8KKhQ","reason":{"type":"parse_exception","reason":"failed to parse date field [2019-05-06T07:38:35.82] with format [strict_date_optional_time||epoch_millis]: [Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19]","caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}}}],"caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}},"status":400}]}

if date is
2019-05-06T07:38:35.82 query fails
if date is
2019-05-06T07:38:35.8200001 query succeced.

I suspect the new  internal serializer (utf8json)

**Comment by russcam** [comment] 2019-05-07 01:49
@lukapor do you have a small but complete example that reproduces the issue? 

It looks like it could possibly be a formatting issue - is there a format defined in the mapping or in the date range query?

**Comment by lukapor** [comment] 2019-05-07 07:39
In the mapping is nothing special defined.
"createdDate": {
   "type": "date"
},

It is hard to reproduce with script, because it is library change.

I did a workaround
previous code was something like that
queryDescriptor.DateRange(t => t.Field(f => f.CreatedDate).LessThan(query.OffsetQuery.OffsetDate)

the workaround is like that
queryDescriptor.DateRange(t => t.Field(f => f.CreatedDate).Format(Helper.DateISO8601Format).LessThan(query.OffsetQuery.OffsetDate)

Helper.DateISO8601Format = "iso8601||strict_date_optional_time||epoch_millis";

i think if you write a test like this
//public DateTime (int year, int month, int day, int hour, int minute, int second, int millisecond);
var dateValue = new DateTime(2019, 5, 7, 12, 0, 0, 11);

queryDescriptor.DateRange(t => t.Field(f => f.CreatedDate).LessThan(dateValue);

Search

the test should fail.

**Comment by russcam** [comment] 2019-05-08 01:53
I can't replicate what you're seeing @lukapor. Here's a repro to show what I see when running with 7.0.0-alpha1

```c#
private static void Main()
{
	var defaultIndex = "default_index";
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

	var settings = new ConnectionSettings(pool)
		.DefaultIndex(defaultIndex)
		.DisableDirectStreaming()
		.PrettyJson()
		.OnRequestCompleted(callDetails =>
		{
			if (callDetails.RequestBodyInBytes != null)
			{
				Console.WriteLine(
					$"{callDetails.HttpMethod} {callDetails.Uri} \n" +
					$"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
			}
			else
			{
				Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
			}

			Console.WriteLine();

			if (callDetails.ResponseBodyInBytes != null)
			{
				Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
						 $"{Encoding.UTF8.GetString(callDetails.ResponseBodyInBytes)}\n" +
						 $"{new string('-', 30)}\n");
			}
			else
			{
				Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
						 $"{new string('-', 30)}\n");
			}
		});

	var client = new ElasticClient(settings);

	if (client.IndexExists(defaultIndex).Exists)
		client.DeleteIndex(defaultIndex);

	client.CreateIndex(defaultIndex, c => c
		.Map<Document>(mm => mm
			.AutoMap()
		)
	);
	
	client.Index(
		new Document { CreatedDate = new DateTime(2019, 5, 7, 12, 0, 0, 10) }, 
		i => i.Refresh(Refresh.WaitFor));
		
	client.Search<Document>(s => s
		.Query(q => q
			.DateRange(t => t
				.Field(f => f.CreatedDate)
				.LessThan(new DateTime(2019, 5, 7, 12, 0, 0, 11))
			)
		)
	);
}

public class Document
{
	public DateTime CreatedDate { get; set; }
}
```

which prints the following to the console

```json
HEAD http://localhost:9200/default_index?pretty=true

Status: 404

------------------------------

PUT http://localhost:9200/default_index?pretty=true 
{"mappings":{"properties":{"createdDate":{"type":"date"}}}}

Status: 200
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "default_index"
}

------------------------------

POST http://localhost:9200/default_index/_doc?pretty=true&refresh=wait_for 
{"createdDate":"2019-05-07T12:00:00.0100000"}

Status: 201
{
  "_index" : "default_index",
  "_type" : "_doc",
  "_id" : "k8D8lGoBQBovf7sob3nN",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}

------------------------------

POST http://localhost:9200/default_index/_search?pretty=true&typed_keys=true 
{"query":{"range":{"createdDate":{"lt":"2019-05-07T12:00:00.011"}}}}

Status: 200
{
  "took" : 32,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "default_index",
        "_type" : "_doc",
        "_id" : "k8D8lGoBQBovf7sob3nN",
        "_score" : 1.0,
        "_source" : {
          "createdDate" : "2019-05-07T12:00:00.0100000"
        }
      }
    ]
  }
}
------------------------------

```

The search query succeeds. 

Are you using JsonNetSerializer? If I plug it in, then the index request fails, but the search request succeeds.

```c#
// same code as above, but with the following change
var settings = new ConnectionSettings(pool, JsonNetSerializer.Default)
```

```json
POST http://localhost:9200/default_index/_doc?pretty=true&refresh=wait_for 
{"createdDate":"2019-05-07T12:00:00.01"}

Status: 400
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [createdDate] of type [date] in document with id 'lMAAlWoBQBovf7soLHlw'"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [createdDate] of type [date] in document with id 'lMAAlWoBQBovf7soLHlw'",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "failed to parse date field [2019-05-07T12:00:00.01] with format [strict_date_optional_time||epoch_millis]",
      "caused_by" : {
        "type" : "date_time_parse_exception",
        "reason" : "Failed to parse with all enclosed parsers"
      }
    }
  },
  "status" : 400
}

------------------------------

POST http://localhost:9200/default_index/_search?pretty=true&typed_keys=true 
{"query":{"range":{"createdDate":{"lt":"2019-05-07T12:00:00.011"}}}}

Status: 200
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}

------------------------------
```

This looks like it may be related to `strict_date_optional_time` requiring a minimum 3 places for sub second values

https://github.com/elastic/elasticsearch/blob/37758bb58306a9a319ec46e42aa8aead7a3acc5d/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L90

I've opened https://github.com/elastic/elasticsearch/issues/41927 to discuss.

I'm not sure if this is the same underlying issue that you're seeing though, as you're seeing it on search which I cannot reproduce. If you can put together a super small repro, it would really help

**Comment by lukapor** [comment] 2019-05-08 10:52
Hi, I dont use JsonNetSerializer.

I run code and runs ok, if I change date in search, it will fail example

client.Search<Document>(s => s
		.Query(q => q
			.DateRange(t => t
				.Field(f => f.CreatedDate)
				.LessThan(new DateTime(2019, 5, 7, 12, 0, 0, 20))

I changed date form DateTime(2019, 5, 7, 12, 0, 0, 11) to DateTime(2019, 5, 7, 12, 0, 0, 20)
this i test it with 7.0.0-alpha2

**Comment by russcam** [comment] 2019-05-10 01:17
silly me, the same date formatter issue affects search too. 😄 

Since this is confirmed as an issue in Elasticsearch that has been fixed in the next minor of 7.x (https://github.com/elastic/elasticsearch/pull/41871), I'm unsure if we should change anything in the serializer to mitigate.

@codebrain @Mpdreamz we could ensure that we emit the minimum 3 fractional values for all datetimes for both Json.NET and utf8json in 7.0.x client releases, and look to remove this in 7.1.x? Thoughts?

**Comment by codebrain** [comment] 2019-05-21 03:25
As discussed, lets emit minimum 3 fractional places for `7.0.x` and remove in `7.1.x` in line with the server side fix.

**Comment by russcam** [comment] 2019-05-21 04:28
@codebrain Plan is to keep for all of 7.x, as it is possible that someone could use 7.1.0 client with Elasticsearch 7.0.0

**Comment by russcam** [comment] 2019-06-06 07:18
I've opened https://github.com/elastic/elasticsearch-net/pull/3802 to address

**Closed** 2019-06-07 07:40 UTC
Labels: Bug, PR Pending, v7.0.0-beta1
