### ISSUE TITLE
Highlight result is bad.

### ISSUE THREAD

**Issue by edusierra** [elastic/elasticsearch-net#7505] opened 2023-03-28 19:53 UTC
**NEST/Elasticsearch.Net version**: 7.2.1

**Elasticsearch version**: 7.10.2

**.NET runtime version**: 6.0

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
We are creating a query with 2 letters and the result is OK but highlight detail is wrong because it highlights full word not only letters from the query.

**Steps to reproduce**:
 1. We create a 2 letters query : {
    "query": "ab"
}
 2. And get this result: highlights: {manufacturer: ["<ABERYSTWYTH UNIV>"]}

**Expected behavior**
Just AB letters must by enclosed into highlight characters < >.
Result must be highlights: {manufacturer: ["<AB>ERYSTWYTH UNIV"]}

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment] 2023-04-04 07:31
Hi, @edusierra. There's not enough information here for us to attempt to reproduce this fully. As a starting point, I recommend you upgrade the client and server to the latest 7.17.x versions, as your versions are pretty old and may contain bugs which have been fixed. 

Are you able to reproduce this by providing the same query in Kibana? If so, then it's likely a server-side issue or usage error.

If you cannot upgrade at this time, could you please try to reproduce this in a small sample application using the 7.17 client and server in development? If you can reproduce the issue, please provide the complete steps to reproduce, including the mapping for your index and any configuration for the highlighting.

**Comment by stevejgordon** [comment] 2023-04-11 07:14
@edusierra Following up to see if you can provide the requested information for us to assist with this.

**Comment by edusierra** [comment] 2023-04-11 14:16
Hi @stevejgordon , when you try a query with 2 letters the highlight result is OK? I just check my post and when I query "ab" highlight result is "<Abercrombie>" but it must be "<Ab>ercrombie".  Please  let me know

**Comment by stevejgordon** [comment] 2023-05-03 09:41
Closing due to lack of reproducible steps.

**Closed by stevejgordon** 2023-05-03 09:41 UTC
Labels: Awaiting Response, 7.x
