### ISSUE TITLE
Exception is thrown when try to deserialize an object using NTS

### ISSUE THREAD

**Issue by HarelM** [elastic/elasticsearch-net#2444] opened 2016-12-02 23:49 UTC
**NEST/Elasticsearch.Net version**: 2.4.5

**Elasticsearch version**: 2.3.5

**Description of the problem including expected versus actual behavior**:
Expected: Query for shape should return valid results.
Actual: Query throws exception.
**Steps to reproduce**:
 1. I'll write the relevant code below, hoping it will be enough.

I'm using NEST with NTS in order to be able to query OSM data, more specifically all the highways in an area.

So I needed to write a JsonNetSerializer to incorporate the Json converters from NTS (Net Topology Suite):
```cs
public class GeoJsonSerializer : JsonNetSerializer
    {
        public GeoJsonSerializer(IConnectionSettingsValues settings) : base(settings)
        {
            OverwriteDefaultSerializers((s, cvs) =>
            {
                s.Converters.Add(new CoordinateConverter());
                s.Converters.Add(new GeometryConverter());
                s.Converters.Add(new FeatureCollectionConverter());
                s.Converters.Add(new FeatureConverter());
                s.Converters.Add(new AttributesTableConverter());
                s.Converters.Add(new ICRSObjectConverter());
                s.Converters.Add(new GeometryArrayConverter());
                s.Converters.Add(new EnvelopeConverter());
            });
        }

        public GeoJsonSerializer(IConnectionSettingsValues settings, JsonConverter statefulConverter) : base(settings, statefulConverter)
        {
            OverwriteDefaultSerializers((s, cvs) =>
            {
                s.Converters.Add(new CoordinateConverter());
                s.Converters.Add(new GeometryConverter());
                s.Converters.Add(new FeatureCollectionConverter());
                s.Converters.Add(new FeatureConverter());
                s.Converters.Add(new AttributesTableConverter());
                s.Converters.Add(new ICRSObjectConverter());
                s.Converters.Add(new GeometryArrayConverter());
                s.Converters.Add(new EnvelopeConverter());
            });
        }
    }
```

I then indexed ```GeoJSON.Features.Feature``` which worked well.
The last part is what failed - query the data back using the following code:

```cs
        public async Task<List<Feature>> GetHighways(LatLng northEast, LatLng southWest)
        {
            var response = await _elasticClient.SearchAsync<Feature>(
                s => s.Index(OSM_HIGHWAYS_INDEX).Size(5000).Query(
                    q => q.GeoShapeEnvelope(
                        e => e.Coordinates(new List<GeoCoordinate>
                            {
                                new GeoCoordinate(northEast.lat, northEast.lng),
                                new GeoCoordinate(southWest.lat, southWest.lng)
                            }).Field(f => f.Geometry)
                            .Relation(GeoShapeRelation.Intersects)
                    )
                )
            );
            return response.Documents.ToList();
        }
```

this throw the following exception:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: Unexpected token when deserializing object:
StartObject. Path 'hits.hits[1]', line 41, position 8. ---> 
Newtonsoft.Json.JsonSerializationException: Unexpected token when deserializing object: 
StartObject. Path 'hits.hits[1]', line 41, position 8.
```
I looked at the json results using the web interface with the following query and everything looked OK:
```
{
    "query":{
        "bool": {
            "must": {
                "match_all": {}
            },
            "filter": {
                "geo_shape": {
                    "geometry": {
                        "shape": {
                            "type": "envelope",
                            "coordinates" : [[35.0516, 31.7553], [35.0251, 31.7467]]
                        }
                    }
                }
            }
        }
    }
}
```

I also tried my luck with the following issues:  #1849, #2282 but didn't manage to make it work.

As a side note, I have a workaround using ```object``` without the ```GeoJsonSerializer```, but it feels hacky as hell...

**Comment by russcam** [comment] 2016-12-03 01:17
@HarelM Can you put together a small reproducible example in something like Linqpad? Take a look at https://github.com/elastic/elasticsearch-net/issues/2445#issuecomment-264603001 for an example Linqpad program that will get you 90% of the way there. 

My initial suspicion is that the GEOJSON Feature is not indexed in the form you expect it to be; [`Feature` and `FeatureCollection` are not supported geo_shape types.](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#input-structure)

It sounds like deserialization is failing into your POCO that contains the Feature, but I think this will be more clear with an example.

**Comment by HarelM** [comment] 2016-12-03 09:03
I'll post the code here, it's relatively small, I use VS:
You'll need the following nuget packages (package.json):
```xml
<packages>
  <package id="Elasticsearch.Net" version="2.5.0" targetFramework="net452" />
  <package id="GeoAPI" version="1.7.4" targetFramework="net452" />
  <package id="NEST" version="2.5.0" targetFramework="net452" />
  <package id="NetTopologySuite" version="1.14" targetFramework="net452" />
  <package id="NetTopologySuite.IO.GeoJSON" version="1.14" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
</packages>
```
code:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using Elasticsearch.Net;
using GeoAPI.Geometries;
using Nest;
using NetTopologySuite.Features;
using NetTopologySuite.Geometries;
using NetTopologySuite.IO;
using NetTopologySuite.IO.Converters;
using Newtonsoft.Json;
using Feature = NetTopologySuite.Features.Feature;

namespace NESTBug
{
    public class GeoJsonSerializer : JsonNetSerializer
    {
        public GeoJsonSerializer(IConnectionSettingsValues settings) : base(settings)
        {
            OverwriteDefaultSerializers((s, cvs) =>
            {
                s.Converters.Add(new CoordinateConverter());
                s.Converters.Add(new GeometryConverter());
                s.Converters.Add(new FeatureCollectionConverter());
                s.Converters.Add(new FeatureConverter());
                s.Converters.Add(new AttributesTableConverter());
                s.Converters.Add(new ICRSObjectConverter());
                s.Converters.Add(new GeometryArrayConverter());
                s.Converters.Add(new EnvelopeConverter());
            });
        }

        public GeoJsonSerializer(IConnectionSettingsValues settings, JsonConverter statefulConverter) : base(settings, statefulConverter)
        {
            OverwriteDefaultSerializers((s, cvs) =>
            {
                s.Converters.Add(new CoordinateConverter());
                s.Converters.Add(new GeometryConverter());
                s.Converters.Add(new FeatureCollectionConverter());
                s.Converters.Add(new FeatureConverter());
                s.Converters.Add(new AttributesTableConverter());
                s.Converters.Add(new ICRSObjectConverter());
                s.Converters.Add(new GeometryArrayConverter());
                s.Converters.Add(new EnvelopeConverter());
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            const string NEST_BUG_INDEX = "nestbug";
            var client = Init(NEST_BUG_INDEX);
            UpdateData(client, new List<Feature>
            {
                new Feature(new LineString(new []
                {
                    new Coordinate(1,1),
                    new Coordinate(2,2),
                    new Coordinate(10.5, 10.5),
                    new Coordinate(11, 11),
                }), new AttributesTable()),
                new Feature(new LineString(new []
                {
                    new Coordinate(10.5, 10.5),
                    new Coordinate(10.8, 10.8),
                }),new AttributesTable()),
                new Feature(new LineString(new []
                {
                    new Coordinate(12, 12),
                    new Coordinate(13, 13),
                }),new AttributesTable()),
            }, NEST_BUG_INDEX);
            var highways = GetHighways(client, NEST_BUG_INDEX);
            Console.WriteLine(highways.Count);
        }

        private static ElasticClient Init(string NEST_BUG_INDEX)
        {
            var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200/"));
            var connectionString = new ConnectionSettings(
                    pool,
                    new HttpConnection(),
                    new SerializerFactory(s => new GeoJsonSerializer(s)))
                .DefaultIndex(NEST_BUG_INDEX)
                .PrettyJson();
            var elasticClient = new ElasticClient(connectionString);
            if (elasticClient.IndexExists(NEST_BUG_INDEX).Exists)
            {
                elasticClient.DeleteIndex(NEST_BUG_INDEX);
            }
            elasticClient.CreateIndex(NEST_BUG_INDEX,
                    c => c.Mappings(
                        ms => ms.Map<Feature>(m =>
                            m.Properties(ps => ps.GeoShape(g => g.Name(f => f.Geometry)
                                .Tree(GeoTree.Geohash)
                                .TreeLevels(10)
                                .DistanceErrorPercentage(0.2))))));
            return elasticClient;
        }

        public static void UpdateData(ElasticClient client, List<Feature> features, string index)
        {
            var writer = new GeoJsonWriter();
            var id = 0;
            client.Bulk(bulk =>
            {
                foreach (var feature in features)
                {
                    bulk.Index<Feature>(i => i.Index(index).Document(feature).Id(id++));
                }
                return bulk;
            });
        }

        public static List<Feature> GetHighways(ElasticClient client, string index)
        {
            var response = client.Search<Feature>(
                s => s.Index(index).Size(5000).Query(
                    q => q.GeoShapeEnvelope(
                        e => e.Coordinates(new List<GeoCoordinate>
                            {
                                new GeoCoordinate(10, 10),
                                new GeoCoordinate(11, 11)
                            }).Field(f => f.Geometry)
                            .Relation(GeoShapeRelation.Intersects)
                    )
                )
            );
            return response.Documents.ToList();
        }
    }
}
```

**Comment by russcam** [comment] 2016-12-22 03:20
@HarelM I've spent some time looking at this. 

It's a bug in `FeatureConverter`, which has been fixed in https://github.com/NetTopologySuite/NetTopologySuite/commit/70b6755ec84992a4b72ceec3a30b1459068af85b but is not in the latest released NetTopologySuite.IO.GeoJSON 1.14 on nuget.

In [`FeatureConverter` in NetTopologySuite.IO.GeoJSON 1.14](https://github.com/NetTopologySuite/NetTopologySuite/blob/ebc10cfc5f7c14b6bbbd656e64e49c4d05bbc2dd/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON/Converters/FeatureConverter.cs#L117) (_there's no tag in the repo for 1.14, but this looks to be the last commit_), when it gets to the `EndObject` token for the `Feature`, it reads to the next token before returning the deserialized `Feature`. The reader is now at the `EndObject` token of the `IHit<T>`. 

At this point, Json.NET's  [`JsonSerializerInternalReader.PopulateObject()`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2320-L2415) method, which is deserializing the outer `HIt<T>`, reads to the next token again in the predicate of the `do / while()`, since it has just finished deserializing the `_source` `T` property, `Feature` in this case. In doing this, the reader advances to the `StartObject` token of the next `IHit<T>` in the hits array, [which throws the exception you see](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2412-L2413).

The fix for now would be to patch a converter for `Feature` and use that, at least until the next version of NetTopologySuite is out on Nuget. Here's a version that works, along with a complete example

```c#
public static void Main()
{
	const string NEST_BUG_INDEX = "nestbug";

	var settings = new ConnectionSettings(
		new SingleNodeConnectionPool(new Uri("http://localhost:9200")),
		new HttpConnection(),
		new SerializerFactory(c => new GeoJsonSerializer(c)))
		.DefaultIndex(NEST_BUG_INDEX);

	var client = new ElasticClient(settings);

	client.CreateIndex(NEST_BUG_INDEX, c => c
		.Mappings(ms => ms
			.Map<Feature>(m => m
				.Properties(ps => ps
					.GeoShape(g => g
							.Name(f => f.Geometry)
							.Tree(GeoTree.Geohash)
							.TreeLevels(10)
							.DistanceErrorPercentage(0.2)
					)
				)
			)
		)
	);

	var features = new List<Feature>
	{
		new Feature(new LineString(new[]
		{
			new Coordinate(1, 1),
			new Coordinate(2, 2),
			new Coordinate(10.5, 10.5),
			new Coordinate(11, 11),
		}), new AttributesTable()),
		new Feature(new LineString(new[]
		{
			new Coordinate(10.5, 10.5),
			new Coordinate(10.8, 10.8),
		}), new AttributesTable()),
		new Feature(new LineString(new[]
		{
			new Coordinate(12, 12),
			new Coordinate(13, 13),
		}), new AttributesTable()),
	};

	var id = 0;
	client.Bulk(bulk => bulk.IndexMany(features, (i, f) => i.Id(id++)));

	client.Refresh(NEST_BUG_INDEX);

	var response = client.Search<Feature>(s => s
		.Size(5000)
		.Query(q => q
			.GeoShapeEnvelope(e => e
				.Field(f => f.Geometry)
				.Coordinates(new List<GeoCoordinate>
				{
					new GeoCoordinate(10, 10),
					new GeoCoordinate(11, 11)
				})
				.Relation(GeoShapeRelation.Intersects)
			)
		)
	);
}

public class GeoJsonSerializer : JsonNetSerializer
{
	private static readonly JsonConverter[] NetTopologyConverters = {
		new CoordinateConverter(),
		new GeometryConverter(),
		new FeatureCollectionConverter(),
		new FixedFeatureConverter(),
		new AttributesTableConverter(),
		new ICRSObjectConverter(),
		new GeometryArrayConverter(),
		new EnvelopeConverter()
	};

	protected override IList<Func<Type, JsonConverter>> ContractConverters =>
		new List<Func<Type, JsonConverter>>
		{
			t => NetTopologyConverters.FirstOrDefault(c => c.CanConvert(t))
		};

	public GeoJsonSerializer(IConnectionSettingsValues settings) : base(settings)
	{
	}
}

/// <summary>Converts Feature object to its JSON representation.</summary>
public class FixedFeatureConverter : JsonConverter
{
    /// <summary>Writes the JSON representation of the object.</summary>
    /// <param name="writer">The <see cref="T:Newtonsoft.Json.JsonWriter" /> to write to.</param>
    /// <param name="value">The value.</param>
    /// <param name="serializer">The calling serializer.</param>
    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        if (writer == null) throw new ArgumentNullException(nameof(writer));
        if (serializer == null) throw new ArgumentNullException(nameof(serializer));

        var feature = value as IFeature;
        if (feature == null) return;

        writer.WriteStartObject();
        writer.WritePropertyName("type");
        writer.WriteValue("Feature");
        writer.WritePropertyName("geometry");
        serializer.Serialize(writer, feature.Geometry);
        writer.WritePropertyName("properties");
        serializer.Serialize(writer, feature.Attributes);
        writer.WriteEndObject();
    }

    /// <summary>Reads the JSON representation of the object.</summary>
    /// <param name="reader">The <see cref="T:Newtonsoft.Json.JsonReader" /> to read from.</param>
    /// <param name="objectType">Type of the object.</param>
    /// <param name="existingValue">The existing value of object being read.</param>
    /// <param name="serializer">The calling serializer.</param>
    /// <returns>The object value.</returns>
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        reader.Read();
        if (reader.TokenType != JsonToken.PropertyName || (string)reader.Value != "type")
            throw new ArgumentException("Expected token 'type' not found.");
        reader.Read();
        if (reader.TokenType != JsonToken.String && (string)reader.Value != "Feature")
            throw new ArgumentException("Expected value 'Feature' not found.");
        reader.Read();
        object id = null;
        var feature = new Feature();

        while (reader.TokenType == JsonToken.PropertyName)
        {
            switch ((string)reader.Value)
            {
                case "id":
                    reader.Read();
                    id = reader.Value;
                    reader.Read();
                    continue;
                case "bbox":
                    serializer.Deserialize<Envelope>(reader);
                    continue;
                case "geometry":
                    reader.Read();
                    if (reader.TokenType == JsonToken.Null)
                    {
                        reader.Read();
                        continue;
                    }
                    if (reader.TokenType != JsonToken.StartObject)
                        throw new ArgumentException("Expected token '{' not found.");

                    feature.Geometry = serializer.Deserialize<IGeometry>(reader);

                    if (reader.TokenType != JsonToken.EndObject)
                        throw new ArgumentException("Expected token '}' not found.");

                    reader.Read();
                    continue;
                case "properties":
                    reader.Read();
                    if (reader.TokenType != JsonToken.StartObject)
                        throw new ArgumentException("Expected token '{' not found.");

                    feature.Attributes = serializer.Deserialize<AttributesTable>(reader);

                    if (reader.TokenType != JsonToken.EndObject)
                        throw new ArgumentException("Expected token '}' not found.");
                    reader.Read();
                    continue;
                default:
                    reader.Read();
                    while (reader.TokenType != JsonToken.PropertyName)
                        reader.Read();
                    continue;
            }
        }
        if (reader.TokenType != JsonToken.EndObject)
            throw new ArgumentException("Expected token '}' not found.");

        if (feature.Attributes != null && id != null && !feature.Attributes.Exists("id"))
            feature.Attributes.AddAttribute("id", id);

        return feature;
    }

    /// <summary>
    /// Determines whether this instance can convert the specified object type.
    /// </summary>
    /// <param name="objectType">Type of the object.</param>
    /// <returns>
    ///   <c>true</c> if this instance can convert the specified object type; otherwise, <c>false</c>.
    /// </returns>
    public override bool CanConvert(Type objectType)
    {
        return typeof(Feature).IsAssignableFrom(objectType);
    }
}
```

**Closed by russcam** 2016-12-22 03:20 UTC

**Comment by HarelM** [comment] 2016-12-23 14:00
Thank you very much for your detailed response and investigation!
I'll wait for the NTS version release for this fix assuming it is fixed as you say.
Current workaround with ```object``` can be seen here - which is a hell lot simpler, although less type-safe :-)
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.DataAccess/ElasticSearch/ElasticSearchGateway.cs
I'm guessing the performance impact is relatively small so I don't think I need to worry about it.
Thanks again!

**Comment by russcam** [comment] 2016-12-23 22:46
No worries. the converter for features above works (I've tested it), so you could avoid returning `object` and using `GeoJsonReader` by using it instead, up to you 😃
