### ISSUE TITLE
Missed Range query in .net sdk 8+

### ISSUE THREAD

**Issue by knopa** [elastic/elasticsearch-net#7604] opened 2023-04-09 16:35 UTC
**Elastic.Clients.Elasticsearch version**:
8.0.10

**Elasticsearch version**:
8.7

**.NET runtime version**:
.net core 7

**Operating system version**:
Windows 11

**Description of the problem including expected versus actual behavior**:
Missed Range for QueryDescriptor<T> seems was in 7.x
q.Range(r => r.Field(f => f.Date).LessThanOrEquals(date))

**Expected behavior**
Add DateRange, NumberRange to QueryDescriptor<T>

**Comment by stevejgordon** [comment] 2023-04-10 13:42
Duplicate of #7050, which is closed. Range queries will be included in the 8.1.0 release, which we plan to ship quite soon.

**Closed by stevejgordon** 2023-04-10 13:42 UTC
Labels: 8.x
