### ISSUE TITLE
Query Index with dynamic template mapping not working at all

### ISSUE THREAD

**Issue by matthewyang0807** [elastic/elasticsearch-net#7235] opened 2023-02-15 04:24 UTC
**Elastic.Clients.Elasticsearch version**:8.0.5

**Elasticsearch version**:8.0

**.NET runtime version**:6.0

**Operating system version**:Win11

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create a simple index only has dynamic template mapping like this:
![image](https://user-images.githubusercontent.com/117877546/218929520-a4ee944c-04e2-4c40-aa33-a0b15a9a2c7e.png)

 2. then use console to write a simple query like this:
       var es8client = GetES8();
            GetIndexRequest cr = new GetIndexRequest("matthew_simple_dynamictemplateindex");
            var response = es8client.Indices.GetAsync(cr);
            Console.WriteLine(response.Result.ApiCallDetails.HasSuccessfulStatusCode);
            Console.WriteLine(response.Result.ApiCallDetails.HttpStatusCode);
 3. The error will come out:
    
![image](https://user-images.githubusercontent.com/117877546/218929772-c09089a8-6e05-4740-8d4c-82477c002605.png)

**Expected behavior**
I would expect this query can be successful with no error.

**Comment by stevejgordon** [comment] 2023-02-15 10:06
Closing as a duplicate of #7221.

**Closed by stevejgordon** 2023-02-15 10:06 UTC
Labels: 8.x
