### ISSUE TITLE
NEST does not omit fields with null values

### ISSUE THREAD

**Issue by real-az** [elastic/elasticsearch-net#2956] opened 2017-12-15 00:02 UTC
**NEST/Elasticsearch.Net version**: 5.5.0, 6.0.0-alpha1

**Elasticsearch version**: 5.5, 6.0, 6.1

**Description of the problem including expected versus actual behavior**:
NEST does not omit fields with null values. It does this with Elastic 5.5, but not with later versions.

**Steps to reproduce**:

```c#
using System;
// using System.Collections.Generic;
using Nest;

namespace TestNest
{
    internal static class Program
    {
        internal sealed class User
        {
            public string UserId { get; set; }

            public string UserName { get; set; }

            public string AccountId { get; set; }

            public string UserRole { get; set; }
        }

        private static void Main()
        {
            var client = new ElasticClient(new ConnectionSettings(new Uri("http://localhost:9200"))
                .DefaultIndex("users").ThrowExceptions());

            /* run this once
            var userList = new List<User>
            {
                new User
                {
                    UserId = "1",
                    UserName = "u1",
                    AccountId = "1",
                    UserRole = "r1"
                },
                new User
                {
                    UserId = "2",
                    UserName = "u2",
                    AccountId = "1",
                    UserRole = "r1"
                },
                new User
                {
                    UserId = "3",
                    UserName = "u3",
                    AccountId = "1",
                    UserRole = "r2"
                }
            };

            var descriptor = new BulkDescriptor();
            descriptor.IndexMany(userList);
            client.Bulk(descriptor);
            */

            // the query counts the number of users in every role

            // works with Elastic 5.5, 6.0 and 6.1
            var response = client.Search<User>(s => s.Aggregations(fa =>
                fa.Filter("aggs",
                    f => f.Filter(q => q.Term(t => t.Field("accountId.keyword").Value("1")))
                        .Aggregations(ac => ac.Terms("aggs", t => t.Field("userRole.keyword"))))).Size(0));
            var buckets = response.Aggs.Filter("aggs").Terms("aggs").Buckets;
            foreach (var bucket in buckets)
            {
                Console.WriteLine($"{bucket.Key}: {bucket.DocCount}");
            }

            // works with Elastic 5.5
            // throws ServerError: 400Type: illegal_argument_exception Reason: "query malformed, empty clause found at [1:37]"
            // for Elastic 6.0 and 6.1
            response = client.Search<User>(s => s.Aggregations(fa =>
                fa.Filter("aggs",
                    f => f.Filter(q => q.Term(t => t.Field("accountId.keyword").Value(null)))
                        .Aggregations(ac => ac.Terms("aggs", t => t.Field("userRole.keyword"))))).Size(0));
            buckets = response.Aggs.Filter("aggs").Terms("aggs").Buckets;
            foreach (var bucket in buckets)
            {
                Console.WriteLine($"{bucket.Key}: {bucket.DocCount}");
            }

            Console.ReadKey(true);
        }
    }
}
```

**Comment by russcam** [comment] 2017-12-15 01:30
This is a change Elasticsearch 6.0+ regarding validation for the [Filter Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filter-aggregation.html) where the filter is a term query that is deemed [_conditionless_](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/verbatim-and-strict-query-usage.html); NEST by convention does not send `null` values through and so a term query with a `null` value is not serialized and sent as part of the request.

The query from [NEST 6.0.0-beta1](https://www.nuget.org/packages/NEST/6.0.0-beta1) looks like

```json
{
  "size": 0,
  "aggs": {
    "aggs": {
      "filter": {},
      "aggs": {
        "aggs": {
          "terms": {
            "field": "userRole.keyword"
          }
        }
      }
    }
  }
}
```

And the response from Elasticsearch 6.1.0 is

``` json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "query malformed, empty clause found at [5:18]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "query malformed, empty clause found at [5:18]"
  },
  "status" : 400
}
```

Even if the query is sent verbatim, using `.Verbatim()` on the `Term()` query:

```c#
response = client.Search<User>(s => s
    .Aggregations(fa => fa
        .Filter("aggs", f => f
            .Filter(q => q
                .Term(t => t
                    .Field("accountId.keyword")
                    .Value(null)
                    .Verbatim() // override conditionless behaviour and send through null 
                )
            )
            .Aggregations(ac => ac
                .Terms("aggs", t => t
                    .Field("userRole.keyword")
                )
            )
        )
    )
    .Size(0)
);
```

where the query now looks like

```json
{
  "size": 0,
  "aggs": {
    "aggs": {
      "filter": {
        "term": {
          "accountId.keyword": {}
        }
      },
      "aggs": {
        "aggs": {
          "terms": {
            "field": "userRole.keyword"
          }
        }
      }
    }
  }
}
```

The query is still invalid 

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "value cannot be null"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "value cannot be null"
  },
  "status" : 400
}
```

I'm not sure what your query is trying to express, but I suspect you may be looking for the [Exists query](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/exists-query-usage.html) to check that the accountId field exists, or an Exists query in a [Bool query `must_not` clause](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-query-usage.html) to check that the accountId field is missing.

I'm closing this as this is not a change in the .NET client behaviour, but in Elasticsearch.

**Closed by russcam** 2017-12-15 01:30 UTC

**Comment by real-az** [comment] 2017-12-18 20:04
I wrote in my previous post what my query does:

> the query counts the number of users in every role

You suggestion
> I'm not sure what your query is trying to express, but I suspect you may be looking for the Exists query to check that the accountId field exists, or an Exists query in a Bool query must_not clause to check that the accountId field is missing.

do not reflect the query intention. I do not want to check if the field exists or not.
The accountId field exists for every user, it is used for filtering the query results. Sometimes, I need to count the number of users for a specific account, and sometimes for all accounts.

Again, that code works without any problems with Elasticsearch 5.5.
I understand that this problem is caused by the new Elasticsearch version, but what can be done in the code (NEST) to have the same behavior as with Elasticsearch 5.5?

**Comment by russcam** [comment] 2017-12-18 23:32
> The accountId field exists for every user, it is used for filtering the query results. Sometimes, I need to count the number of users for a specific account, and sometimes for all accounts.

You can express this within the query part of a search request, to constrain results to just those matching a specific account, and aggregate on those. You could also constrain to more than one specific account, but then you will still need the filters aggregation to partition into accounts.

> Again, that code works without any problems with Elasticsearch 5.5.
I understand that this problem is caused by the new Elasticsearch version, but what can be done in the code (NEST) to have the same behavior as with Elasticsearch 5.5?

I don't think anything should be done in NEST for this, it's the expected behaviour of Elasticsearch 6.0+. Attempting to rewrite a sub aggregation when the parent aggregation is invalid seems like the wrong approach. The better approach I think is to fix the query sent, to execute one of two different queries, depending on whether the value passed to the Terms aggregation is `null` or an empty string, or not:

```c#
// your term value;
var termValue = "1"; //string.Empty;
IReadOnlyCollection<KeyedBucket<string>> buckets;

if (string.IsNullOrEmpty(termValue))
{
    var response = client.Search<User>(s => s
        .Aggregations(fa => fa
            .Terms("roles", t => t
                .Field("userRole.keyword")
            )
        )
        .Size(0)
    );

    buckets = response.Aggs.Terms("roles").Buckets;
}
else
{
    var response = client.Search<User>(s => s
        .Aggregations(fa => fa
            .Filter("accountIds", f => f
                .Filter(q => q
                    .Term(t => t
                        .Field("accountId.keyword")
                        .Value(termValue)
                    )
                )
                .Aggregations(ac => ac
                    .Terms("roles", t => t
                        .Field("userRole.keyword")
                    )
                )
            )
        )
        .Size(0)
    );

    buckets = response.Aggs.Filter("accountIds").Terms("roles").Buckets;
}

foreach (var bucket in buckets)
{
    Console.WriteLine($"{bucket.Key}: {bucket.DocCount}");
}
```

**Comment by real-az** [comment] 2017-12-18 23:38
Ok, got it. I am already using two different queries, so I will continue doing so :)
Thank you for the help.
