### ISSUE TITLE
Multisearch response fails to deserialize document type

### ISSUE THREAD

**Issue by rm2k** [elastic/elasticsearch-net#2502] opened 2016-12-19 07:28 UTC
**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**:

`MultiSearchResponse.GetResponse<T>(string name)` fails to deserialize document type

**Steps to reproduce**:
 1. `IndexAsync<T>(T document)` where `T` here is the type of my document: works fine
 2. `MultiSearchAsync(IMultiSearchRequest request)`: I'm able to get search hits
 3. `var result = response.GetResponse<T>("name");` : returns `null`, eventhough I have search hits.
 4.  `var result = response.GetResponse<object>("name");` : works

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by gmarz** [comment] 2016-12-20 17:10
Hey @rm2k I'm not quite able to reproduce this, and our [tests](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Search/MultiSearch/MultiSearchApiTests.cs#L116) would have caught any blatant issues.  So, I suspect there's something up with how you have your type/index inference mappings setup.  Would you mind sharing your `ConnectionSettings` as well as the full `Index()` and `MultiSearch` requests?

**Comment by rm2k** [comment] 2016-12-21 09:18
@gmarz hope the following snippets helps:

```
// MyType.cs
[ElasticsearchType(Name="mytype")]
class MyType 
{
  public string Id { get; set; }
  [Keyword]
  public string Category { get; set; }
  [Nested(Name = "my_type1s")]
  public List<MyType1> MyType1s { get; set; }
  . . . // other properties
}
```

``` 
// connection
var nodes = new Uri[] { new Uri($"http://localhost:9200") };

var pool = new StaticConnectionPool(nodes);

var defaultIndex = "my_index";

var connectionSettings = new ConnectionSettings(pool) 
      .DefaultIndex(defaultIndex);

var client = new ElasticClient(connectionSettings);

if (!client.IndexExists("my_index").Exists)
{
  client.CreateIndex("my_index", cex => cex
     .Mappings(mps => mps
          .Map<MyType>(map => map
              .Properties(pos => pos
                  .Nested<Type1>(nsd => nsd
                     .Name(nme => nme.Type1s)
                  )
                  .Nested<Type2>(nsd => nsd
                     .Name(nme => nme.Type2s)
                  )
              )
              .AutoMap()
          )
     )
  );
}
```

```
// Index request
var doc = new MyType { Id = "some-doc-id", . . .};

var docType = nameof(MyType).ToLowerInvariant();

await client.IndexAsync(doc, idx => idx.Type(docType));
```

```
// multisearch request
var field = "category"; //[from query strings]
var termsValues = new string[] { "value1", "value2" }; //[from query strings]

var request = new SearchRequest
{
  Query = new QueryContainerDescriptor<MyType>()
              .Bool(bol => bol
                .Must(mst => mst
                  .Terms(trs => trs
                     .Field(field)
                       .Terms(termsValues)
                     )
                  )
                );
};

var multirequest = new MultiSearchRequest
{
  Operations = new Dictionary<string, ISearchRequest>()
};
multirequest.Operations["search1"] = request;

var response = await client.MultiSearchAsync(multirequest);

// get response
var result = response.GetResponse<MyType>("search1"); //returns null
var result = response.GetResponse<object>("search1"); // returns correct result

```

**Comment by gmarz** [comment] 2016-12-21 17:35
@rm2k I think this might be your problem

```
var docType = nameof(MyType).ToLowerInvariant();
```

This will create the type `mytype`, (all lowercase)  Whereas NEST infers `MyType` as `myType` (camelCased) by default when you call `.Map<MyType>()` or `.GetResponse<MyType>`.  Elasticsearch types are case-sensitive FYI.

Try using the generic index method instead

```
await client.IndexAsync<MyType>(doc);
```

or

```
await client.IndexAsync(doc, idx => idx.Type(typeof(docType)));
```

or even

```
await client.IndexAsync(doc, idx => idx.Type("myType"));
```

Let me know if that solves it.

**Comment by rm2k** [comment] 2016-12-21 21:55
Hi @gmarz ,

Like I mentioned `MyType` is just an example here. My bad indeed :(. I could have just went with `Class Product` to make matters easy. but in any case thanks for all the clarification that came with `MyType`. 

Now to the problem. I tried all the options you gave. still no success.

Just out of interest, I tried this:
```
var result = response.GetResponse<MyType>("search1"); //returns null
var doc = JsonConvert
    .DeserializeObject<Product>(result.Documents.First().ToString()); // it worked
```

I have no idea where I'm going wrong. I'm about to loose all my hair as I've been scratching my head ever since.

**Comment by gmarz** [comment] 2016-12-23 20:41
> Like I mentioned MyType is just an example here. 

Sure, but what I've explained still applies.

> or maybe do I need to map all the properties? because I map the nested ones only.

Shouldn't matter.

I will take a look at this again and try to repro it when I have the spare cycles.  Hopefully you haven't pulled your hair out just yet :p

**Comment by rm2k** [comment] 2016-12-23 21:49
> I will take a look at this again and try to repro it when I have the spare cycles.

that would greatly help as I want to extract ID's for some of the multi search results before passing results to user . so I thought it would be great if I can just do:
```
var result = response.GetResponse<Product>("popular");
string[] popularProducts = result.Documents.Select(doc => doc.Id);
```

**Comment by russcam** [comment] 2017-01-10 00:56
Looks like this

```c#
var request = new SearchRequest
{
  Query = new QueryContainerDescriptor<MyType>()
              .Bool(bol => bol
                .Must(mst => mst
                  .Terms(trs => trs
                     .Field(field)
                     .Terms(termsValues)
                  )
                )
              );
};
```

should also be using the generic `SearchRequest<T>` type

```c#
    var request = new SearchRequest<MyType>
    {
        Query = new QueryContainerDescriptor<MyType>()
              .Bool(bol => bol
                .Must(mst => mst
                  .Terms(trs => trs
                     .Field(field)
                     .Terms(termsValues)
                  )
                )
              )
    };
```
otherwise no index and type will be inferred for `MyType`, so the search will be across all types in all indices.

The above could be refined further to

```c#
var request = new SearchRequest<MyType>
{
    Query = new BoolQuery
    {
        Must = new QueryContainer[] 
        {
            new TermsQuery
            {
                Field = field,
                Terms = termValues
            }
        }
    }
};
```

which makes it a little bit clearer that the generic type on `QueryContainerDescriptor<T>()` is only used for field inference and not needed for the query overall. It also avoids mixing fluent API constructs with object initializer constructs

**Comment by rm2k** [comment] 2017-01-10 07:17
@russcam thanks. that worked

**Comment by russcam** [comment] 2017-01-10 10:42
@rm2k great! I'm going to close this issue

**Closed by russcam** 2017-01-10 10:42 UTC
