### ISSUE TITLE
Indices.Exists returns false even if the index exists for ES 7.2.0

### ISSUE THREAD

**Issue by xucito** [elastic/elasticsearch-net#3950] opened 2019-07-14 19:35 UTC
**NEST/Elasticsearch.Net version**:
7.0.1
**Elasticsearch version**:
7.2.0
**Description of the problem including expected versus actual behavior**:
Regardless of whether the index exists or not the function 
```csharp
Indices.Exists("IndexName").Exists
```
always returns false.

This can be observed for Indices.ExistsAsync too.

![image](https://user-images.githubusercontent.com/36687889/61188302-4d106e00-a68e-11e9-9d1c-0ece409cff3d.png)

Calling ` HEAD accesslogs` in the dev console will return "200 - OK"

**Steps to reproduce**:
 1. Create an index in dev console
 2. Write a console app that calls "Indices.Exists().Exists" function for index created in step 1
 3.  Observe that the return is false instead of expected true

**Comment by russcam** [comment] 2019-07-15 05:24
I can't replicate this issue with NEST 7.0.1 running against Elasticsearch 7.2.0. Here's an example

```c#
private static void Main()
{
    var defaultIndex = "posts";
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

    var settings = new ConnectionSettings(pool)
        .DefaultIndex(defaultIndex)
        .DisableDirectStreaming()
        .PrettyJson()
        .OnRequestCompleted(callDetails =>
        {
            if (callDetails.RequestBodyInBytes != null)
            {
                Console.WriteLine(
                    $"{callDetails.HttpMethod} {callDetails.Uri} \n" +
                    $"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
            }
            else
            {
                Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
            }

            Console.WriteLine();

            if (callDetails.ResponseBodyInBytes != null)
            {
                Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                         $"{Encoding.UTF8.GetString(callDetails.ResponseBodyInBytes)}\n" +
                         $"{new string('-', 30)}\n");
            }
            else
            {
                Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                         $"{new string('-', 30)}\n");
            }
        });

    var client = new ElasticClient(settings);
	
    client.Indices.Delete(defaultIndex);
	
    client.Indices.Create(defaultIndex);
	
    var existsResponse = client.Indices.Exists(defaultIndex);

    Console.WriteLine($"{defaultIndex} index exists: {existsResponse.Exists}");
}
```

which writes the following to the console ("posts" index already exists on first call)

```txt
DELETE http://localhost:9200/posts?pretty=true 
{}

Status: 200
{
  "acknowledged" : true
}

------------------------------

PUT http://localhost:9200/posts?pretty=true 
{}

Status: 200
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "posts"
}

------------------------------

HEAD http://localhost:9200/posts?pretty=true

Status: 200

------------------------------

posts index exists: True
```

Note that `ExistsResponse` checks that the Api call is successful and that the response code is 200:

https://github.com/elastic/elasticsearch-net/blob/c7ec96c1dc130078a058da0e8c6d534aefd09a13/src/Nest/Indices/IndexManagement/IndicesExists/ExistsResponse.cs#L8

And there are integration tests for when an index exists and doesn't exist

https://github.com/elastic/elasticsearch-net/blob/6ee869fcc14ddd51388c47c9c558cd5efcefc21e/src/Tests/Tests/Indices/IndexManagement/IndicesExists/IndexExistsApiTests.cs

I'm going to close this issue for now as it doesn't appear to be an issue. If you have more details and a reproducible example, feel free to reopen 👍

**Closed by russcam** 2019-07-15 05:24 UTC

**Comment by xucito** [comment] 2019-07-22 17:48
I can reproduce the error using the code below (Note, I am using commercial licenses)

```csharp
        static void Main(string[] args)
        {
            var defaultIndex = "posts";


            var settings = new ConnectionSettings(new Uri("<Redacted>"))
                .BasicAuthentication("<Redacted>", "<Redacted>")
                .ServerCertificateValidationCallback(CertificateValidations.AllowAll)
                .DisableDirectStreaming()
                .PrettyJson()
                .EnableDebugMode()
                .OnRequestCompleted(callDetails =>
                {
                    if (callDetails.RequestBodyInBytes != null)
                    {
                        Console.WriteLine(
                            $"{callDetails.HttpMethod} {callDetails.Uri} \n" +
                            $"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
                    }
                    else
                    {
                        Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
                    }

                    Console.WriteLine();

                    if (callDetails.ResponseBodyInBytes != null)
                    {
                        Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                                 $"{Encoding.UTF8.GetString(callDetails.ResponseBodyInBytes)}\n" +
                                 $"{new string('-', 30)}\n");
                    }
                    else
                    {
                        Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                                 $"{new string('-', 30)}\n");
                    }
                });

          var client = new ElasticClient(settings);

            client.Indices.Delete(defaultIndex);

            client.Indices.Create(defaultIndex);

            var existsResponse = client.Indices.Exists(defaultIndex);

            Console.WriteLine($"{defaultIndex} index exists: {existsResponse.Exists}");
            Console.ReadLine();
        }
```

![Untitled](https://user-images.githubusercontent.com/36687889/61652806-deed2c00-acc9-11e9-9990-a8f1b52d648d.png)

I realize now that the Exists is returning a error

```
{System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 87 calling WinHttpSendRequest, 'The parameter is incorrect'.
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError(String nameOfCalledFunction)
   at System.Net.Http.WinHttpHandler.InternalSendRequestAsync(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)}
```

But it doesn't throw any errors and instead returns Exists as "false" with Invalid as false.

This issue seems to be fixed in NEST 7.1.0 so I won't reopen the case.

**Comment by russcam** [comment] 2019-07-23 00:52
The client is behaving as expected. The delete index, create index and index exists API calls above have all failed

1. Delete index API call returns `"acknowledged": false`
2. Create index API call returns `"acknowledged": false`
3. Index exists API call has failed

In each case, `.IsValid` can be checked on the response to determine if the API call is valid as determined by NEST, based on expected response status codes, no error from Elasticsearch, no exception in request pipeline, etc. If you'd prefer the client to throw exceptions instead, you can set `.ThrowExceptions()` on `ConnectionSettings`. 

The response will contain 

- any error from Elasticsearch under the `ServerError` property
- any exception in `OriginalException` property

**Comment by jwagon** [comment] 2019-08-09 03:52
I am reproducing this consistently with Elasticsearch 7.3.0 and NEST 7.1.0

With code like:

```
var result = _client.Indices.Exists("ms-core-integration-test");
```

result.IsValid comes back false, as does result.Exists. result.ServerError is null.

The index definitely exists, I can see (returns 200) it when calling 

```
HEAD /ms-core-integration-test
```

I am getting this response:
```

FailureReason: BadResponse while attempting HEAD on https://XXXXXXXX.us-east-1.aws.found.io:9243/ms-core-integration-test

Audit trail of this API call:
- [1] BadResponse: Node: https://XXXXXXXX.us-east-1.aws.found.io:9243/ Took: 00:00:00.0230221
OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 200 from: HEAD /ms-core-integration-test
Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
Response:
> > 
Exception:
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 200 from: HEAD /ms-core-integration-test
```

That makes no sense, how can the response be invalid but also return 200?

BTW, other operations (search, actually creating the index, etc.) work fine, so it's not as if I'm not connecting properly.

This is definitely a bug and the client is **not** behaving as expected. Please re-open.

**Comment by russcam** [comment] 2019-08-09 04:17
Do you have an example that reproduces the issue, @jwagon? Ideally, a small, succinct project that pins to a known runtime version would be super useful. It's not been possible to replicate this issue locally or in CI, so anything that you can provide to aid investigation will be helpful.

**Comment by russcam** [comment] 2019-08-09 04:57
@jwagon Would you be able to try with the latest 7.x client from CI? To do so, would need to reference the following in your Nuget package sources

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="Elasticsearch.Net CI" value="https://ci.appveyor.com/nuget/elasticsearch-net" />
	</packageSources>
</configuration>
```

then remove the nuget NEST package, and reference the latest `NEST` package (will be 8.1 something).

**Comment by jwagon** [comment] 2019-08-09 16:35
Yeah, I can try that . . . sorry, what is CI though?

**Comment by jwagon** [comment] 2019-08-09 16:36
Thanks for the quick response, BTW, sorry I fell asleep last night . . . I boiled it down to this code, which exhibits the issue:

```
 ElasticClient client;
            NameValueCollection configSection;

            configSection = (NameValueCollection)ConfigurationManager.GetSection("elasticsearch/core");

            var connectionSetting = new ConnectionSettings(new SingleNodeConnectionPool(new Uri(configSection.Get("url"))));
            connectionSetting.DisableDirectStreaming(Convert.ToBoolean(configSection.Get("view-raw-request")));

            //connectionSetting.ThrowExceptions();

            var username = configSection.Get("username");
            var password = configSection.Get("password");

            connectionSetting.BasicAuthentication(username, password);

            client = new ElasticClient(connectionSetting);
            var result = client.Indices.Exists("ms-core-dev");
```

I also put this code in a repo as part of a console app if that helps:

https://github.com/jwagon/TestNestUpgradeTo7

**Comment by jwagon** [comment] 2019-08-09 17:09
@russcam I tried with NEST/Elasticsearch.NET 8.1.x and it works as expected, no "invalid response".

Any thoughts as to a workaround for version 7.1?

**Comment by russcam** [comment] 2019-08-12 02:30
@jwagon I think the problem is related to mime type checking, which has been fixed in: https://github.com/elastic/elasticsearch-net/pull/3972. We'll be putting out a release to nuget shortly with this fix in.

**Comment by jwagon** [comment] 2019-08-12 02:48
@russcam Awesome, thank you.

**Comment by jwagon** [comment] 2019-08-14 01:31
@russcam Is there an ETA for when this fix will be available in the normal NuGet package(s)?

**Comment by russcam** [comment] 2019-08-19 06:12
@jwagon This fix is in [version 7.2.0](https://www.nuget.org/packages/NEST/7.2.0)

**Comment by cesar2** [comment] 2020-02-14 12:00
Hey @russcam , I tried the above code in an example project and worked fine, but at my current project solution, I am getting always invalid response. This is my method:

`
private string defaultIndex = "myindex";
public ElasticClient GetElasticSearchClient()
        {
            var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
            var settings = new ConnectionSettings(pool)
                .DefaultIndex(defaultIndex)
                .DisableDirectStreaming()
                .PrettyJson();

            ElasticClient client = new ElasticClient(settings);
            var existsResponse = client.Indices.Exists(defaultIndex);
            if (existsResponse.IsValid && !existsResponse.Exists)
            {
                bool created = CreateEntityIndex(client);
                if (!created)
                {
                    return null;
                }
            }

            return client;
        }`


existsResponse.IsValid is false and existsResponse.Exists (of course) is also false.

I get : Invalid NEST response built from a successful (404) low level call on HEAD

**Comment by dmitriyklimovich** [comment] 2020-04-08 13:54
I have the same problem with ES 7.6.2 and NEST 7.6.1 on .NET Core

**Comment by ffMathy** [comment] 2021-06-16 08:51
Same problem here. It has re-emerged. Also .NET Core and latest NEST.
