### ISSUE TITLE
Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.

### ISSUE THREAD

**Issue by rayancodeir** [elastic/elasticsearch-net#6413] opened 2022-05-17 19:49 UTC
**NEST/Elasticsearch.Net 17.7.1

elasticsearch:7.17.3:

**.NET runtime 6**:

Windows 11:
I Get this error: 
ApiCall = {Unsuccessful () low level call on PUT: /people/_doc/1?pretty=true&error_trace=true}
DebugInformation = "Invalid NEST response built from a unsuccessful () low level call on PUT: /people/_doc/1?pretty=true&error_trace=true\n# Audit trail of this API call:\n - [1] ProductCheckOnStartup: Took: 00:00:00.0741956\n - [2] ProductCheckFailure: Node: http://localhost...

InnerException = {Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http....

Message = "The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /?pretty=true&error_tra...

public async  Task<IActionResult> Index()
        {
            var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
                .DefaultIndex("Facebook")
                .EnableDebugMode()
                .DisableDirectStreaming();
            var client = new ElasticClient(settings);

            var person = new Person
            {
                Id = 1,
                FirstName = "Martijn",
                LastName = "Laarman"
            };

            //var indexResponse = await client.IndexDocumentAsync(person);
            var fluentIndexResponse = client.Index(person, i => i.Index("people"));

            return View();
        }

I test my code in win 10 , but I get error like this error

**Comment by stevejgordon** [comment] 2022-05-18 05:35
HI, @rayancodeir.

This suggests that the first request is unable to reach the server at "http://localhost:9200". Are you able to reach this URL from a browser? I've just tested with a 7.17.3 docker container locally and can't reproduce an error. How are you running Elasticsearch?

Can you please copy and paste the whole DebugInformation string from the response so we can also see the stack trace.

**Comment by rayancodeir** [comment] 2022-05-19 13:09
> 

Yes I can run ElasticSearch in http://localhost:9200/ And Kibana in http://localhost:5601/

DebugInformation = "Invalid NEST response built from a unsuccessful () low level call on PUT: /people/_doc/1?pretty=true&error_trace=true\n# Audit trail of this API call:\n - [1] ProductCheckOnStartup: Took: 00:00:00.0713671\n - [2] ProductCheckFailure: Node: http://localhost...
-----------------------------------------------------------------------------------------------------------------------------
Invalid NEST response built from a unsuccessful () low level call on PUT: /people/_doc/1?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.0713671
 - [2] ProductCheckFailure: Node: http://localhost:9200/ Took: 00:00:00.0616844
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /?pretty=true&error_trace=true
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:9200)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.Ping(Node node)
   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:

**Comment by rayancodeir** [comment] 2022-05-19 13:11
My ElasticSearch detail:
{
  "name" : "a445e5e4cc90",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "p5nRkZotRZyRPpfUe10s5Q",
  "version" : {
    "number" : "7.17.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "5ad023604c8d7416c9eb6c0eadb62b14e766caff",
    "build_date" : "2022-04-19T08:11:19.070913226Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"

**Comment by stevejgordon** [comment] 2022-05-20 07:19
Thanks for providing that information @rayancodeir. Based on this line in the stack trace:

```
System.Net.Sockets.SocketException (99): Cannot assign requested address
```

It leads me to suspect you might be running the .NET application inside a Docker container? Is that the case? If so, you will need to ensure the contain is on the same Docker network as the Elasticsearch container and that it uses the internal Docker DNS name for the server. `localhost` will not work in those cases.

Also, re-reading the initial issue, you mentioned Windows 11 and Windows 10. If you are not running in a container, is this working on one OS but not the other?

**Comment by rayancodeir** [comment] 2022-05-20 17:38
@stevejgordon  Yes I used Docker.
Yes I use same docker network.
- [ ] "Name": "elasticnetwork",
        "Id": "edfd8f734e0c622c450cfb41debbdc2f23fc4528aea732686fce3a5bbe4b6c19",
        "Created": "2022-04-17T20:02:54.088019Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "04a940d351ba47bf0d35c5e2feb13753a575b0c2170a8e863f0404533144095a": {
                "Name": "kib-node01",
                "EndpointID": "e90ea9640d9de15d7a74ace7b50ef635b2921d2a434964bb3db1365ca0a6fca7",
                "MacAddress": "02:42:ac:12:44:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "60a65d7bc802127e20bc522fb098efed97e325eb32288bb580b70c3bb50f92a4": {
                "Name": "Bigweb",
                "EndpointID": "c1c50b17287862c71699625715651a66972f5c311c685cf2b421cda1327c4216",
                "MacAddress": "02:42:ac:32:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "a445e5e4cc90eac7b1fafebf69a333c656624393c49262d584f4f9d047e0c35c": {
                "Name": "es-node01",
                "EndpointID": "321e531c616fd4b23ad9267bd540304ecd297c3a7ba29569b07ba835cc0170f5",
                "MacAddress": "02:75:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },

**Comment by stevejgordon** [comment] 2022-05-20 17:43
@rayancodeir In that case, `localhost` would not be correct inside a Docker network, which explains the exception. You'll need to use the correct DNS name for the container from inside the network. So at a guess you want to use `http://es-node01:9200` based on your configuration. I presume when you hit `localhost` from the browser you were doing so on an exposed container port for ES.

**Comment by rayancodeir** [comment] 2022-05-20 17:52
Thank you very much.
My problem was solved.
I was involved in this for 20 days and I read all the forums.
thanks again.

**Comment by stevejgordon** [comment] 2022-05-20 17:56
Glad to help @rayancodeir. Things can unfortunately get a little more complex once containers are in the mix. I'll close this now.

**Closed by stevejgordon** 2022-05-20 17:56 UTC
Labels: Awaiting Response, 7.x
