### ISSUE TITLE
Nuget package does not include 4.5 framework files for Nest/Elasticsearch.Net v6.2.0

### ISSUE THREAD

**Issue by gokussx4** [elastic/elasticsearch-net#3423] opened 2018-09-27 14:39 UTC
**NEST/Elasticsearch.Net version**: 6.2.0

**Description of the problem including expected versus actual behavior**:
The nuspec file claims support for .net framework 4.5 but the files included do not include a .net framework 4.5 build.

**Steps to reproduce**:
 1. Review nuspec file for tag 6.2.0, you will see the files listed do not include a .net framework 4.5

**Comment by gokussx4** [comment] 2018-09-27 15:06
Not sure but looks like a backport merge wiped out the net45 files.

https://github.com/elastic/elasticsearch-net/commit/f719e968ca2550d1ea743848250f1a18ff05b427#diff-cef6b0470ec2e19aa9a8ccaf79f38d00

**Comment by Mpdreamz** [comment] 2018-09-28 14:46
Hi @gokussx4 thanks for taking the time to report.

This is a duplicate of https://github.com/elastic/elasticsearch-net/issues/3348

**Closed by Mpdreamz** 2018-09-28 14:46 UTC

**Comment by gokussx4** [comment] 2018-09-28 15:01
Hi @Mpdreamz, the nuspec file should be updated one way or the other though. Your public nuspec file has a targetframework of 4.5 in it and causes a failure because the lib/net45 wasn't included in the files sections. 
So if you aren't supporting .net 4.5 in version 6.2.0 then remove the targetframework so those installing through nuget will clearly see 6.2.0 does not support .net 4.5. 
Otherwise just add the file section back that included that build.

Does that make sense?
