### ISSUE TITLE
Set response body for derived types

### ISSUE THREAD

**Issue by achobanov** [elastic/elasticsearch-net#6149] opened 2022-03-07 13:41 UTC
## Overivew
This is a suggestion, not a bug. I can submit a PR one of these days, 

## Suggestion
1. Change `Body` to internal set/init for **StringResponse** and similar
2. Remove parameterized constructor
3. Change the if-else chain on `ResponseBuilder:229` from
```c#
responseType == typeof(StringResponse)
``` 
to 
```c#
typeof(StringResponse).IsAssignableFrom(responseType)
```

## Version
Targeting 7.x branch

## Thoughts
I know it's not a necessary change, because there are existing workarounds. The one I'm currently using is to derive from `ElasticsearchResponseBase` and define my own Property, which is deserialized from `ResponseBodyInBytes` in the getter. However, I think It would be better the Body is handled internally, since a child of `StringResponse` it's still a `StringResponse`, albeit a more derived one. And if you don't intend to let people derive from them, they should be defined as sealed IMO. 

What do you think?

**Comment by stevejgordon** [comment] 2022-03-21 11:09
Hi, @achobanov.

For v8 we are moving this code into our [transport library](https://github.com/elastic/elastic-transport-net). We generally don't expect derived types from these special low-level response types. Sealing them is something we could consider but I'd need to review historic decisions and consider other use cases such as testing that might be impacted.

Are you looking to solve a problem (or enable a scenario) here, or simply clean up the code? You mention using a workaround, but I'm unsure why you need to do that?

**Comment by achobanov** [comment] 2022-03-21 16:58
@stevejgordon I think "clean up" is a good way to put it.  As of now I've derived from `ElasticsearchResponseBase` (the parent of StringResponse, in case I messed up the name) And I've defined my own property with a getter, which performs the deserialization. 

I proposed it, because it makes sense theoretically and seems like a not-so-big a change. I've also never done open source contribution, so that's sort-of exciting as well :) It is certainly not an issue that needs fixing. I've also fixed the version to 7.13, because we're using AWS provider.

**Comment by stevejgordon** [comment] 2022-03-21 17:16
@achobanov I'm still curious why you need to derive from `ElasticsearchResponseBase` and manage deserialisation yourself?

**Comment by achobanov** [comment] 2022-03-21 21:04
Well, because it seems a good way to centralise the deserialization. I did use StringResponse's body to start with and deserialized in my service method, but since ElasticsearchLowLevelClient allows for custom responses (i.e. its constrained to an interface), why not make one that handles it instead?

**Comment by stevejgordon** [comment] 2022-03-24 12:56
Thanks for the reply. We'd recommend you return `ByteResponse` and do any deserialisation from there. Consumers being able to derive from any of these base or specialised response types is not intended behaviour. I am including this on a worklist we have for the Transport work for v8. I'm going to close this issue as we won't make this change for `7.x` in this responsitory. Thanks for raising this though as it prompted me to revisit this area and will benefit the package going forward.

**Closed by stevejgordon** 2022-03-24 12:56 UTC
Labels: Awaiting Response
