### ISSUE TITLE
ThrowExceptions() not throwing exceptions for 7.x (though it does work for 6)

### ISSUE THREAD

**Issue by dharmaturtle** [elastic/elasticsearch-net#5227] opened 2021-01-03 15:20 UTC
The following test passes in for NEST versions 7.0.0, 7.0.1, 7.9.0, and 7.10.1 (the latest package on Nuget.)

```
public class Person {
    public string Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
  }
  public class UnitTest1 {
    [Fact]
    public void Test1() {
      using var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
        .EnableDebugMode()
        .ThrowExceptions();
      var client = new ElasticClient(settings);
      var missingIndex = Guid.NewGuid().ToString();
      _ = client.Search<Person>(s =>
        s.Index(missingIndex));
    }
  }
```

The same test fails for NEST version 6.8.6 with the following error:
```
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute.
Call: Status code 404 from: POST /6cc513cb-c961-4c97-9715-d822bc6e5168/person/_search?pretty=true&error_trace=true&typed_keys=true.
ServerError: Type: index_not_found_exception Reason: "no such index [6cc513cb-c961-4c97-9715-d822bc6e5168]"
```

All tests were done using **Elasticsearch version 7.10.1**

**Description of the problem including expected versus actual behavior**:
I would expect an error to be thrown in v7. None are thrown. I'm also seeing similar behavior for `UpdateAsync`; in 6.8.6, it'll fail complaining that the Id doesn't exist, but in 7.x it'll just return the nonvalid response and not throw.

Here's a _truncated_ `DebugInformation` from the response for the passing test in 7.10.1:

```
Invalid NEST response built from a successful (404) low level call on POST: /e68098b3-7bd1-47ff-b085-585e93a4890d/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:01.8995930
# Request:
{}
# Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [e68098b3-7bd1-47ff-b085-585e93a4890d]",
```

For 7.x, the `IsValid` on the response is false for both `UpdateAsync` and the above `Search`.

---

# Update 1

In my attempts to find a workaround, I discovered that the following code (added to the test mentioned above) exhibits unexpected behavior too:

```
    new ConnectionSettings(new Uri("http://localhost:9200"))
        .EnableDebugMode(x => {
          System.Diagnostics.Debugger.Break();
        })
```

For 7.10.1, the `Success` property is `true` and the `OriginalException` is null...
but for 6.8.6 it is false and has an `ElasticsearchClientException`.

Both of the `HttpStatusCode`s are `404`.

Here's a truncated `DebugInformation` for 7.10.1:

```
Successful (404) low level call on POST: /acb434ba-ec4c-4728-b40b-7b74bfe13f32/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.3864333
# Request:
{}
# Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [acb434ba-ec4c-4728-b40b-7b74bfe13f32]",
        "resource.type" : "index_or_alias",
```

My current workaround looks like this:

```
        .EnableDebugMode(x => {
          if (System.Text.RegularExpressions.Regex.IsMatch(x.DebugInformation, @"# Response:\s+{\s+""error""")) {
            System.Diagnostics.Debugger.Break();
            throw new Exception(x.DebugInformation);
          }
        })
```

**Comment by stevejgordon** [comment] 2021-01-04 11:01
Hi @dharmaturtle. This was a by-design change, documented in [NEST Breaking Changes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-breaking-changes.html#_high_level_client) for 7.0.0. The document describes the reasoning behind this behaviour. The behaviour you are identifying here is therefore not a bug and is functioning correctly. Based on that, I'll close this issue. Thanks.

**Closed by stevejgordon** 2021-01-04 11:01 UTC
Labels: Bug

**Comment by dharmaturtle** [comment] 2021-01-11 02:00
Thanks. After reading the relevant section, I'm going to alter my workaround to the following:

```c#
        .EnableDebugMode(x => {
          if (x.HttpStatusCode == 404) {
            throw new Exception(x.DebugInformation);
          }
        })
```

**Comment by dtirschek** [comment] 2021-03-23 15:55
Hello,

reading the explanation, I am afraid I don't follow. Yes with NEST we will not call a non-existant endpoint, and yes the only reason a 404 would be thrown is a missing document.
However, I don't understand how trying to update a missing document and thus failing is not an exception (or "Successful"), and why / in which usecase it could be considered a "nice side-effect" to not throw an exception in this case.

**Comment by stevejgordon** [comment] 2021-03-23 16:11
@dtirschek It really depends on how you view a 404. It's a valid response from the server i.e. "you asked me for x, and I couldn't find it". In this regard, the request was "successful" and the status code can be used to determine the next course of action for your specific circumstance. Library consumers are best placed to determine if a missing document then represents non-success and act accordingly. The distinction with unsuccessful is that this is not a failure due to an incorrect URL, malformed request or server error.
