### ISSUE TITLE
Different classes between filters and return document

### ISSUE THREAD

**Issue by imperugo** [elastic/elasticsearch-net#8186] opened 2024-05-12 13:48 UTC
**Is your feature request related to a problem? Please describe.**
In a scenario when you have to read partially the document (a projection) would be nice to have different classes for the query and for the result.
This is absolutely helpful when you use a class that uses the required keyword for some properties, here an example

```csharp
internal sealed class SampleSearchDocument : SearchDocumentBase<string>
{
    public required Guid Property1 { get; set; }
    public string? Property2 { get; set; }
    public required DateTime Property3 { get; set; }
    public required int Property4 { get; set; }
}
```

the projection object could be something like

```csharp
internal sealed class ProjectionSearchDocument
{
    public required Guid Property1 { get; set; }
}

```

With that scenario and `SourceFilter` is not possible because the deserialization process says that some required fields are missing (Property3 and Property4 in this example).

**Describe the solution you'd like**

```csharp
elasticSearchClient.SearchAsync<SampleSearchDocument, ProjectionSearchDocument>(.....)
```

**Additional context**
I'm using a custom serilization class that uses System.Text.Json with source generators

**Comment by silmer** [comment] 2024-05-15 10:56
Agreed! I'm new to Elastic Search myself, but it actually looks like a variant of this feature was available in a previous version based on this thread: https://stackoverflow.com/questions/66143051/elasticsearch-mapping-dto-after-source-filtering-in-net (SearchDescriptor no longer seems to exist in a form where this works the new .NET library).

**Comment by flobernd** [comment] 2024-05-17 07:37
@imperugo @silmer Hi there!

This topic came up a few weeks ago (#8074) in a slightly more complex context, but it essentially boils down to the same feature request.

I already put this item on my roadmap 🙂

**Comment by imperugo** [comment] 2024-05-17 15:58
Hi @flobernd thanks for the feedback. Do you know if there is any workaround to reach the result in the meantime you implement the correct solution?

**Comment by flobernd** [comment] 2024-09-23 07:15
Duplicate of #7792

**Closed by flobernd** 2024-09-23 07:15 UTC
Labels: 8.x, Usability, Area: Generator, Category: Feature
