### ISSUE TITLE
QueryContainer can only hold a single query already contains a XQueryDescriptor

### ISSUE THREAD

**Issue by pirovorster** [elastic/elasticsearch-net#2875] opened 2017-10-12 10:27 UTC
**NEST/Elasticsearch.Net version**: 5.0.0.0

**Elasticsearch version**: 5

When reusing a QueryContainerDescriptor the following exception happens
'QueryContainer can only hold a single query already contains a TermQueryDescriptor`1'. when running

```
queryDesciptor
	.Bool(b => b
		.Must(queryDesciptor                               
			.Term("Test","Test")
		));
```
Or
 'QueryContainer can only hold a single query already contains a BoolQueryDescriptor`1' when running
```
queryDesciptor
	.Bool(b => b
		.MinimumShouldMatch(1)
		.Should(
			queryDesciptor                               
				.Bool(sb => sb
					.Must(new QueryContainer[] { }))
		));
```

However when you first call the below before calling the code below the exception does not happen
`queryDesciptor.Term(o => "Test2", "Test");`

**Comment by russcam** [comment] 2017-10-13 09:18
A `QueryContainer ` can only hold a single query by design. If you need to combine multiple queries, [take a look at `bool` queries and operator overloading](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-queries.html)

Your first example should look like this

```c#
queryDesciptor
    .Bool(b => b
        .Must(m => m                           
            .Term("Test","Test")
        )
    );
```

Your second example 

```c#
queryDesciptor
    .Bool(b => b
        .MinimumShouldMatch(1)
            .Should(s => s                              
                .Bool(sb => sb
                    .Must(new QueryContainer[] { }))
        )
    );
```

Hope that helps!

**Comment by pirovorster** [comment] 2017-10-13 10:14
I still don't get why adding
queryDesciptor.Term(o => "Test2", "Test");
```
queryDesciptor
	.Bool(b => b
		.Must(queryDesciptor                               
			.Term("Test","Test")
		));
```
works 
but not just
```
queryDesciptor
	.Bool(b => b
		.Must(queryDesciptor                               
			.Term("Test","Test")
		));
```

Also it is not obvious that queryDescriptor would add another item to the same container in the above example.

**Comment by russcam** [comment] 2017-10-13 10:44
I don't understand what you mean; your code blocks are identical above (typing error)?

> ```
> queryDesciptor
> 	.Bool(b => b
> 		.Must(queryDesciptor                               
> 			.Term("Test","Test")
> 		));
> ```

won't work because both the term query (`.Term("Test","Test")`) and `bool` query (`.Bool(...)`) are invoked on the same `queryDescriptor` instance which [violates the API.](https://github.com/elastic/elasticsearch-net/blob/7590f306e23337658681542f5e7216ee65f49f2d/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs#L63-L69)

**Comment by pirovorster** [comment] 2017-10-13 10:52
Hi Russ

Sorry my code block start was at the wrong place. Please see my edited previous post.

**Comment by russcam** [comment] 2017-10-13 13:17
That's a very interesting question 😄 

It's related to [where the invocation of a query happens and when it is assigned to the `QueryContainer`, and the initial check to see if the `QueryContainer` contains a query](https://github.com/elastic/elasticsearch-net/blob/69c4cf874ad512df3bfe125cb0dd8f82896e22c9/src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs#L18-L41). 

In the first example, since the container already contains a query when the `.Bool(...)` and inner `.Term()` execute, [a new `QueryContainerDescriptor<T>()` instance is assigned to `container` in both cases](https://github.com/elastic/elasticsearch-net/blob/69c4cf874ad512df3bfe125cb0dd8f82896e22c9/src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs#L19-L21), so each invocation is operating on a different instance.

In the second example however, the container does not yet have a query assigned, so the current `QueryContainerDescriptor<T>()`  instance is used as the container. At the point of [creating the inner `.Term()` query, ](https://github.com/elastic/elasticsearch-net/blob/69c4cf874ad512df3bfe125cb0dd8f82896e22c9/src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs#L23), the `.Bool(...)` query of which it is part has not yet been assigned to container, so the same `QueryContainerDescriptor<T>()`  instance is used as the container. When it comes to setting the `.Bool()` query on the container however, the inner `.Terms()` query has already been assigned.

Both cases should really result in an exception though. I'll reopen this issue to investigate how this can be improved so that the API is not violated. Thanks for opening this @pirovorster  👍

**Comment by pirovorster** [comment] 2017-10-13 14:02
Thanx @russcam 👍

**Closed** 2018-01-24 06:37 UTC
Labels: PR Pending
