### ISSUE TITLE
ElasticClient.search - uppercase field name 

### ISSUE THREAD

**Issue by ssssyj** [elastic/elasticsearch-net#7743] opened 2023-06-01 09:25 UTC
**NEST/Elasticsearch.Net version**:7.17.5

**Elasticsearch version**:8.6.2

**.NET runtime version**:4.6.1

**Operating system version**:win10

**Description of the problem including expected versus actual behavior**:
I can not get value if the field name is in upper case when using client.Search<T>()

**Steps to reproduce**:
 1. My record:
{
"_index": "cmmtest2",
"id": "q3_WdIgBcz5F0I953TG",
"_score": 1,
"_source": {
"characteristic": "150 W8 Prof 0.1 J",
"actual": 0.019991,
"nominal": 0,
"partno": "2022_7933 S2",
"XBAR": "XX"
}
}
 2.My code:
        public class Record2
        {
            public string characteristic { get; set; }
            public float actual { get; set; }
            public float nominal { get; set; }
            public string partno { get; set; }
            public string XBAR { get; set; }
        }

        public static string Initial2()
        {
            var settings = new ConnectionSettings(new Uri("http://localhost:9200")).DefaultIndex("cmmtest2");
            settings.DisableDirectStreaming();
            var client = new ElasticClient(settings);
            var searchResponse = client.Search<Record2>(s=>s.Size(300));
            var record = searchResponse.Hits;
            return record.ToString();
}
I can get value from "Hits" if the field name is in lower case, but cannot get value in upper case like "XBAR".
 

**Expected behavior**
Does it has any solution?

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:
Valid NEST response built from a successful (200) low level call on POST: /cmmtest2/_search?typed_keys=true
# Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.2821033
 - [2] ProductCheckSuccess: Node: http://localhost:9200/ Took: 00:00:00.2624864
 - [3] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.2727551
# Request:
{}
# Response:
{"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"cmmtest2","_id":"qn_VdIgBcz5F0I95SzHQ","_score":1.0,"_source":{
          "characteristic": "150 W8 Prof 0.1 J",
          "actual": 0.019991,
          "nominal": 0,
          "partno": "2022_7933   S2"
}
},{"_index":"cmmtest2","_id":"q3_WdIgBcz5F0I953TG_","_score":1.0,"_source":{
          "characteristic": "150 W8 Prof 0.1 J",
          "actual": 0.019991,
          "nominal": 0,
          "partno": "2022_7933   S2",
          "XBAR":"XX"
}
}]}}

**Comment by stevejgordon** [comment] 2023-06-05 09:29
@ssssyj - This appears to be a duplicate of the question raised on the [discuss forum](https://discuss.elastic.co/t/c-elasticclient-search-field-name-upper-case-issue/334903/2), which I have just answered. Questions and requests for community support are best raised there. We reserve issues on this repository for bug reports and feature requests, so I'll close this issue.

**Closed** 2023-06-05 09:30 UTC
Labels: 7.x
