### ISSUE TITLE
Combine boolQuery Must & Should with nested queries, bug?

### ISSUE THREAD

**Issue by HaggeMan** [elastic/elasticsearch-net#2697] opened 2017-03-29 20:55 UTC
**NEST/Elasticsearch.Net version**:
2.5.2

**Elasticsearch version**:
2.3.2

**Description of the problem including expected versus actual behavior**:
I'm trying to build up a boolQuery using two should queries and one must query all with nestedQuery but the must query never appears. The query I try to produce would look like this...

```json
{
  "from": 0,
  "size": 20,
  "query": {
    "bool": {
      "should": [
        {
          "nested": {
            "query": {
              "terms": {
                "prices.priceKey": [
                  "seprod_se100_124104",
                  "seprod_se100_price_a"
                ]
              }
            },
            "path": "prices"
          }
        },
        {
          "nested": {
            "query": {
              "terms": {
                "customerStock.origin": [
                  "SEPROD_SE100_124104",
                  "SEPROD_SE100_10040",
                  "SEPROD_SE100",
                  "*"
                ]
              }
            },
            "path": "customerStock"
          }
        }
      ],
      "must": [
        {
          "nested": {
            "path": "compatible",
            "query": {
              "term": {
                "compatible.variantId": 245738
              }
            }
          }
        }
      ]
    }
  }
}
```

The query works perfect when running against Elastic Search.

**Steps to reproduce**:
I' build up my query using the following syntax...

```c#
var compatibleQuery = new NestedQuery
{
        Path = "compatible",
        Query = new TermQuery()
        {
             Name = "compatible.variantId",
             Value = 245738
        }
};

var queryPriceContainer = new NestedQuery
{
        Path = "prices",
        Query = new TermsQuery()
        {
             Field = "prices.priceKey",
             Terms = ["seprod_se100_124107","seprod_se100_price_a"]
        }
};

var queryStockContainer = new NestedQuery
{
      Path = "customerStock",
      Query = new TermsQuery()
      {
           Field = "customerStock.origin",
           Terms = ["SEPROD_SE100_124104","SEPROD_SE100_10040","SEPROD_SE100"]
      }
};

var boolQuery = new BoolQuery()
{
      Should = new QueryContainer[] { queryPriceContainer, queryStockContainer },
      Must = new QueryContainer[] { compatibleQuery }
};
```
I can see the MustQuery when debugging, but when passed into my searchRequest the boolQuery only contains the Should queries and not Must queries (see the debuginformation for the result)...

```c#
var filterRequest = new SearchRequest("maincatalog","variant")
{
       Query = boolQuery,
       From = 0,
       Size = 20
};
using (var ms = new MemoryStream())
{
      _client.Serializer.Serialize(filterRequest, ms, Elasticsearch.Net.SerializationFormatting.Indented);
      string jsonQuery = Encoding.UTF8.GetString(ms.ToArray());
};
```

**Provide `DebugInformation` (if relevant)**:

This is the result I get back. 
```json
{
  "from": 0,
  "size": 20,
  "query": {
    "bool": {
      "should": [
        {
          "nested": {
            "query": {
              "terms": {
                "prices.priceKey": [
                  "seprod_se100_124104",
                  "seprod_se100_price_a"
                ]
              }
            },
            "path": "prices"
          }
        },
        {
          "nested": {
            "query": {
              "terms": {
                "customerStock.origin": [
                  "SEPROD_SE100_124104",
                  "SEPROD_SE100_10040",
                  "SEPROD_SE100",
                  "*"
                ]
              }
            },
            "path": "customerStock"
          }
        }
      ]
    }
  }
}
```

**Comment by russcam** [comment] 2017-03-29 21:25
The problem is that the query inside of `compatibleQuery` has no value assigned to `Field` 

```c#
var compatibleQuery = new NestedQuery
{
        Path = "compatible",
        Query = new TermQuery()
        {
             Name = "compatible.variantId", // has a name, but no field
             Value = 245738
        }
};
```

Because of this, it's consider [_conditionless_ (this is 1.x version docs, but behaviour is the same. working on new docs!)](https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/writing-queries.html#conditionless-queries) and therefore is not included in the serialized json. If you add a `Field`, it'll be included.

**Closed by russcam** 2017-03-29 21:25 UTC
