### ISSUE TITLE
[BUG] RequestResponseSerializer DateTime serialization is inconsistent

### ISSUE THREAD

**Issue by cspital** [elastic/elasticsearch-net#7233] opened 2023-02-14 21:31 UTC
**NEST/Elasticsearch.Net version**:
7.16.0

**Elasticsearch version**:
7.16.3

**.NET runtime version**:
NET6.0

**Operating system version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
DateRange queries of the form:
`Query(q => q.Bool(b => b.Must(m => m.DateRange(...))))`
produce inconsistently serialized DateTime values and server errors. RequestResponseSerializer appears to produce unparseable DateTime strings in some use cases.

**Steps to reproduce**:
```csharp
public class FacilityModelV2
{
    ... snipped ...

    [Keyword(Index = true)]
    public string Key { get; set; }

    // stored in format: yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffzzz
    [Date(Format = "date_time")]
    public DateTime RepositoryTimeStamp { get; set; }
}

var results = await _client.SearchAsync<FacilityModelV2>(s => s
    .Index("some_index")
    .TrackTotalHits(true)
    .Size(1000)
    .From(0)
    .Sort(x => x.Ascending(z => z.Key))
    .Query(q => q.Bool(b => b.Must(m => m.DateRange(r => r.Field(f => f.RepositoryTimeStamp).GreaterThanOrEquals(new DateTime(2022, 11, 18, 11, 6, 55, 0, DateTimeKind.Local))))))
    );

// Additionally, one can observe the incorrect serialization behavior without talking to the server at all.
Console.WriteLine(_client.RequestResponseSerializer.SerializeToString(new DateTime(2022, 11, 18, 11, 6, 55, 0, DateTimeKind.Local)));
Console.WriteLine(_client.RequestResponseSerializer.SerializeToString(new DateTime(2022, 11, 18, 11, 6, 55, 1, DateTimeKind.Local)));
```

Outputs the datetime value as `2022-11-18T11:06:55-08:00` and the call fails with the following exception:
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /some_index/_search?typed_keys=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed"
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
   at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)

**Expected behavior**
The RequestResponseSerializer should always output values in a format that the server can parse and understand, a DateTime with a 0 millisecond value is valid and expected in the real world.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**More Context**:
The mapping for RepositoryTimeStamp is:
```
{
  "type" : "date",
  "format" : "date_time"
}
```

when we change the mapping to:
```
{
  "type" : "date",
  "format" : "date_time || date_time_no_millis"
}
```

it works, but `date_time` should work on its own.

We observe this behavior in Kibana as well:
```
GET some_index/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "RepositoryTimeStamp": {
              "gte": "2022-11-18T11:06:55-08:00"
            }
          }
        }
      ]
    }
  }
}
```

This fails with the following server error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [2022-11-18T11:06:55-08:00] with format [date_time]: [failed to parse date field [2022-11-18T11:06:55-08:00] with format [date_time]]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "some_index",
        "node" : "kP_Qc_DJRE6jlrMzSacNlw",
        "reason" : {
          "type" : "parse_exception",
          "reason" : "failed to parse date field [2022-11-18T11:06:55-08:00] with format [date_time]: [failed to parse date field [2022-11-18T11:06:55-08:00] with format [date_time]]",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "failed to parse date field [2022-11-18T11:06:55-08:00] with format [date_time]",
            "caused_by" : {
              "type" : "date_time_parse_exception",
              "reason" : "Failed to parse with all enclosed parsers"
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
```

And this succeeds:
```
GET some_index/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "RepositoryTimeStamp": {
              "gte": "2022-11-18T11:06:55.0-08:00"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by stevejgordon** [comment] 2023-02-15 10:10
Thanks for raising this, @cspital. I'll close this as it's a duplicate of #6444, which does need some review. We need to take care with any changes to the serialization behaviour as it may introduce a break for behaviour some users depend on.

**Closed by stevejgordon** 2023-02-15 10:10 UTC
Labels: 7.x
