### ISSUE TITLE
Elasticsearch.Net.UnexpectedElasticsearchClientException: 'Year, Month, and Day parameters describe an un-representable DateTime

### ISSUE THREAD

**Issue by amandk666** [elastic/elasticsearch-net#5226] opened 2020-12-31 13:05 UTC
NEST/Elasticsearch.Net version: 7.10.0

Elasticsearch version: 7.7

We are migrating ES from version 6.3 to version 7.7. With respect to this, we have updated the Nest and Elasticsearch.Net version from 6.x to 7.10.0 version in our DotNet Code. Now when we are querying in ES using the Sorting query with Date field we are getting an error: "Year, Month, and Day parameters describe an un-representable DateTime". But when we are providing the other date-time field for sorting it's working fine. Below is the ES mappings for both the Datetime field:

"startDate": (with this we are getting error)
                        {
                            "type": "date",
                            "store": true,
                            "format": "dateOptionalTime"
                        }
Sample data with this date field is: "2007-07-25T00:00:00"

"lastUpdateDate": {(With this it's working fine)
                                    "type": "date",
                                    "store": true,
                                    "format": "dateOptionalTime"
                                },
Sample data with this date field is: "2018-07-27T13:44:39Z"

One thing to point here is with ES 6.3 and Nest 6.x version sorting was working fine with the "startDate" field.

The dot net code which we are using here is:

  public ISearchResponse<T> GetProduct(QueryOptions queryOptions, bool withLimit = true)
       {
            SearchDescriptor<T> _search = new SearchDescriptor<T>();

            if (withLimit)
            {
                _search = _search.Index(Constants.IndexName)
                                     .From(queryOptions.Offset)
                                     .Size(queryOptions.Limit);
                
            }
            // first of all, add an ascending sorting for the custom score            
            _search = _search.Sort(s => s
                                .Ascending("_score")
                                );

            foreach (DataModel.Sort sort in queryOptions.Sort)
            {
                string field = sort.sortby.EndsWith("Date") ? sort.sortby : sort.sortby + ".raw";
             
                switch ("Ascending")
                {
                    case Ascending:
                        _search = _search.Sort(s => s
                        .Ascending(field));                    
                       
                        break;
                    case Descending:
                        _search = _search.Sort(s => s
                                            .Descending(field));
                        break;
                }
            }

            var res = client.Search<T>(_search);
             
            return res;

        }

Below is a complete stack trace from the error:

# FailureReason: Unrecoverable/Unexpected BadResponse while attempting POST on ESUrl/IndexName/_search?typed_keys=true
 - [1] BadResponse: Node: EsUrl/ Exception: ArgumentOutOfRangeException Took: 00:00:03.4320348
# Audit exception in step 1 BadResponse:
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at Elasticsearch.Net.Utf8Json.Formatters.ISO8601DateTimeFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Inner Exception: Year, Month, and Day parameters describe an un-representable DateTime.
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at Elasticsearch.Net.Utf8Json.Formatters.ISO8601DateTimeFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: Year, Month, and Day parameters describe an un-representable DateTime. ---> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at Elasticsearch.Net.Utf8Json.Formatters.ISO8601DateTimeFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Nest.DefaultHighLevelSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.DoRequest[TRequest,TResponse](TRequest p, IRequestParameters parameters, Action`1 forceConfiguration)
   at Nest.ElasticClient.Search[TDocument](ISearchRequest request)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by stevejgordon** [comment] 2021-01-06 10:07
Hi @amandk666. I'm not able to repro this locally with a small dummy data set. In 7.x the default serialiser was changed to UTF8Json which may be more script on some oddly formatted dates. I suspect there may be 1 or more docs which for some reason can't be successfully deserialised as dates. 

Could you please try settting `.DebugEnabled()` on `ConnectionSettings` to gather more information. If the data is sensitive and you wish to share the full error with debug enabled, please send it to us at: `microsoft @ elastic.co` (without spaces) and ping me here so I can check for it.

**Comment by amandk666** [comment] 2021-01-12 05:28
Hello @stevejgordon: Had enabled the Debug Mode but getting the same stack trace that we shared previously.

**Comment by stevejgordon** [comment] 2021-01-13 16:15
Thanks @amandk666. That's unfortunate. Are you able to narrow this down to a specific set of documents by limiting your `Offset` and `Limit`? Ideally we need to track down an example of one of the values which is apparently not able to deserialise to a date.

**Comment by amandk666** [comment] 2021-01-14 11:57
Yes @stevejgordon, i tried that and found that which ever date field is having the second value in 2 digit ie., "yyyy-MM-ddTHH:mm:SS" is not working but instead if we have 3 digits in date field value ie., "yyyy-MM-ddTHH:mm:SSS" is working fine.

**Comment by stevejgordon** [comment] 2021-01-19 14:31
Thanks @amandk666 - I'll try again to reproduce based on that.

**Comment by stevejgordon** [comment] 2021-02-04 10:10
Hi @amandk666. My apologies for the delay. I took another look at this today and still cannot reproduce. Here is how I set up my index:

```
PUT issue-5226
{
   "mappings" : {
      "properties" : {
        "endDate" : {
          "type" : "date",
          "store" : true,
          "format" : "date_optional_time"
        },
        "startDate" : {
          "type" : "date",
          "store" : true,
           "format" : "date_optional_time"
        }
      }
    }
}

POST issue-5226/_doc
{
  "startDate" : "2021-01-15T10:45:16",
  "endDate": "2018-07-27T13:44:39Z"
}

GET issue-5226/_search
{
 "sort": [
   {
     "startDate": {
       "order": "desc"
     }
   }
 ]
}
```

The search response here looks like:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "issue-5226",
        "_type" : "_doc",
        "_id" : "ZF6AbHcBPgV8wa_w9gju",
        "_score" : null,
        "_source" : {
          "startDate" : "2021-01-15T10:45:16",
          "endDate" : "2018-07-27T13:44:39Z"
        },
        "sort" : [
          1610707516000
        ]
      }
    ]
  }
}
```

My C# Code against this index is:

```csharp
public void Search()
{
	var response = _client.Search<DateObject>(s => s
		.Index("issue-5226")
		.Sort(sort => sort.Ascending(f => f.StartDate)));

	response.Hits.First().Source.StartDate.Should().Be(new DateTime(2021, 01, 15, 10, 45, 16, DateTimeKind.Unspecified));
}

public class DateObject
{
	public DateTime StartDate { get; set; }
	public DateTime EndDate { get; set; }
}
```

This succeeds without the exception you have reported. Are you able to see if you can advise any differences from your code in order to minimally reproduce the exception?

**Comment by stevejgordon** [comment] 2021-02-11 16:48
Hi @amandk666 - Just following up to see if this is still an issue and to see if you're able to generate a small reproduction or advise of any key differences in my steps above?

**Comment by aman-dubey666** [comment] 2021-02-18 15:07
Hello @stevejgordon,

Is there any way we can connect on a call so that will show you the exact issue. Because it's not the thing which can be solved from here directly. 

Thanks,
Aman

**Comment by stevejgordon** [comment] 2021-02-19 15:34
@aman-dubey666 Do you have a support contract in place? We can certainly kick something off under that if you do. 

In the meantime, I'd like to try and get to a place where we have a small isolated reproduction in a sample app, or steps to reproduce, including the relevant mapping and data samples. Are the steps I provided above close to the scenario you are experiencing?

**Comment by Dharmbeerk** [comment] 2021-03-06 01:14
Hi  @amandk666/stevejgordon

I was able to reproduce the issue and find out the solution of this issue. It is failing in the de-serialization when date is null, so you have to make property nullable.

Here is the steps which I follow to reproduce:

````
   PUT issue-5226
  {
     "mappings" : {
        "properties" : {
          "endDate" : {
            "type" : "date"
          },
          "startDate" : {
            "type" : "date"
          }
        }
      }
  }
  
  POST issue-5226/_doc
  {
    "startDate" : null,
    "endDate": "2020-04-28T17:49:47.108Z"
  }
````


Now if you call with this nest client then it fails in the deserialization with error "Year, Month, and Day parameters describe an un-representable DateTime". 

````
 public void Search()
        {
            try
            {
                var connectionSettings = new ConnectionSettings(new Uri("http://localhost:9200/"))
                              .DefaultIndex("issue-5226");
                var client = new ElasticClient(connectionSettings);
                var response = client.Search<DateObject>(s => s
                    .Index("issue-5226"))
                    ;
                Console.WriteLine("StartDate {0}", response.Hits.FirstOrDefault().Source.StartDate);
                Console.WriteLine("EndDate {0}", response.Hits.FirstOrDefault().Source.EndDate);
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                throw;
            }
          
        }
        public class DateObject
        {
            public DateTime StartDate { get; set; }
            public DateTime EndDate { get; set; }
        }
````

To solve this make StartDate Nullable. This will solve the de-serialization issue.

````
     public class DateObject
        {
            public DateTime? StartDate { get; set; }
            public DateTime EndDate { get; set; }
        }
````

**Comment by stevejgordon** [comment] 2021-03-19 18:23
Sorry @Dharmbeerk, I missed your reply. That's an entirely reasonable potential explanation. 

@amandk666 - Is it possible you're running into null dates in your data?

**Comment by stevejgordon** [comment] 2021-03-26 09:17
@amandk666 I'm going to close this issue, but do please let me know if this continues to be a problem and whether the above suggestion might be related?

**Closed by stevejgordon** 2021-03-26 09:17 UTC
Labels: Awaiting Response, Bug
