### ISSUE TITLE
_client.Map<Entity>(m=>m.SourceField(s=>s.Includes(_list))) does not work anymore

### ISSUE THREAD

**Issue by lichtkabouter** [elastic/elasticsearch-net#1664] opened 2015-12-15 13:04 UTC
Recently we upgraded from 1.6.0 to 1.7.0. After the upgrade the following code did not work anymore:

_client.Map<TEntity>(m => m
                    .InitializeUsing(_definitionList)
                    .SourceField(s => s.Includes(_includesList).Excludes(new string[] { }))
                    .Dynamic(false)
                    ).IsValid;

Before the update everything worked fine (I could filter what data would be in the source and what should be mapped).

The 'old' mapping showed the following:

    "org_2": {
        "mappings": {
            "ifamily": {
                "dynamic": "false",
                "_source": {
                    "includes": [
                        "id",
                        "name",
                    ]
                },
                "properties": { ....

The new mapping fails to show the _source part with the includes.

Could you please state how to make this work correctly again?

Thank you in advance.

**Comment by russcam** [comment] 2016-02-05 09:57
Hey @lichtkabouter, I just tried this with both NEST 1.7.0 and 1.7.1 and both serialized the `_source` into the request

```c#
void Main()
{
	var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
		.SetConnectionStatusHandler(response =>
		{
			// log out the requests
			if (response.Request != null)
			{
				Console.WriteLine("{0} {1} \n{2}\n", response.RequestMethod.ToUpperInvariant(), response.RequestUrl,
					Encoding.UTF8.GetString(response.Request));
			}
			else
			{
				Console.WriteLine("{0} {1}\n", response.RequestMethod.ToUpperInvariant(), response.RequestUrl);
			}

			if (response.ResponseRaw != null)
			{
				Console.WriteLine("Status: {0}\n{1}\n\n{2}\n", response.HttpStatusCode, Encoding.UTF8.GetString(response.ResponseRaw), new String('-', 30));
			}
			else
			{
				Console.WriteLine("Status: {0}\n\n{1}\n", response.HttpStatusCode, new String('-', 30));
			}
		});
		
	var client = new ElasticClient(settings, connection: new InMemoryConnection());
	var _includesList = new[] { "id", "name" };

	var result = client.Map<Ifamily>(m => m
	    .Index("org_2")
	    .InitializeUsing(new RootObjectMapping())
	    .SourceField(s => s.Includes(_includesList).Excludes(new string[] { }))
	    .Dynamic(false)
	);
}

public class Ifamily
{
}
``` 
The output for this is

```javascript
PUT http://localhost:9200/org_2/ifamily/_mapping 
{
  "ifamily": {
    "_source": {
      "includes": [
        "id",
        "name"
      ],
      "excludes": []
    },
    "dynamic": false
  }
}
```

Is it possible the issue is somewhere else?

**Comment by Mpdreamz** [comment] 2016-03-07 12:16
Closing this as could not reproduce, feel free to reopen if this is still an issue @lichtkabouter

**Closed by Mpdreamz** 2016-03-07 12:16 UTC
Labels: Next Legacy Release
