### ISSUE TITLE
StackOverflowException when doing a query against an non matching index - crashes IIS Express and IIS

### ISSUE THREAD

**Issue by mastoj** [elastic/elasticsearch-net#1598] opened 2015-10-22 10:03 UTC
We were updating the index, and in that period we will have a moment were some queries might go against an index that doesn't match the query. We're fine with that, but we didn't expect it to take down the whole server.

I haven't reproduced this in a smaller sample yet, and we can't share everything we have, but here is a step by step scenario of my take on what we have:

1. We created an index X_<date1> with an alias X and one mapping.
2. When rolling out the new version of our application a new index would eventually be created from our event stream, and at the same time we updated the query. Before we have caught up the new query will go against the old index X_<date1> --> StackOverflowException

Our query that caused the problem looked something like this:

        return _esClient.Search<ElasticSearchEnhet, SokEnhet>(_ => _
            .Query(SearchQuery.LagQuery(spørring))
            .From(0)
            .Size(spørring.PageSize)
    //                    .SearchType(SearchType.Scan) // adding this line fixed the problem!
            .Scroll(ScrollLifetime)
            .Filter(SearchFilters.LagFilter(spørring))
            .Index(_alias));

I know there probably are things that we shouldn't do, but I didn't expect it to crash.

**Comment by mastoj** [comment] 2015-10-22 10:04
Elasticsearch.Net version 1.7.1. Elasticsearch version 1.7.2.

**Comment by mastoj** [comment] 2015-10-22 10:32
Looks like there's an issue with Json.Net. We hit it on this line in NEST: https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Resolvers/Converters/ConcreteTypeConverter.cs#L90

**Comment by mastoj** [comment] 2015-10-22 10:49
Note that that Poco is what we try to seralize too, our actual object used for mapping looks different and the actual mapping looks different againg... We are working on paying some technical debt, but this is how it looks like now.

**Comment by Mpdreamz** [comment] 2015-10-27 07:55
@mastoj are you able to share your POCO's complete with any annotations?

Did not have time to dive into this yet (currently in trainings)

**Comment by mastoj** [comment] 2015-10-30 07:56
@Mpdreamz, I haven't had the time either. We had to apply the work around, which was delete the index and recreate it from our event store :). I'll try to add the POCO later, but it isn't nice...

**Comment by Mpdreamz** [comment] 2016-01-06 14:17
@mastoj  closing this because we can not reproduce, if you can still share your POCO we can reopen this one.

**Closed by Mpdreamz** 2016-01-06 14:17 UTC
