### ISSUE TITLE
Unable to create my own TopHitsAggregate when unit testing

### ISSUE THREAD

**Issue by kanup** [elastic/elasticsearch-net#4076] opened 2019-09-06 07:27 UTC
**NEST/Elasticsearch.Net 6.5.1**:

**Cannot create my own TopHitsAggregate to return as a mock result for my unit tests**:

**Steps to reproduce**:
Hi, 
I'm trying to setup IElasticClient.SearchAsync to return my own AggregateDictionary for my unit tests. While I am able to do it for TermsAggregate, TopHitsAggregate is looking difficult.

`
    
    public static class AggregateDictionaryHelper
    {
        // Following method work well for my terms aggregate
        public static AggregateDictionary CreateWithTerms<T>(string aggregationKey,
            Dictionary<T, long> keyDocCountDict)
        {
            Dictionary<string, IAggregate> aggregateDict = new Dictionary<string, IAggregate>
            {
                [aggregationKey] = new BucketAggregate
                {
                    Items = keyDocCountDict.Select(x =>
                        new KeyedBucket<T>(new Dictionary<string, IAggregate>()) {Key = x.Key, DocCount = x.Value}
                    ).ToList()
                }
            };

            return new AggregateDictionary(aggregateDict);
        }

        // This is the method I'm trying to write
        public static AggregateDictionary CreateWithTopHits<TKey, TItem>(string termsAggregationKey,
            string topHitsAggregationKey, Dictionary<TKey, IEnumerable<TItem>> termsTopHitsDict)
        {
            Dictionary<string, IAggregate> termsAggregateDict = new Dictionary<string, IAggregate>
            {
                [termsAggregationKey] = new BucketAggregate
                {
                    Items = termsTopHitsDict.Select(x =>
                        {
                            TopHitsAggregate topHitsAggregate = new MockTopHitsAggregate<TItem>(x.Value);

                            Dictionary<string, IAggregate> topHitsAggregateDict = new Dictionary<string, IAggregate>
                            {
                                [topHitsAggregationKey] = topHitsAggregate
                            };

                            return new KeyedBucket<TKey>(topHitsAggregateDict)
                            {
                                Key = x.Key,
                            };
                        })
                        .ToList()
                }
            };
            return new AggregateDictionary(termsAggregateDict);
        }
    }

    public class MockTopHitsAggregate<T> : TopHitsAggregate
    {
        private readonly IEnumerable<T> _items;

        public MockTopHitsAggregate(IEnumerable<T> items)
        {
            _items = items;
        }

        public override IReadOnlyCollection<TDocument> Documents<TDocument>() where TDocument : class
        {
            if (typeof(TDocument) is T)
            {
                return (_items as IEnumerable<TDocument>).ToList().AsReadOnly();
            }

            return null;
        }
    }
`

The method I'm trying to override in TopHitsAggregate class is not virtual, so I'm not allowed to do this. I'm wondering if there is another way to create my TopHitsAggregate. If not, is it sane to request for this method to be made virtual?

Thanks

**Comment by russcam** [comment] 2019-09-29 23:32
Hi @kanup, 

We have generally steered folks away from this this kind of stubbing/mocking of the client; For example, what is your mock trying to assert or do? It looks like it's trying to provide stubbed top hits for another system under test?

Some ways you may want to handle this:

1. Encapsulate client usage in your in own types which you can mock/stub
2. Use `InMemoryConnection` and return a specific response for a given request. Take a look at this [GitHub issue as an example](https://github.com/elastic/elasticsearch-net/blob/b5cf181bbef2269e26a704f0f21bb7f7be6bdf83/src/Tests/Tests.Reproduce/GithubIssue3745.cs)
3. [Use `Elastic.Xunit` and projects](https://github.com/elastic/elasticsearch-net-abstractions) to spin up a cluster as part of your tests. Granted that these will now be integration tests. These can be referenced from our AppVeyor package feed at `https://ci.appveyor.com/nuget/elasticsearch-net-abstractions` which you can reference by adding to Package Sources.

A combination of approaches may be useful.

**Comment by russcam** [comment] 2019-11-13 03:36
I'm going to close this issue; I've provided some other approaches to consider.

**Closed by russcam** 2019-11-13 03:36 UTC

**Comment by it3xl** [comment] 2023-11-15 10:16
We could have some logic that simply processes NEST query results. And having all those proposed "dances" to just Unit-test it is no so fun, actually.
