### ISSUE TITLE
The speed of search in NEST is two slow

### ISSUE THREAD

**Issue by SilentCC** [elastic/elasticsearch-net#3341] opened 2018-07-30 02:52 UTC
**Some information**:
 1.  Version:

   NEST/Elasticsearch.Net version: 6.2.0
   Elasticsearch version: 6.0.0

 2. Index Size:
     5,800,000 documents ;  60G

 3.  ConnectionSettings :
```
    var node = new Uri(uri);
            var setting = new ConnectionSettings(node);
            setting.DefaultIndex(indexName);

            _elastic = new ElasticClient(setting);
```

**Problem description:**
**The speed of search with ElasticSearch  :**
1. The request body . I use **different keyword**s in every request .I have prepared more than 5,000 keywords for this.
```
   {
	"query": 
	{
		"multi_match": 
		{
			"query":"keyword",
			"fields":["Title","Content"],
			"type":"best_fields",
			"operator":"or",
			"analyzer":"jieba_index"
			
			
		} 
	
		
	},
	"highlight":
	{
		"fields":{
		"Title":{},
		"Content":{}
		}
	}
}
```
2. Use [wrk](https://github.com/wg/wrk) pressure tool 
I use one threads  and  ten connections  during ten seconds.The result is:

<img width="446" alt="screen shot 2018-07-30 at 11 15 59 am" src="https://user-images.githubusercontent.com/26513670/43376290-7aba9dc2-93ec-11e8-8617-bb4d153d5acc.png">

**The speed of Nest:** 
1. The search code with Nest:
```
      [HttpPost("api/{docName}/{indexName}")]
        public SearchResult GetByQuery(string docName,[FromBody]Query query)
        {
            return _elasticSearcher.Search(query.QueryStr);
        }
    
      public SearchResult Search(string queryStr)
        {
            var sw = Stopwatch.StartNew();
            var searchResponse = _elastic.Search<BlogPost>(s => s
                .From(0)
                .Size(15)
                .Query(q => q
                       .MultiMatch(l => l
                              .Query(queryStr)
                              .Fields(new[] { "title", "content" })
                                   .Operator(Operator.Or)))
                .Highlight(p => p
                           .Fields()));
            Console.WriteLine(sw.ElapsedMilliseconds);
            SearchResult result = new SearchResult
            {
                Docs = searchResponse.Documents.ToList(),
                TotalCount = (int)searchResponse.Total,
                TotalTime = sw.ElapsedMilliseconds
            };
            return result;
        }
 
```
2. I use the same keywords and  same way  as the test of ElasticSearch  .

<img width="466" alt="screen shot 2018-07-30 at 11 39 45 am" src="https://user-images.githubusercontent.com/26513670/43376459-6ae66768-93ed-11e8-96cf-364a5b563805.png">

**Comment by russcam** [comment] 2018-07-30 03:02
@SilentCC Before we can consider even starting to look at this, we would need a succinct, but complete reproducible example of how you are measuring latency, as there are many pitfalls associated in macrobenchmarking e.g.

1. How is 16ms being measured? Where is this value reported?
2. How is 800ms being measured?
3. Are caches suitably primed before starting to benchmark?
4. Are you measuring percentiles (50, 90, 95, 99) across multiple runs?

If you can provide further detail, it will be helpful

**Comment by SilentCC** [comment] 2018-07-30 03:47
@russcam Thankyou for your advice. I have already modify description of this issue. 
I don't understand this very well . There is no cache in my test application of NEST.
>3.  Are caches suitably primed before starting to benchmark?

**Comment by russcam** [comment] 2018-07-30 04:40
Thanks for the additional information @SilentCC! 

> I don't understand this very well . There is no cache in my test application of NEST.

> > Are caches suitably primed before starting to benchmark?

NEST uses caches internally, so it's important when benchmarking to ensure that there are a sufficient number of requests made _before_ measuring, to ensure caches are used and application is pre-warmed.

I'm not familiar with `wrk`. Is it also

- serializing the request?
- deserializing the response?
- being run from the same machine from which NEST is running?

A few other observations:

1. `wrk` has opened more connections (280) to Elasticsearch than NEST, which has reached the default limit of 80 (this can be increased with `ConnectionLimit(....)` on `ConnectionSettings`). 
2. It looks like `wrk`s test is testing for volume throughput in conjunction with latency. Is this representative of the application throughput?
3. Are Keep-Alive, Nagling, HTTP compression the same across `wrk` and `NEST`?
4. The query for `wrk` and for NEST look _slightly_ different e.g. fields, type and analyzer. This may not make much difference, but good to use **exactly the same** query

Would you also be able to provide details of your environment e.g. .NET runtime, OS? Another thing to look at is [enabling network tracing](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/network-tracing) and profiling with something like [JetBrain's DotTrace](https://www.jetbrains.com/profiler/), to get a better picture of where the time is being spent.

**Comment by SilentCC** [comment] 2018-08-10 02:55
@russam Thanks for your observations! Now I find that the reason for slow speed of my application is that I create a new ElasticClient instance for each search. I should use a single instance or cache to avoid creating new instances each time.Here is the code of creating ElasticClient instance:
```
            var node = new Uri(uri);
            var setting = new ConnectionSettings(node);
            setting.DefaultIndex(indexName);
            setting.ConnectionLimit(10000);

            _elastic = new ElasticClient(setting);

```

**Comment by russcam** [comment] 2018-08-10 03:08
> I create a new ElasticClient instance for each search. I should use a single instance or cache to avoid creating new instances each time.

Yes, create a single instance of `ElasticClient` (or `ConnectionSettings`, which is the type that really needs caching) and reuse 😄 

Are you happy to close this issue @SilentCC?

**Comment by Mpdreamz** [comment] 2018-08-10 10:59
Closing this 😄 Thanks for reporting @SilentCC let me know if I closed this too fast.

**Closed by Mpdreamz** 2018-08-10 10:59 UTC
