### ISSUE TITLE
NEST is super slow on AspNet Core 

### ISSUE THREAD

**Issue by ran729** [elastic/elasticsearch-net#2730] opened 2017-04-20 12:07 UTC
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**:
i just updated my .net web api app from .net framework 4.5 to .net core 1.1, 
i noticed that the NEST library is 2-3 times slower (in most cases... could also be less or even more) than it was when i was using .net framework 4.5, with any action i make - create index, search, get, index, upsert, aggregation, really everything is slower.
i am using visual studio 2017 rc, running with Kestrel server.

**Steps to reproduce**:
 1. just do every action in NEST and compare .net core to .net framework
 2. see the performance gaps

**Provide `ConnectionSettings` (if relevant)**:
config =  {
        "Servers" : [ "http://localhost:9200" ],
        "ExposeRawResponse" : true,
        "UsePrettyResponses": true,
        "EnableMetrics" : true,
        "MaximumRetries": 3,
        "Timeout": 30000,
        "ConnectTimeout": 10000,
        "RequestLog":  {
            "Warning": 1000,
            "Error": 5000
        }
    }

ConnectionSettings settings = new ConnectionSettings(connectionPool, new HttpConnection(),
                new SerializerFactory((jsonSettings, nestSettings) =>
                {
                    jsonSettings.DateParseHandling = DateParseHandling.DateTimeOffset;
                    jsonSettings.Converters = new List<JsonConverter> { new DataPointConvertor() };
                })
                )
                .DisableDirectStreaming(config.ExposeRawResponse)
                .OnRequestCompleted(ConnectionStatusHandler)
                .PrettyJson(config.UsePrettyResponses)
                .MaximumRetries(config.MaximumRetries)
                .RequestTimeout(TimeSpan.FromMilliseconds(config.Timeout))
                .PingTimeout(TimeSpan.FromMilliseconds(config.ConnectTimeout))
                .EnableHttpCompression()
                .ThrowExceptions()
                .DefaultFieldNameInferrer(i => i);// don't let NEST mess with us
            Client = new ElasticClient(settings);

**Comment by alexsandro-xpt** [comment] 2017-04-21 03:21
I'm using ES 5.3.0 and NEST 5.3.1 without problems.

**Comment by russcam** [comment] 2017-04-24 01:46
@ran729 How are you benchmarking comparisons between .NET 4.5 and .NET Core? Do you have a benchmarking/test harness that you can share?

Would you be able to provide details for how you are using `Client` e.g. is it a singleton, instance per request, etc?

.NET 4.5 and .NET Core use different implementations of `HttpConnection`, the former using `HttpWebRequest` while the latter, `HttpClient`. We've not seen a 2-3x difference in performance in our integration tests. You say you're running with Kestrel in 2017, which sounds like you're using NEST in a web app. If you remove the web app from your benchmarking e.g. with a console application, such that you are only benchmarking the client, do you still the same problem?

**Comment by JefStat** [comment] 2017-04-24 15:30
After an update to production with aspcore, under a full load elasticsearch request would begin to fail after about 2-5 mins at our peak time of day with the following exceptions. From the brief inspection the response times started to build up very quickly until the following exception occurred on all requests.
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.IndicesExists[T](String index, Func`2 requestParameters)
   at Nest.LowLevelDispatch.IndicesExistsDispatch[T](IRequest`1 p)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
```
Unfortuantely we ran out of time to triage the issue and reverted back to WebApi 2 for our server.

**Comment by Mpdreamz** [comment] 2017-05-03 21:12
@JefStat I've opened up https://github.com/elastic/elasticsearch-net/pull/2753 which should help surface what is going on. As per #2751 that task cancelled should not bubble out like that. Hopefully we can see what is going on. Please open an issue when #2753 lands and you attempt to move again!


@ran729 closing this issue because we can not reproduce but we'll be monitoring this even more closely. Please don't take this as us disengaging and if you have more information that could help us diagnose let us know here!

**Closed by Mpdreamz** 2017-05-03 21:12 UTC

**Comment by JefStat** [comment] 2017-08-18 14:51
Re-attempting the deploy now
The following fix  https://github.com/elastic/elasticsearch-net/pull/2785 particularily 
> Lowers the default concurrent connection limit when we find that HttpClient runs with CurlHandler, this to minimize TCP connections bleeding.

Sounds like possible fix to the issue I was seeing in production. Since with the elasticsearch exception iirc I was also seeing `CurlHandler.ThrowIfCURLEError`
