### ISSUE TITLE
Mapping is wrong on dynamic template generic type

### ISSUE THREAD

**Issue by vovikdrg** [elastic/elasticsearch-net#3110] opened 2018-02-25 09:01 UTC
**NEST/Elasticsearch.Net version**:
6.0.1
**Elasticsearch version**:
6.2.2
**Description of the problem including expected versus actual behavior**:
I want to ignore all fields to prevent automapping. So I've added generic and index not analyzed
ES accepted my mapping but when i try to index it shows error
**Failed to parse value [not_analyzed] as only [true] or [false] are allowed.**

**Steps to reproduce**:
  var createIndexResponse = _client.CreateIndex(FlymarkAppSettings.ResultIndexName,
                i =>
                    i.Mappings(m =>
                        m.Map<StreamCategoryDetailsView>(map =>
                            map.DynamicTemplates(d => d
                                    .DynamicTemplate("default",
                                        dt => dt.Match("*")
                                            .Mapping(dtm => dtm
                                                .Generic(k => k.Index(FieldIndexOption.NotAnalyzed)))))
                                .Properties(p => p
                                    .Number(n => n.Name(f => f.CategoryIds))
                                )
                            )));

Expected result 

 .Generic(k => k.Index(FieldIndexOption.NotAnalyzed))))) should accept true or false

**Comment by lakario** [comment] 2018-03-06 18:51
Duplicates #3103.

**Comment by russcam** [comment] 2018-04-30 02:15
Thanks for opening @vovikdrg. Agree with @lakario, this is a duplicate of #3103, so I'm going to close this issue to track there. Thanks!

**Closed by russcam** 2018-04-30 02:15 UTC
