### ISSUE TITLE
More Like This query is sending a null _index value to the server

### ISSUE THREAD

**Issue by ahazelwood** [elastic/elasticsearch-net#2143] opened 2016-06-29 16:57 UTC
I am attempting to do a "More Like This" query and in looking at the raw json query sent to the server, there is an attached _index field that is set to null which causes a "Can't get text on a VALUE_NULL" exception within elasticsearch.  There doesn't appear to be a way to either remove the _index value or set it.

c# code being used to query for matching results:

                var results = clientSearch.Search<DupeAtom>( req => 
                    req.Index( Indices.Index( DuplicateIndex ) ).Query( q => 
                        q.MoreLikeThis( mlt => 
                            mlt.Like( l => l.Document( d => d.Id( atom.Id ) ) )
                            .Fields( f => f.Fields( "title", "text" ) )
                            .MinTermFrequency(1)
                            .MinDocumentFrequency(1)
                            .MaxDocumentFrequency(100)
                        )
                    ).Fields( s => s.Fields( "id", "title" )).Size(10)
                );

Generated query to the server

{"size":10,"fields":["id","title"],"query":{"mlt":{"fields":["title","text"],"like":[{"_index":null,"_type":"dupeatom","_id":"kyXzqPXzZt"}],"min_term_freq":1,"min_doc_freq":1,"max_doc_freq":100}}}]

If I manually remove the "_index" property in the like object, the query is correct.

Thanks.

**Comment by gmarz** [comment] 2016-07-07 19:55
Hi @ahazelwood what version of NEST are you using?

**Comment by gmarz** [comment] 2016-07-28 15:15
@ahazelwood any update on this?

**Comment by Mpdreamz** [comment] 2016-09-13 14:00
Closing this because I can not reproduce this using the latest NEST.

@ahazelwood if you still see this issue please reopen and let us know!

**Closed by Mpdreamz** 2016-09-13 14:00 UTC
