### ISSUE TITLE
"Invalid version string\r\nParameter name: fullVersion" // at Elasticsearch.Net.VersionInfo.StoreVersion(String fullVersion)

### ISSUE THREAD

**Issue by bobrien27** [elastic/elasticsearch-net#5539] opened 2021-04-14 19:42 UTC
**NEST/Elasticsearch.Net version**: 7.12.0

**Elasticsearch version**: 7.12.0

**Description of the problem including expected versus actual behavior**:
"new ConnectionSettings();" continues to give me errors whether using a local or domain hosted version of ElasticSearch and am given the error message "Invalid version string\r\nParameter name: fullVersion"

**Steps to reproduce**:
 1. Create Xamarin Forms Application
 2. Create any type of query call using: 
        var node = new Uri("http:elasticsearch:9200");
        var settings = new ConnectionSettings(node); //*FAILS HERE, creating ConnectionSettings*
        var client = new ElasticClient(settings);

**Expected behavior**
Simple queries have been working since version 7.8 but after upgrading to Java 15 and ES 7.12.0 I am unable to create an ElasticClient as it is unable to successfullt create ConnectionSettings whether it be a "specific-url:9200" or "localhost:9200".

**Provide `ConnectionSettings` (if relevant)**: 
N/A

**Provide `DebugInformation` (if relevant)**: 
StackTrace given by debug:
"""  
**at Elasticsearch.Net.VersionInfo.StoreVersion(String fullVersion)**
   at Elasticsearch.Net.MetaDataHeader..ctor(VersionInfo version, String serviceIdentifier, Boolean isAsync)
   at Elasticsearch.Net.MetaHeaderProvider..ctor()
   at Elasticsearch.Net.ConnectionConfiguration`1..ctor(IConnectionPool connectionPool, IConnection connection, IElasticsearchSerializer requestResponseSerializer)
   at Nest.ConnectionSettingsBase`1..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializerFactory, IPropertyMappingProvider propertyMappingProvider)
   at Nest.ConnectionSettings..ctor(Uri uri)
"""

ElasticSearch itself is working locally and across domains after upgrading to Java 15 and the ELK collective, however upon upgrading NuGet Packages: ElasticSearch.Net and NEST, I have not been able to use "var settings = new ConnectionSettings(node);" to establish a connection and am given an error.

**Comment by stevejgordon** [comment] 2021-04-19 07:18
Thanks for reporting this @bobrien27. I'll take a look to see if I can reproduce this and track down the cause.

**Comment by stevejgordon** [comment] 2021-04-19 12:26
After attempting to reproduce this, I'm currently unable to. I created a new Xamarin Forms app (5.0.0.2012) in Visual Studio, added NEST NuGet dependency and inserted the code you provided into the ctor of the `App` class. I was able to start the application through the emulator, without observing an error when creating the `ConnectionSettings`. The only change I made was to set the Uri to a valid URL as the code above is invalid. However, I presume that's a typo since it would fail earlier, and with a different error, than the one you've observed.

I would like to try to identify why this is causing an exception in your application. My guess right now is this due to some difference in the runtime. Are you able to provide a minimal reproduction in a public repo I can test locally, or advise of any additional steps, such as the runtime version needed to get to a complete reproduction of the failure?

**As a short-term workaround for your application:** 
The code where you've observed the exception is part of a feature added in 7.11.0 which detects the client and runtime version through reflection. If you only need basic search functionality, you could continue using 7.10.1 or earlier, before that change was introduced.

**Comment by stevejgordon** [comment] 2021-04-20 11:03
@bobrien27 I've included a small fix in 7.12.1 which should avoid failed runtime detection from crashing your application. Please let me know if that helps? I'd still like to identify the runtime and above information to try and reproduce this since I'd like to investigate the root cause.

**Comment by bobrien27** [comment] 2021-04-20 19:02
@stevejgordon Thank you for your response, that issue has gone away since upgrading the package to 7.12.1. I restarted visual studio and the elasticsearch server and downgraded to 7.12.0 but was not able to reproduce it now. I do have an issue with posting slices but otherwise everything else is working, may have been a fluke with VS.

**Comment by stevejgordon** [comment] 2021-04-21 05:23
Thanks for the update @bobrien27. I'm glad it seems to have resolved. I'll close this issue, but do open a new one if you experience it again and we'll dig into it. Feel free to open an issue for that other issue as well.

**Closed by stevejgordon** 2021-04-21 05:23 UTC
Labels: Awaiting Response, Bug
