### ISSUE TITLE
Possible memory leak after 2.4.4

### ISSUE THREAD

**Issue by RTodorov** [elastic/elasticsearch-net#2401] opened 2016-11-21 11:18 UTC
**NEST/Elasticsearch.Net version**:
2.4.4

**Elasticsearch version**:
2.2.2

**Description of the problem including expected versus actual behavior**:
Guys, while using 2.4.3, I can serve hundreds of simultaneous users without any issues. After upgrading to 2.4.4/2.4.5/2.4.6, my app started leaking memory. It usually runs with just about 80mb, after 2.4.4 in just a few hours it gets to 4gb. I'm sorry but I didn't have time to go deep into profiling NEST but I managed to isolate the problem and found out that it's something to do with NEST or ElasticSearch .NET Client.

**Steps to reproduce**:
 1. Create one single instance of ElasticClient
 2. Use jMeter or whatever to spawn multiple connections
 3. See the difference on memory consumption from 2.4.3 to the upper versions

Can I help any further?

**Comment by Mpdreamz** [comment] 2016-11-21 12:13
Hi @RTodorov thanks for opening this issue, diving on it straight away.

Using JMeter to do you hit a Search API endpoint? Can you share that call?

**Comment by Mpdreamz** [comment] 2016-11-21 12:21
Also if you can share your ConnectionSettings that would be useful as well

**Comment by RTodorov** [comment] 2016-11-21 12:23
Hey @Mpdreamz, I use JMeter to hit an endpoint that builds a dynamic query. I'll get an example query and share here.

I'm using the default ConnectionSettings with just my ES endpoint:

``new ConnectionSettings("http://localhost:9200/index-name/type");``

**Comment by RTodorov** [comment] 2016-11-21 12:28
I'm not sure how useful this query is without the complete structure of my index but here it goes: http://pastebin.com/QdX8HFT8

This is one of my simplest queries but is enough to cause the leak.

**Comment by Mpdreamz** [comment] 2016-11-21 12:46
I tried to verify if i see a similar behaviour using 

https://gist.github.com/Mpdreamz/ec7f639632acf53448842ea42c3cf2fe

(using NEST 2.4.6 against elasticsearch 2.3.0)

But the memory consumption stays contanst (around 70-80mb) for the past 15 minutes. 

Are you able to create a memory dump? I will try to remodel my setup to match you query more closely.

**Comment by Mpdreamz** [comment] 2016-11-21 12:48
How are you sharing the ElasticClient instance between requests?

**Comment by RTodorov** [comment] 2016-11-21 12:58
I tried several different methods including: static instance, using a factory with Dictionary/ConcurrentDictionary to cache 5 clients and distribute the requests over them... all with the same result.

How can I create a memory dump?

**Comment by Mpdreamz** [comment] 2016-11-21 13:32
The hardcore way: http://www.diaryofaninja.com/blog/2014/03/20/investigating-aspnet-memory-dumps-for-idiots-like-me

If you have dotMemory (i think a trial is fully functional for 30days) you can easilly attach it to your local development machine's IIS web instance wait for the memory leak to be noticable and then use dotMemory to take the memory dump. 

The latter option will be easiest and safest.

**Comment by RTodorov** [comment] 2016-11-21 13:45
Not a Windows user, sorry. I'm hosting my application on Linux via Docker containers, using .NET Core 1.1

**Comment by Mpdreamz** [comment] 2016-11-21 13:55
Ok no problem, can you share how you instantiate the client and share it? Just so I have a full picture.

Will bisect the changes after 2.4.3 and after to see if I can spot an offender

**Comment by RTodorov** [comment] 2016-11-21 14:10
```
protected ElasticClient GetClient(string indexType, string country)
{
    var key = String.Format("{0}-{1}", indexType, country);
    if (!ClientsList.ContainsKey(key)) {
        var uri = new Uri(String.Format("{0}/{1}-{2}/{3}", Config.Endpoint, IndexName, country, indexType));

        Logger.LogInformation("Spawning new ElasticSearch client: {0}", uri);

        ClientsList.AddOrUpdate(key, new ElasticClient(new ConnectionSettings(uri)), (a,b) => b);
    }

    return ClientsList[key];
}
```

Each country has a different Index so I spawn one client per country, or, per index.

**Comment by Mpdreamz** [comment] 2016-11-21 14:39
How many clients does this total? 

The URI you pass to the connectionsettings should be the root of the elasticsearch instance. 

All operations will use that as the baseUri. 

You are better off calling 

```
.Search(s=>s
    .Index(index)
    .Type(indexType)
)
```

Explicitly on each search call. 

All the caches (both json.net and ours) are per connectionsettings. Still does not explain fully the difference in between versions though

**Comment by RTodorov** [comment] 2016-11-21 14:41
It does only 5 clients but anyway I'll change to what you suggested for the sake of using the correct pattern.

**Comment by RTodorov** [comment] 2016-11-21 16:30
Ok, did the change but the result remains the same. With 2.4.6, memory jumped from 80mb to 400mb in a matter of seconds.

**Comment by Mpdreamz** [comment] 2016-11-21 18:10
@RTodorov since doing a memory dump is not that useful are you available for a screenshare session this week? We'll continue to bisect the commits after `2.4.3` and try to reproduce in the mean time.

**Comment by RTodorov** [comment] 2016-11-21 23:30
@Mpdreamz yes, sure, will send you my Skype over twitter so we can arrange that!

**Comment by Mpdreamz** [comment] 2016-11-28 21:09
@RTodorov sorry for not reaching out, was out doing elasticsearch training all of last week. 

My colleague @russcam spotted this in the change set between `2.4.3` and `2.4.4`

https://github.com/elastic/elasticsearch-net/commit/139ccfebbdbe9778201de5380000c6e4f9f33a8c#diff-4eb6f7a15a069c6324a632b9426e6046L75

This one line change had a huge impact and also surfaced #2417 which is related to this change. 

We'll get a fix out tomorrow 👍

**Comment by michaellandi** [comment] 2016-11-28 21:47
I'm pretty sure I'm seeing the same thing using 2.4.7 or any of the 5.0.0 RCs.

**Comment by Mpdreamz** [comment] 2016-11-28 21:50
@michaellandi sorry to hear, the fix is forthcomming `> 2.4.7` and `> 5.0.0 rc3`

**Comment by RTodorov** [comment] 2016-11-29 09:50
Hey @Mpdreamz, no problem! I'm glad I could help raising the issue.

I'll test the new version as soon as it's out, run jMeter and share the results.

Thanks for the great work!

**Comment by russcam** [comment] 2016-12-01 05:49
@RTodorov @michaellandi new releases of [2.x](https://www.nuget.org/packages/NEST/2.5.0) and [5.x](https://www.nuget.org/packages/NEST/5.0.0-rc4) out on nuget; would you mind taking them for a spin and checking to see if you still see the same issues?

**Comment by RTodorov** [comment] 2016-12-02 18:32
Hey @russcam @Mpdreamz , everything seems to be fine now with 2.5.0 on my side, my app is back to the 80mb average even after 2 hours under heavy loading from JMeter. Thanks for the fix!

**Comment by michaellandi** [comment] 2016-12-02 18:44
@russcam Thanks so much for getting a fix out soon.  Unfortunately I'm traveling with limited connectivity for the next two weeks.  But I'll definitely be pulling the new version and testing when I get back.

**Comment by michaellandi** [comment] 2016-12-19 19:59
@russcam I am also able to confirm that things are working fine with 2.5.0.  Memory allocation of my app seems stable after several hours of testing (previously I would notice coninuous app memory growth).  Thanks for getting this fix out so quick.

**Comment by russcam** [comment] 2016-12-19 20:03
Thanks for getting back @michaellandi, happy to hear that all is now well 😄 

I'm going to close this issue, but feel free to open this or a new one if the problem returns.

**Closed by russcam** 2016-12-19 20:03 UTC
