### ISSUE TITLE
unable to use dynamic templates with MapFromAttributes

### ISSUE THREAD

**Issue by jayhilden** [elastic/elasticsearch-net#1318] opened 2015-04-20 22:50 UTC
I'm trying to use a dynamic template to make all strings multi-fields.  I also want to run ```MapFromAttributes``` so that the ES type ```geo_point``` is correctly applied to a lat/long.

Here is my sample:

```
    _client.Map<RedemptionES>(m =>
        m.DynamicTemplates(dt => dt.Add(a => a
               .Name("string_fields")
                .Mapping(tm => tm
                    .Generic(mf => mf
                        .Type("{dynamic_type}")
                        .Index("analyzed")
                        .Fields(mff => mff
                            .Generic(g => g
                                .Name("raw")
                                .Type("{dynamic_type}")
                                .Index("not_analyzed")
                            )
                        )
                    )
                )
               .MatchMappingType("string")
            )
        )
        .MapFromAttributes() //THIS IS THE LINE CAUSING PROBLEMS
    )
```

If I run the dynamic template without the ```MapFromAttributes()``` the string fields are correctly multi-fields when they are created on the fly but my geo_point field is just mapped as 2 doubles instead of an ES geo_point.

If I run the dynamic template *with* ```MapFromAttributes()``` then my geo_point is mapped correctly but any defined string field does *not* get created as a multi-field.

Is it possible to get both to work together?

**Comment by gmarz** [comment] 2015-04-21 17:06
@jayhilden hmm, your example should work and I've been unable to successfully reproduce this.

Mind sharing your `RedempetionES` poco?

**Comment by jayhilden** [comment] 2015-04-21 17:51
@gmarz here are 2 samples that should help clarify the issue/question.

**Example 1: I create the dynamic template, then call MapFromAttributes()**
```
    public class GeoPointTest
    {
        [JsonProperty("lat")]
        public double Latitude { get; set; }

        [JsonProperty("lon")]
        public double Longitude { get; set; }
    }

    [ElasticType(Name = "test1")]
    public class MappingTest1
    {
        [ElasticProperty(Type = FieldType.GeoPoint)]
        public GeoPointTest GeoPoint { get; set; }
        public string Field1 { get; set; }
    }

    internal class ElasticSearchRunner
    {
        private static void Main(string[] args)
        {
            var ninjectKernel = new StandardKernel(new VBNinjectModule());

            var esClient = ninjectKernel.Get<IElasticClient>();
            
            //DELETE devdev/test1

            esClient.Map<MappingTest1>(m =>
                m.DynamicTemplates(dt => dt.Add(a => a
                       .Name("string_fields")
                        .Mapping(tm => tm
                            .Generic(mf => mf
                                .Type("{dynamic_type}")
                                .Index("analyzed")
                                .Fields(mff => mff
                                    .Generic(g => g
                                        .Name("raw")
                                        .Type("{dynamic_type}")
                                        .Index("not_analyzed")
                                    )
                                )
                            )
                        )
                       .MatchMappingType("string")
                    )
                )
                .MapFromAttributes()
            )
            .VerifySuccessfulResponse();

            esClient.Index(new MappingTest1
                           {
                               GeoPoint = new GeoPointTest
                                          {
                                              Latitude = 12.12,
                                              Longitude = -11.11
                                          },
                               Field1 = "I want this to be a multifield"
                           })
                           .VerifySuccessfulResponse();
        }
```
Here is the resulting mapping:
```
{
   "devdev": {
      "mappings": {
         "test1": {
            "dynamic_templates": [
               {
                  "string_fields": {
                     "mapping": {
                        "index": "analyzed",
                        "type": "{dynamic_type}",
                        "fields": {
                           "raw": {
                              "index": "not_analyzed",
                              "type": "{dynamic_type}"
                           }
                        }
                     },
                     "match_mapping_type": "string"
                  }
               }
            ],
            "properties": {
               "field1": {
                  "type": "string"
               },
               "geoPoint": {
                  "type": "geo_point"
               }
            }
         }
      }
   }
}
```
Notice how the field ```geoPoint``` is correct, but the field ```field1``` is *NOT* a multi-field.  The following query fails to return any data.

```
GET devdev/test1/_search
{
  "query": {
    "term": {
      "field1.raw": {
        "value": "I want this to be a multifield"
      }
    }
  }
}
````

**Example 2: dynamic template applied, but MapFromAttributes *NOT* called.**

```
DELETE devdev/test1

            esClient.Map<MappingTest1>(m =>
                m.DynamicTemplates(dt => dt.Add(a => a
                       .Name("string_fields")
                        .Mapping(tm => tm
                            .Generic(mf => mf
                                .Type("{dynamic_type}")
                                .Index("analyzed")
                                .Fields(mff => mff
                                    .Generic(g => g
                                        .Name("raw")
                                        .Type("{dynamic_type}")
                                        .Index("not_analyzed")
                                    )
                                )
                            )
                        )
                       .MatchMappingType("string")
                    )
                )
                //.MapFromAttributes()  //DO NOT MAP FROM ATTRIBUTES FROM THIS EXAMPLE
            )
            .VerifySuccessfulResponse();

            esClient.Index(new MappingTest1
                           {
                               GeoPoint = new GeoPointTest
                                          {
                                              Latitude = 12.12,
                                              Longitude = -11.11
                                          },
                               Field1 = "I want this to be a multifield"
                           })
                           .VerifySuccessfulResponse();
```

The resulting mapping is:

```
{
   "devdev": {
      "mappings": {
         "test1": {
            "dynamic_templates": [
               {
                  "string_fields": {
                     "mapping": {
                        "index": "analyzed",
                        "type": "{dynamic_type}",
                        "fields": {
                           "raw": {
                              "index": "not_analyzed",
                              "type": "{dynamic_type}"
                           }
                        }
                     },
                     "match_mapping_type": "string"
                  }
               }
            ],
            "properties": {
               "field1": {
                  "type": "string",
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               },
               "geoPoint": {
                  "properties": {
                     "lat": {
                        "type": "double"
                     },
                     "lon": {
                        "type": "double"
                     }
                  }
               }
            }
         }
      }
   }
}
```

Notice that ```field1``` is correctly a multi-field but now ```geoPoint``` is not correctly a ```geo_point```

The following query successfully returns the record I just inserted (but now I can't query on geoPoint properly.

```
GET devdev/test1/_search
{
  "query": {
    "term": {
      "field1.raw": {
        "value": "I want this to be a multifield"
      }
    }
  }
}
````

I hope that all makes good sense.

Thank you.

**Comment by gmarz** [comment] 2015-04-22 19:07
Hey @jayhilden

Thanks for the full examples!  The issue is much clearer now.

You can't apply a dynamic template to existing fields in the same mapping call- it's only for newer fields that are detected after the fact.

By calling `MapFromAttributes()`, you are explicitly mapping `Field1` as a string.  Unfortunately, there is no abstraction in NEST to apply a dynamic template to existing fields in the same request.

I think the best way to solve this would be to remove the `MapFromAttributes()` call and map `GeoPoint` explicitly.  Any new string fields will get mapped via the dynamic template when they're indexed:

```csharp
_client.Map<RedemptionES>(m => m
	.Properties(ps => ps
		.GeoPoint(gp => gp
			.Name(r => r.GeoPoint)
		)
	)
	.DynamicTemplates(dt => dt
		.Add(a => a
			.Name("string_fields")
            .Mapping(tm => tm
                .Generic(mf => mf
                    .Type("{dynamic_type}")
                    .Index("analyzed")
                    .Fields(mff => mff
                        .Generic(g => g
                            .Name("raw")
                            .Type("{dynamic_type}")
                            .Index("not_analyzed")
                        )
                    )
                )
            )
            .MatchMappingType("string")
        )
    )
)
```

Hope that helps.

**Comment by Mpdreamz** [comment] 2015-04-24 12:24
Closing this since `MapFromAttributes()` and `DynamicTemplates()` are too conflicting features. 

One is all about locking down known mappings up front as much as possible inferring what we can using reflection on CLR types, and the other is to be able to handle all unknown mappings in a certain way whenever and from where ever they might appear.

Having said that:

```csharp
.MapFromAttributes(a=>a
    .String( /* set up default string mapping here for reflected properties */ )
```

Would be a great addition to our API :+1: adding a new ticket for this now.

**Closed by Mpdreamz** 2015-04-24 12:24 UTC

**Comment by Mpdreamz** [comment] 2015-04-24 12:30
https://github.com/elastic/elasticsearch-net/issues/1328
