### ISSUE TITLE
NEST does not deserialize failure's from task api response

### ISSUE THREAD

**Issue by jeetuthakur** [elastic/elasticsearch-net#6235] opened 2022-03-27 04:48 UTC
**NEST/Elasticsearch.Net version**: 7.17

**Elasticsearch version**: 7.17

**.NET runtime version**: 6.0.4

**Operating system version**: macOS monterery

**Description of the problem including expected versus actual behavior**: Nest is not able to deserialize task api failure response properly. Though Elastic search return error cause and reason but NEST does not deserialize errorCause and reason and only provide headers and index name. Nest only return below error and hide all the reason and errorCause.
  {
                "cause": {
                  "headers": {}
                },
                "id": "NQBhAGYAOQAwAGUAMgAxAC0ANABkAGMAYQAtADUAOAA4ADYALQBiADcAMgAzAC0ANABjAGQAYQA2AGYAZQAzADIANwA4ADIAXwA4AGMAYQA0ADMAYQAxAGQALQA2ADgAMwA3AC0ANAA2AGIANwAtAGEAMgAzAGUALQBhADMAMgAzAGUANAA5AGYAZQBmADUAMQA=",
                "index": "temp_index1",
                "status": 400,
                "type": "_doc"
              }

Please fix it.
**Steps to reproduce**:
 1. create an ES task which fails and have some failure in the task response. 
 2. fetch task status with task api ex var task = elasticClient.Tasks.GetTask("<taskid>");
var response =  task.GetResponse<ReindexOnServerResponse>()
print response
4. though ES gives actual reason and error cause but when you deserialize ReindexOnServerResponse you dont find reason and errorCause.

**Expected behavior**
NEST should deserialize errorCause and reason from Error Obejct like below 
 "failures" : [
      {
        "index" : "temp_index1",
        "type" : "_doc",
        "id" : "1",
        "cause" : {
          "type" : "mapper_parsing_exception",
          "reason" : "failed to parse field [keyword_1] of type [date] in document with id '1'. Preview of field's value: 'somesubject'",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "failed to parse date field [somesubject] with format [strict_date_optional_time||epoch_millis]",
            "caused_by" : {
              "type" : "date_time_parse_exception",
              "reason" : "Failed to parse with all enclosed parsers"
            }
          }
        },
        "status" : 400
      }
    ]

Response deserialize by NEST 
  {
                "cause": {
                  "headers": {}
                },
                "id" : "1",
                "index": "temp_index1",
                "status": 400,
                "type": "_doc"
              }

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment] 2022-03-28 08:39
Thanks for raising this @jeetuthakur. I'll look into this and see if we can add the missing properties to support this in a future release.

**Comment by stevejgordon** [comment] 2022-04-13 14:06
Hi, @jeetuthakur. I just took a proper look at this and everything seems to work as expected on my end and I'm unable to reproduce. Each failure has a `Cause` property which includes the full `Error` object which includes the `CausedBy` and `Reason` properties.

Here's the code I used:

```c#
var client = new ElasticClient();
var response = await client.Tasks.GetTaskAsync("NV5pzcN3S4-4hvmLnnYeTQ:2391076");
var reindex = response.GetResponse<ReindexOnServerResponse>();
```

Here is the locals window showing the expected data on the object.

![image](https://user-images.githubusercontent.com/3669103/163197644-796d6576-947e-40e8-a73a-2600f1a1880d.png)

Can you expand on your scenario so I can understand the issue you are facing?

**Comment by stevejgordon** [comment] 2022-04-21 14:23
Hi, @jeetuthakur. Just checking in to see if this is still a valid issue and if so, can you please provide more information?

**Comment by jeetuthakur** [comment] 2022-04-22 00:48
Hi Steve,
Thanks for looking into this and sorry for replying so late but i was on
vacation.
Yes, I can see the failures in debugger but when i deserialize the object
to print the same info in logs then i do not see any failure or
reason/cause and those objects are empty.
please see attached screenshot.

**Comment by stevejgordon** [comment] 2022-05-10 14:12
I'm going to close this as the use case is not supported.

**Closed by stevejgordon** 2022-05-10 14:12 UTC
Labels: bug, Awaiting Response, 7.x
