### ISSUE TITLE
5.0-rc client unable to deserialize bulk failure

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2358] opened 2016-11-01 19:52 UTC
I get a null reference exception because the following response couldn't be deserialized

```
POST http://127.0.0.1:9200/_bulk HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: 127.0.0.1:9200
Content-Length: 812

{"index":{"pipeline":"increment-age-pipeline","_index":"employees","_type":"employee","_id":"5818f021f8a10328d42ecb76","_version":0}}
{"id":"5818f021f8a10328d42ecb76","companyId":"5818f021f8a10328d42ecb78","name":"  BLAKE  ","age":72,"location":"75.7665134434432,22.3632582288064","yearsEmployed":0,"createdUtc":"2016-11-01T19:42:25.8584684Z","updatedUtc":"2016-11-01T19:42:25.8815678Z","isDeleted":false}
{"index":{"pipeline":"increment-age-pipeline","_index":"employees","_type":"employee","_id":"5818f021f8a10328d42ecb79","_version":0}}
{"id":"5818f021f8a10328d42ecb79","companyId":"5818f021f8a10328d42ecb7a","name":"\tBLAKE  ","age":63,"location":"3.20768867303045,165.742287983067","yearsEmployed":0,"createdUtc":"2016-11-01T19:42:25.8584684Z","updatedUtc":"2016-11-01T19:42:25.8815678Z","isDeleted":false}
```

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 421

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];2: illegal version value [0] for version type [INTERNAL];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];2: illegal version value [0] for version type [INTERNAL];"},"status":400}
```

**Comment by niemyjski** [comment] 2016-11-01 19:53
So I changed the repos to call the create end points for adds. I found this after we were just doing a save only and passing a version

**Comment by niemyjski** [comment] 2016-11-03 13:08
Might be related to https://github.com/elastic/elasticsearch-net/issues/2296#issuecomment-258081863

**Comment by gmarz** [comment] 2016-11-14 22:26
@niemyjski where exactly is the null reference exception occurring? I would expect [this test](https://github.com/elastic/elasticsearch-net/blob/5.x/src/Tests/Document/Multiple/Bulk/BulkInvalidVersionApiTests.cs) to catch any deserialization issues.

Is this just a case of `response.Items` being null as discussed in #2296?  If so, that's the expected behavior since the response is a 400.

**Comment by niemyjski** [comment] 2016-11-14 22:27
The BulkResult itself was null.

**Comment by gmarz** [comment] 2016-11-14 22:31
I'm assuming you mean [BulkResponse](https://github.com/elastic/elasticsearch-net/blob/5.x/src/Nest/Document/Multiple/Bulk/BulkResponse.cs)?

**Comment by niemyjski** [comment] 2016-11-14 22:31
Looking at the test it should reproduce it, but maybe you need multiple bulk index operations need to fail. The errors is an array and talking about multiple errors.

**Comment by gmarz** [comment] 2016-11-14 23:02
> maybe you need multiple bulk index operations need to fail

That did not reproduce it either.  Going to close this in favor of #2296 which looks to be the same issue.

**Closed by gmarz** 2016-11-14 23:02 UTC
