### ISSUE TITLE
Issue with the terms aggregation

### ISSUE THREAD

**Issue by DavidRouyer** [elastic/elasticsearch-net#4505] opened 2020-03-20 16:18 UTC
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.6

**Description of the problem including expected versus actual behavior**:
I'm trying to make a very simple terms aggregation but the Elasticsearch.Net client returns an empty list.

**Steps to reproduce**:
 1. Execute a valid terms aggregation query:
```csharp
return this.ElasticClient.SearchAsync<BundleIndex>(
    s => s
        .From(skip)
        .Size(take)
        .Query(q => q.MatchAll())
        .Aggregations(a => a
            .Terms("affectedTo", t => t
            .Field(f => f.Project.AffectedTo))));
```
 2. Elasticsearch returns a correct response:
```json
    "aggregations": {
        "affectedTo": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "c82b7c93-4355-47eb-2819-08d73b5b29ce",
                    "doc_count": 6
                }
            ]
        }
    }
```
 3. But the client gives me:
```json
"aggregations":{
    "affectedTo":{
        "afterKey":null,
        "bgCount":0,
        "docCount":0,
        "docCountErrorUpperBound":0,
        "items":[{}],
        "meta":null,
        "sumOtherDocCount":0,
        "interval":null
    }
}
```

**Expected behavior**
The client should populate the bucket list in the response.

**Comment by russcam** [comment] 2020-03-21 03:57
How are you accessing the response? How are you printing JSON from the client? Please show the code you're using, as I suspect the issue might be in this

**Comment by DavidRouyer** [comment] 2020-03-21 12:07
Here is the full code:
```csharp
        [HttpGet("search")]
        public async Task<IActionResult> SearchBundles(
            [FromQuery] BundleSearchDto request,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            var searchResponse = await bundleSearchService.SearchAsync(request.Query, request.Skip, request.Take, request.Debug, cancellationToken);
            return Json(searchResponse);
        }
```
My method in BundleSearchService:
```csharp
        public Task<ISearchResponse<BundleIndex>> SearchAsync(
            string query,
            int skip,
            int take,
            bool debug,
            CancellationToken cancellationToken)
        {
            return this.ElasticClient.SearchAsync<BundleIndex>(
                s => s
                    .From(skip)
                    .Size(take)
                    .Query(q => q.MatchAll())
                    .Aggregations(a => a
                        .Terms("affectedTo", t => t
                            .Field(f => f.Project.AffectedTo.Suffix("keyword")))));
        }
```
The aggregation is empty in my Visual Studio debugger

**Comment by russcam** [comment] 2020-03-22 23:26
The problem is

```c#
return Json(searchResponse);
```

The serializer used by the web framework will not know how to serialize all NEST types like `ISearchResponse<T>`. If you need to serialize NEST types. you should use the client's serializer assigned to the `RequestResponseSerializer`. 

Further to using the client's serializer, NEST's response types aren't designed to be reserialized, only deserialized from the Elasticsearch response. Whilst some may reserialize OK, others may not. (This is similar to https://github.com/elastic/elasticsearch-net/issues/3093#issuecomment-366158401)

 If you want to send the verbatim response from Elasticsearch back to the caller, there are a few options:

1. Capture the response bytes with `DisableDirectStreaming()`, and send these to the caller

Either on per request basis

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var settings = new ConnectionSettings(pool);
var client = new ElasticClient(settings);

var searchResponse = client.Search<dynamic>(s => s
	.RequestConfiguration(r => r
		.DisableDirectStreaming()
	)
);
```

Or for all calls

```c#
var pool = new SingleNodeConnectionPool(new Uri($"http://localhost:9200"));
var settings = new ConnectionSettings(pool)
    .DisableDirectStreaming();
var client = new ElasticClient(settings);
```

Then the response bytes are available on the response

```c#
var bytes = searchResponse.ApiCall.ResponseBodyInBytes;
```

Not that this buffers request and response bytes in memory, so comes at a cost of higher memory usage and allocations.

2. Use the low level client to make the call, returning a low level response

```c#
var client = new ElasticClient();

var searchRequest = new SearchDescriptor<BundleIndex>()
	.From(skip)
	.Size(take)
	.Query(q => q.MatchAll())
	.Aggregations(a => a
		.Terms("affectedTo", t => t
		.Field(f => f.Project.AffectedTo)));
		
var index = client.ConnectionSettings.Inferrer.IndexName(Infer.Index<BundleIndex>());

var searchResponse = client.LowLevel.Search<BytesResponse>(
	index, 
	PostData.Serializable(searchRequest));

var bytes = searchResponse.Body;
```

You can use `client.RequestResponseSerializer` to turn the low level response into a high level response if you need to work with it

```c#
var bytes = searchResponse.Body;
SearchResponse<BundleIndex> response = null; 

using (var stream = client.ConnectionSettings.MemoryStreamFactory.Create(bytes))
{
	response = client.RequestResponseSerializer.Deserialize<SearchResponse<BundleIndex>>(stream);
}
```

**Comment by DavidRouyer** [comment] 2020-03-23 15:20
@russcam Thank you for your complete answer! It would have been easier to work directly with the high level client but I understand why it doesn't work.
I'll work directly with the low level client and deserialize the content of the response when I need it.
Thank you!

**Comment by russcam** [comment] 2020-03-23 23:55
No worries! If you don't often need to do anything with the response then going the low level client option may be best. You can still use the high level request types as input, as per the example 👍

**Closed by russcam** 2020-03-23 23:55 UTC
Labels: Awaiting Response, Non-issue
