### ISSUE TITLE
Type inference on anonymous objects

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1761] opened 2016-01-27 20:58 UTC
Currently, if an anonymous object is indexed without specifying a type:

```csharp
client.Index(new { foo = "bar" }, i => i.Index("foo"));
```
the type is inferred as <>f__anonymoustype0`1

Should we throw an exception instead?

**Comment by russcam** [comment] 2016-01-27 22:36
All anonymous type type names start with `<>` (along with a few other characteristics).

Should we infer type to be `object`?

**Comment by gmarz** [comment] 2016-01-27 22:46
> All anonymous type type names start with <> (along with a few other characteristics).

Right, but it seems weird to use that name as a type name in ES.

`object` is better, and technically follows suit with our inference rules...but it still seems a little unassuming to me.

Also, another potential issue- when an index isn't specified:

```csharp
client.Index(new { foo = "bar" });
```

or

```csharp
client.Index(new Foo { Foo = "bar" });
```
The index isn't inferred and we get an exception when dispatching the call ("not enough information").  Shouldn't we be falling back to the default index?

**Comment by russcam** [comment] 2016-01-27 22:59
I think making the assumption that anonymous types are of type `object` is reasonable since one general usage is to pass them to methods that accept a parameter of type `object` e.g. MVC routing, html attributes on `HtmlHelper` methods.

As for the other issue - yes, I think we should be using the default index here as per NEST 1.x :+1:

**Comment by russcam** [comment] 2016-01-29 00:22
NEST 1.x uses the anonymous type name e.g. 

```
<>f__anonymoustype0`1
```

so 2.x is consistent with 1.x right now

**Comment by russcam** [comment] 2016-02-01 20:46
Throw exception on known invalid type and index names

**Comment by russcam** [comment] 2016-02-02 01:35
[issue #9059](https://github.com/elastic/elasticsearch/issues/9059) on input validation rules for Elasticsearch is still open in regards to valid and invalid characters in directory/filenames. 

From source, [Elasticsearch does not allow the following characters in a file name (i.e. index name _currently_)](https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/core/src/main/java/org/elasticsearch/common/Strings.java#L460)

```
'\\', '/', '*', '?', '"', '<', '>', '|', ' ', ','
```

and there are also [some checks for invalid characters in type names}(https://github.com/elastic/elasticsearch/blob/105411060c44cd796187068abe9df6168ff9253b/core/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L228)

```java
if (mapper.type().length() == 0) {
    throw new InvalidTypeNameException("mapping type name is empty");
}
if (mapper.type().length() > 255) {
	throw new InvalidTypeNameException("mapping type name [" + mapper.type() + "] is too long; limit is length 255 but was [" + mapper.type().length() + "]");
}
if (mapper.type().charAt(0) == '_') {
	throw new InvalidTypeNameException("mapping type name [" + mapper.type() + "] can't start with '_'");
}
if (mapper.type().contains("#")) {
	throw new InvalidTypeNameException("mapping type name [" + mapper.type() + "] should not include '#' in it");
}
if (mapper.type().contains(",")) {
	throw new InvalidTypeNameException("mapping type name [" + mapper.type() + "] should not include ',' in it");
}
if (mapper.type().equals(mapper.parentFieldMapper().type())) {
	throw new IllegalArgumentException("The [_parent.type] option can't point to the same type");
}
if (typeNameStartsWithIllegalDot(mapper)) {
	throw new IllegalArgumentException("mapping type name [" + mapper.type() + "] must not start with a '.'");
}
```

But given that the issue on validation is still open and being discussed, I'm suggesting we keep the current behaviour and close this issue for the time being. The exception messages that are returned have a clear description of what the problem is.

Thoughts, @gmarz and @Mpdreamz ?

**Comment by gmarz** [comment] 2016-02-02 02:41
+1 I think we can close this

**Closed** 2016-02-02 03:33 UTC
Labels: Next Release, Vote
