### ISSUE TITLE
Dispatching from NEST into to Elasticsearch.NET failed

### ISSUE THREAD

**Issue by labsilva** [elastic/elasticsearch-net#1839] opened 2016-02-15 16:54 UTC
Using NEST 2.0.2 downloaded from nuget.org in a console app using framework 4.5.2, following a sample from https://nest.azurewebsites.net/nest/quick-start.html:
`            var node = new Uri("http://localhost:9200");
            var settings = new ConnectionSettings(
                node
            );
            var client = new ElasticClient(settings);
            var person = new Person
            {
                Id = "1",
                Firstname = "Martijn",
                Lastname = "Laarman"
            };
            var index = client.Index(person);`

Fails with Exception:
`An unhandled exception of type 'Elasticsearch.Net.ElasticsearchClientException' occurred in Nest.dll

Additional information: Dispatching Index() from NEST into to Elasticsearch.NET failed

Received a request marked as PUT

This endpoint accepts POST,PUT

The request might not have enough information provided to make any of these endpoints:

  - /{index}/{type}

  - /{index}/{type}/{id}`

**Comment by Mpdreamz** [comment] 2016-02-15 21:13
duplicate of: https://github.com/elastic/elasticsearch-net/issues/1833

We are going to publish fancy new docs soon but we are all in San Fransisco for Elasticon and meetings the coming days.

Thanks for reporting though :+1:

**Closed by Mpdreamz** 2016-02-15 21:13 UTC
