### ISSUE TITLE
Issue with CloudConnectionPool 

### ISSUE THREAD

**Issue by knilecrack** [elastic/elasticsearch-net#5951] opened 2021-08-21 01:25 UTC
**NEST/Elasticsearch.Net version**:
7.14.1
**Elasticsearch version**:
7.14
**.NET runtime version**:
5.0.400
**Operating system version**:
10.0.22000

**Description of the problem including expected versus actual behavior**:
Getting following exception when I want to index or get something from cloud hosted elastic search.
Error:
`
Invalid NEST response built from a unsuccessful () low level call on PUT: /mytweetidx/_doc/1?pretty=true&error_trace=true
 Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.4842438
 - [2] ProductCheckFailure: Node: https://xxxxxxx:9243/ Took: 00:00:00.4534002
 OriginalException: Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /?pretty=true&error_trace=true
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.Ping(Node node)
   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
`

**Steps to reproduce**:
```
var cloudId = "cloudId"

var crednetials = new BasicAuthenticationCredentials(user, stringPw);
var pool = new CloudConnectionPool(cloudId, crednetials);
var settings = new ConnectionSettings(pool)
    .EnableDebugMode()
    .EnableHttpCompression()
    .PrettyJson();
var client = new ElasticClient(settings);
var newTweet = new Tweet()
{
    Id = 1,
    User= "knile",
    PostDate = DateTime.Now,
    Message = "Madafaka ne radi"
};
var response = client.Index(newTweet, idx => idx.Index("mytweetidx"));
var getDoc = client.Get<Tweet>(1, idx => idx.Index("mytweetidx"));
var retrived = getDoc.Source;
```
Same code works on ubuntu 20.04, this looks like a underlying OS issue but I wanted to check if you have any suggestions what could cause this issue. 

Thanks

**Comment by stevejgordon** [comment] 2021-08-21 08:47
This appears to be down in the HttpClient TLS code and suggests the client and server are unable to agree on the cipher to use during handshake.

Based on the OS build, this looks like you're running on Windows 11 Preview? If so, it's possible there's an OS issue or incompatibility at play. 

You could take the client out of the equation and try connecting directly via HttpClient. I would expect the same issue to occur there.

**Comment by knilecrack** [comment] 2021-08-21 11:32
@stevejgordon Yes, it's Win 11 Preview, looks like an issue with OS now, as I've tried with .net 6 preview as well and it was not working. I'll give it a try with HttpClient today and let you know. 
I'm deploying to Azure, region:west-eu.

**Comment by knilecrack** [comment] 2021-08-21 12:37
@stevejgordon it's same issue using HttpClient: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.

**Comment by stevejgordon** [comment] 2021-08-21 15:13
Thanks for confirming @knilecrack. Sounds like some issue with .NET 5 on Win 11 Preview then. There's likely no support for that right now until Win 11 is out of preview. I'll pass it along to my contacts at Microsoft to see if they are aware. I'll close this issue as it's unrelated to the client.

**Closed by stevejgordon** 2021-08-21 15:13 UTC

**Comment by wfurt** [comment] 2021-08-24 16:23
You can try to disable TLS 1.3 @knilecrack
https://docs.microsoft.com/en-us/answers/questions/348388/windows-10-tls-13-enablement-registry-keys.html

**Comment by stevejgordon** [comment] 2021-08-31 10:24
Hi @knilecrack. Microsoft would be interested in looking into this issue further to understand if this is a problem with Win 11 / .NET that needs addressing. They'd ideally need to capture the TLS handshake using Wireshark to look at the negotiation. Is there a possibility of you capturing this so that I could pass it along?

Disabling TLS 1.3 as @wfurt suggested would also be interesting to test. The cloud service does not support TLS 1.3 and that might force the client and server to agree on TLS 1.2 during the handshake.

**Comment by stevejgordon** [comment] 2021-08-31 12:49
@knilecrack I've investigated further and reproduced this on Windows 11 myself so no need for a Wireshark capture from you now. I've captured and identified that indeed the handshake appears to default to using TLS 1.0 on Windows 11 which is likely the problem here since the server will not support that. I've provided the details to Microsoft to investigate the behaviour difference on Win 10 and Win 11.

**Comment by knilecrack** [comment] 2021-08-31 16:24
@stevejgordon Oh thanks. If you need anything else let me know.

**Comment by wfurt** [comment] 2021-08-31 16:48
Shoot me the capture @stevejgordon. The handshake _may_ look like 1.0 but there is extension showing all supported versions in ClientHello. If this is caused by underlying OS, we will also need to collect Schannel traces.

**Comment by stevejgordon** [comment] 2021-08-31 16:58
Thanks, @wfurt - You should have an email from me waiting from earlier today which includes the trace and some other details. I may have misinterpreted the TLS specifics though.

**Comment by knilecrack** [comment] 2021-09-11 16:38
@wfurt Hi, were you able to figure out anything regarding this ?

**Comment by wfurt** [comment] 2021-09-11 17:31
Tls13 is the culprit and disabling it should unblock anybody @knilecrack. @stevejgordon is investigating the server part as it seems to complain about ciphers even if client offers cipher suites that should be available on the server.

**Comment by jaspinder-comarm** [comment] 2021-10-19 02:33
I have disabled TLS1.3 but the issue is still there?
