### ISSUE TITLE
Timeout responses after long processing

### ISSUE THREAD

**Issue by dpunset** [elastic/elasticsearch-net#2640] opened 2017-02-28 20:55 UTC
NEST 5.2.0
Elasticsearch 5.2.1

I have an application that analyzes a big ammount of data and usually takes a long time to complete. All the data is stored in ElasticSearch accross different indexes, all in the same server (which I run locally at the moment, on the same pc as my tool).

The application consists of 5 threads reading data from the db and each producing more data that is sent at the end of each job with Bulk, each posting a different index. One of the jobs takes much longer than the others. After a long time processing (more than one hour) all the NEST searches return with a timeout and a few exceptions, and it never recovers. The response gives me this:

```
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll

Invalid NEST response built from a unsuccessful low level call on POST: /methods_codedeptools/methodstype/_search
# Audit trail of this API call:
 - [1] BadResponse: Node: http://mtl-be100:9200/ Took: 00:01:00.0390033
 - [2] MaxTimeoutReached: Took: -736387.20:17:39.6497672
# OriginalException: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 145
# Request:
{"size":1,"query":{"match":{"name":{"query":"inline class CParticlesData &CParticlesData::operator=(class CParticlesData &&)"}}}}
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```

I've tried using different configurations:
- Use one single ElasticClient through every thread
- Create multiple clients (one per thread, or a new one on each query)
- Try different connection settings configurations (no pool, singlenodeconnectionpool, disable/enable direct streaming...)

But sooner or later I reach the point where I can't talk with the DB anymore. When this happens, I try to communicate with it through Kibana and everything works fine, from Kibana itself or the debug console.

My connection settings are created like this:

```
m_url = new Uri("http://" + url);
var pool = new SingleNodeConnectionPool(m_url);
ConnectionSettings esConnectionSettings = new ConnectionSettings(pool);
m_client = new ElasticClient(esConnectionSettings);
```

I checked my connections with cports before running into the issue, and I see 5 connections to elasticsearch from my application, always the same ones and they stay there. When the problem starts happening, those connections are gone, and I don't see any new ones. However, the 3 from Kibana are always fine.

What could be the issue? Is there anything I can do to understand better what could be the problem?
Thank you

Edit: I must add, that if I relaunch the same application while the other one is still running and I debug it, it has no issue talking with ElasticSearch, but the other one keeps getting all the exceptions and timeouts forever.

**Comment by russcam** [comment] 2017-03-02 23:53
What platform are you running on e.g. Windows, Linux, etc? And what framework version of NEST 5.2.0 are you using e.g. .NET 4.6, .NET Standard 1.3, etc?

Are you able to put together a small reproducible example that replicates the issue? This would be super helpful and allow us to investigate it more quickly.

**Comment by dpunset** [comment] 2017-03-10 14:47
Sorry for the delay.

I'm running Windows .Net 4.5.2.

As for the example, I don't know how I could give you something useful :( Really the code is just performing a bunch of searches on a process that runs for a long time. For me to give you a standalone repro case I would also need to send you the contents of the database (the ammount of data is what makes the process very long). Still if you think the code would be useful I can send you the whole solution (it's quite small). Do you think that will help you?

By the way, I managed to work around the issue for the moment. For this task that takes so long, I just split the process in multiple jobs and it manages to finish before the timeouts start. Still, it would be great to know why this happens.

Thank you. Let me know.

David

**Comment by Mpdreamz** [comment] 2017-03-14 01:18
> The application consists of 5 threads reading data from the db a

`db` in this context is it `Elasticsearch` ? Because your search has `size: 1` i think you are overloading the search thread pool. By cutting them up in smaller tasks you might not be sending that many concurrent requests to Elasticsearch anymore and not hitting the timeouts. 

Hard to say without knowing more about your usecase. Feel free to send your solution to `ml` > @ < `elastic.co`, closing this for now but will reopen if I spot anything in the solution.

**Closed by Mpdreamz** 2017-03-14 01:18 UTC
