### ISSUE TITLE
Cannot assign  request address 

### ISSUE THREAD

**Issue by laosandegudai** [elastic/elasticsearch-net#3787] opened 2019-05-31 07:37 UTC
**NEST/Elasticsearch.Net version**:6.6

**Elasticsearch version**:6.7

**Description of the problem including expected versus actual behavior**:
When big data index 
![IB BIMMD}BWZPNM930NK}OK](https://user-images.githubusercontent.com/17979159/58689415-8f6d3c80-83b9-11e9-8805-207896d84c3b.png)

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:
          var path = Environment.GetEnvironmentVariable("ESURL");
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new Exception("the Environment vairable ESURL is not exist");
            }

            var pathArr = path.Split(",", StringSplitOptions.RemoveEmptyEntries);
            IEnumerable<Uri> nodes = pathArr.ToList().Select(s => new Uri(s));
            var pool = new StaticConnectionPool(nodes);
            var settings = new ConnectionSettings(pool).DefaultTypeName(ESClient.DOCUMENTTYPE).ConnectionLimit(1000);
**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment] 2019-05-31 08:16
This looks like an issue in your environment @laosandegudai. What does `http://es:9200` resolve to?

**Comment by laosandegudai** [comment] 2019-05-31 09:44
> This looks like an issue in your environment @laosandegudai. What does `http://es:9200` resolve to?
My   environment  is  right ,it  works well a little ,    alaways  happyend    one  hour  time after   running.

**Comment by biaotang** [comment] 2019-05-31 10:36
@russcam  
Through the command ```netstat -n | grep 9200 | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'``` on the application docker container, I found many ESTABLISHED tcp connection when large amount of data was inserting into es,  nest client  doesn't  release or close the tcp connection.  The  value of ESTABLISHED connection  grows to  20 thousand.  Doesn't  the nest client reuse the connection ?

**Comment by Mpdreamz** [comment] 2019-05-31 12:29
It should @biaotang can you share more about the docker images and host?

**Comment by Mpdreamz** [comment] 2019-05-31 12:45
Also be sure you adhere to our lifetime guidelines:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html

Reusing HttpClient is per `ConnectionSettings`

**Comment by biaotang** [comment] 2019-06-01 02:36
> It should @biaotang can you share more about the docker images and host?

I am sorry to reply so late.

The information related deployment environment  as follow:

```
[root@node1 ~]# docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

.net application named  edoc2,  image built  base  on  dotnet-runtime-2.1.0


es image :   docker.elastic.co/elasticsearch/elasticsearch:6.7.2
 

(deployed using  ```docker stack```)  compose file  as follow: 

```
version: '3.3'

services:
  edoc2:
    hostname: edoc2
    image: 192.168.251.78/edoc2v5/edoc2:20190530195516
    labels:
      "type": "1"
    environment:
      - ESURL=http://es:9200
    networks: 
      - edoc2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    hostname: es
    volumes:
      - /home/edoc2/data/es:/usr/share/elasticsearch/data
    labels:
      "type": "2"
    networks: 
      - edoc2
    environment:
      - node.name=es
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  edoc2:
    driver: overlay
```

code for ESClient :
```
public class ESClient
    {
        public const string ESSECTION = "ESClient";
        public const string ESURLS = "Urls";
        private static ConnectionSettings _defaultConnectionSettings;
        private ConnectionSettings _connectionSettings;
        private ElasticClient _elasticClient;
        public ESClient()
        {
            _connectionSettings = _defaultConnectionSettings;
        }
        public ESClient(IConfiguration configuration)
        {
            var urls = configuration.GetSection($"{ESSECTION}:{ESURLS}");
            if (!string.IsNullOrWhiteSpace(urls.Value))
            {
                var nodes = urls.Value.Split(';').Select(x => new Uri(x));
                var pool = new StaticConnectionPool(nodes);
                _connectionSettings = new ConnectionSettings(pool);
            }
        }

        public static void AddESClient(ConnectionSettings connectionSettings)
        {
            _defaultConnectionSettings = connectionSettings;
        }

        private void InitESClient()
        {
            if (_elasticClient == null)
            {
                if (_connectionSettings != null)
                {
                    _elasticClient = new ElasticClient(_connectionSettings);
                }
                else
                {
                    throw new Exception("ESClient init failed！");
                }
            }
        }
    }
```

code for ESClientProvider: 
```
public static class ESClientProvider
    {
        private static ESClient _client;

        public static ESClient GetESClient()
        {
            if (_client != null)
            {
                return _client;
            }

            var path = Environment.GetEnvironmentVariable("ESURL");
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new Exception("the Environment vairable ESURL is not exist");
            }
        
            var pathArr = path.Split(",", StringSplitOptions.RemoveEmptyEntries);
            IEnumerable<Uri> nodes = pathArr.ToList().Select(s=>new Uri(s));
            var pool = new StaticConnectionPool(nodes);
            var settings = new ConnectionSettings(pool).ConnectionLimit(1000);
            ESClient.AddESClient(settings);
            ESClient client = new ESClient();
            _client = client;
            return _client;
        }
    }
```

The application  created three instances  through ESClientProvider,  different instance doing different tasks. 

According to my understanding， every instance created limit the connection 1000  by the option connectionLimits,  three instances at most 3000 concurrent connections and then HttpClient will reuse the connection. Is it  right ?

However, I found 20,000 connections from edoc2 with the status ESTABLISHED

**Comment by Mpdreamz** [comment] 2019-06-01 07:26
Thanks for the detailed response! 

I have reported on socket reuse issues on linux with .NET Core before:

https://github.com/dotnet/corefx/issues/21227

It's one of the reasons our connection limit on linux is so conservative

https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs#L24

Going from `Environment.ProcessorCount` to `1000` might amplify the bleed. 

Are you compiling AND running on .NET Core 2.1? Can you share the `<TargetFramework>` of your `csproj`?

**Comment by Mpdreamz** [comment] 2019-06-01 07:40
For full reference how are you calling `ESClientProvider.GetESClient()` and storing the result and `ESClient.Index()`?

**Comment by biaotang** [comment] 2019-06-01 08:26
> Thanks for the detailed response!
> 
> I have reported on socket reuse issues on linux with .NET Core before:
> 
> [dotnet/corefx#21227](https://github.com/dotnet/corefx/issues/21227)
> 
> It's one of the reasons our connection limit on linux is so conservative
> 
> https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs#L24
> 
> Going from `Environment.ProcessorCount` to `1000` might amplify the bleed.
> 
> Are you compiling AND running on .NET Core 2.1? Can you share the `<TargetFramework>` of your `csproj`?


I am sorry, the information provided before is a bit wrong. 

I confirmed that the dotnet runtime of application  is using version 2.2,   compiling and running on .NET Core 2.2 .  
 
The ` <TargetFramework> `  of edoc2  application  is  .NET Core 2.2 .

**Comment by biaotang** [comment] 2019-06-01 08:54
> For full reference how are you calling `ESClientProvider.GetESClient()` and storing the result and `ESClient.Index()`?

such as writing logs,  calling ``` ESClientProvider.GetESClient() ``` as follow : 

```
    public static class LogsProvider
    {
        private static string indexName = "filelog";
        private static ESClient client = ESClientProvider.GetESClient();

        public static string WriteLogs(FileLogDto fileLogDto)
        {
            return client.Index(indexName, fileLogDto);
        }
   }
```

Actually，

**Comment by laosandegudai** [comment] 2019-06-02 11:47
> storing the result and `ESClient.Index()`?
yes,storing the result and ESClient.Index().

**Comment by russcam** [comment] 2019-06-11 01:10
@biaotang would you be able to put together a small example that reproduces what you're seeing? Having a small example to work with will make this much easier to investigate.

**Comment by russcam** [comment] 2019-06-21 14:48
Looks like this may be https://github.com/dotnet/corefx/issues/37044

**Comment by biaotang** [comment] 2019-06-25 09:09
> Looks like this may be [dotnet/corefx#37044](https://github.com/dotnet/corefx/issues/37044)

Not the same Exception,  I have restored the configuration "ConnectionLimit" to 80, and cancel the ping request for single ES node,  I saw  the  connection  had been recycled。 Hope  these will help !  
I will continue to follow up and update .  Thanks  for your help ， @russcam  @Mpdreamz

**Comment by russcam** [comment] 2019-07-22 06:04
@biaotang Can you try with [NEST 7.1.0](https://www.nuget.org/packages/NEST/7.1.0), and update whether the issue persists, or is now resolved?

**Comment by biaotang** [comment] 2019-08-16 02:31
> @biaotang Can you try with [NEST 7.1.0](https://www.nuget.org/packages/NEST/7.1.0), and update whether the issue persists, or is now resolved?

hi, after modifying the source code not to reuse httpclient,  this error has not yet appeared, thanks

**Comment by russcam** [comment] 2019-08-16 02:39
Thanks for getting back, @biaotang. I'm going to close this issue for now as the issue appears to be resolved.

**Closed by russcam** 2019-08-16 02:39 UTC
Labels: Awaiting Response, Research

**Comment by wernerbarnard** [comment] 2019-09-11 06:16
How can this issue be solved for someone stuck on Elasticsearch 5.1.x ? (Corporate, etc)

**Comment by laosandegudai** [comment] 2019-09-11 06:19
you can custom connection by yourself. order to use "HttpClientFactory"  control  httpclient  and  dispose tcp .

**Comment by wernerbarnard** [comment] 2019-09-11 10:53
@laosandegudai can I customise/specify that with NEST, or are you referring to not using NEST ?

**Comment by laosandegudai** [comment] 2019-09-12 05:37
> @laosandegudai can I customise/specify that with NEST, or are you referring to not using NEST ?

yes,I use NEST. You  can look  for it  in     sourcecode.
![image](https://user-images.githubusercontent.com/17979159/64756629-36897480-d562-11e9-98a1-bf964c1c2dfd.png) 
 you can leve me email  ,  if you dont understand me.
