### ISSUE TITLE
Support for case_insensitive feature in Terms Query

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [elastic/elasticsearch-net#5408] opened 2021-03-16 07:12 UTC
Hi,
    
   We have a support for case_insenstive option in Term Query as mentioned in the url [https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html](url). 

`{
    "query": {
        "term": {
            "title": {
                "value": "big THEORY",
                "case_insensitive": true
            }
        }
    }
}`

   Likewise Is there any support to set case-insensitive option in Terms Query?

Thanks.

**Comment by stevejgordon** [comment] 2021-03-16 11:26
Closing as duplicate of #5407

**Closed by stevejgordon** 2021-03-16 11:26 UTC
Labels: Feature

**Comment by Sangeetha-Murugesan** [comment] 2021-03-16 11:46
@stevejgordon  I think u misunderstood my question.In elastic we have Term and Terms level query right? Term will be used for matching the field with exact value whereas Terms query is an equivalent to SQL IN Clause operation and it will be implemented like:
 
Term Query:
```
{
    "query": {
        "term": {
            "title": {
                "value": "big THEORY",
                "case_insensitive": true
            }
        }
    }
}
```
Terms Query:

```
{
    "query": {
        "terms": {
            "title":["big bang","big theory"]
        }
    }
}
```
 in which case_insensitive is supported in Term Query..meanwhile i couldnt have any idea of how to use case_insensitive option in Terms Query.
