### ISSUE TITLE
The precision of inserting long type data is lost

### ISSUE THREAD

**Issue by wzfeilongge** [elastic/elasticsearch-net#6212] opened 2022-03-26 10:13 UTC
**NEST/Elasticsearch.Net version**: 7.16.0

**Elasticsearch version**:7.16.3

**.NET runtime version**: .NET 5

**Operating system version**: Centos 7.9

**Description of the problem including expected versus actual behavior**:
            BulkRequest bulkRequest = new(IndexName);
            var operations = csmRecordESModels.Select((CsmRecordESModel o) => new 
        BulkIndexOperation<CsmRecordESModel>(o));
            foreach (var item in operations)
            {

                item.Id = item.Document.ID;
            }
            var op = operations.Cast<IBulkOperation>().ToList();
            bulkRequest.Operations = new BulkOperationsCollection<IBulkOperation>(op);
            var indexManyResponse = await ElasticLinqClient.BulkAsync(bulkRequest);

The type of ID is long,The ID precision of my own entity is lost, and the ID of the document is not lost
The precision of ID is lost when the query is inserted successfully

When querying, the ID precision of the document is not lost, and my own ID precision is lost
**Steps to reproduce**:
 1.insert data
 2. ES HeadQuery 
![GV`MI7H`S9U%Q7@_ACGWY X](https://user-images.githubusercontent.com/48375655/160234791-9cc6e7be-ac32-4d9a-ae74-b49881ab45ff.png)

 3. NEST  query result is the same as ES head
 4.  NEST settings ![DDG~R3VN%2$I N2@L3814IW](https://user-images.githubusercontent.com/48375655/160234878-d0eb3f2f-0b3c-4b70-85a9-ecdff3cf770f.png)
 5. Json settings ![@3Y%2%40SN35@ WRCHZ}(`C](https://user-images.githubusercontent.com/48375655/160234903-fdc7c36b-7a4d-42e6-b284-4638e890db5c.png)
 6. I know it should be possible to avoid this problem through the JSON setting, but I don't know what to do

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment] 2022-03-26 12:13
Hi, @wzfeilongge.

Thanks for the information. Unfortunately, I can't reproduce this locally. As an example, I created an index in Kibana using:

```
PUT precision
{
  "mappings": {
    "properties": {
      "id": {
        "type": "long"
      }
    }
  }
}
```

Then I indexed a single document based on your code to replicate as closely as possible.

```c#
var client = new ElasticClient(); // configure as neccessary

var thing = new Thing
{
    Id = 2942856957231431681
};

var op = new BulkIndexOperation<Thing>(thing)
{
    Id = thing.Id
};

var bulkRequest = new BulkRequest("precision")
{
    Operations = new BulkOperationsCollection<IBulkOperation>(new [] { op })
};

var response = await client.BulkAsync(bulkRequest);

var queryResponse = await client.SearchAsync<Thing>(p => p.Index("precision").MatchAll());

foreach (var hit in queryResponse.Hits)
{
    Console.WriteLine($"_id:{hit.Id} and Value:{hit.Source.Id}");
}
```

The output of which is:
```
_id:2942856957231431681 and Value:2942856957231431681
```

This all appears to work as expected. 

Can you share the mapping for your index and your query code? 

As a starting point, you could enable DebugMode to collect the bulk operation request/response and your query request/response. First, double-check the values being sent in the JSON.

To investigate further, I'll need a minimal reproducible example based on the code I've provided.

The JSON settings you show in bullet no. 5 are not related to those used by NEST.

A final tip: You don't need to create a separate instance of the low-level client in your code. As you are using NEST you can access the low-level client through the `client.LowLevel` property. This will ensure you reuse connections and pooling information.

**Comment by wzfeilongge** [comment] 2022-03-26 12:28
> 嗨，@wzfeilongge。
> 
> 感谢您的信息。不幸的是，我无法在本地复制它。例如，我使用以下方法在 Kibana 中创建了一个索引：
> 
> ```
> PUT precision
> {
>   "mappings": {
>     "properties": {
>       "id": {
>         "type": "long"
>       }
>     }
>   }
> }
> ```
> 
> 然后我根据您的代码索引了一个文档，以尽可能地复制。
> 
> ```cs
> var  client  =  new  ElasticClient (); //配置为必要
> 
> var  thing  =  new  Thing 
> { Id = 2942856957231431681 
> }; var op = new BulkIndexOperation < Thing >( thing ) 
> { Id = thing . 身份证
> }; var bulkRequest = new BulkRequest ( " precision " ) 
> { Operations = new
>       
> 
>     
>       
> 
>     
>        BulkOperationsCollection < IBulkOperation >( new [] { op }) 
> }; var response =等待客户端。BulkAsync ( bulkRequest ); var queryResponse =等待客户端。SearchAsync < Thing >( p => p .Index ( " precision " ). MatchAll ( )); foreach ( var命中queryResponse。_
> 
>     
> 
>       
> 
>    点击）
> {控制台。WriteLine ( $" _id: { hit.Id } and Value : { hit.Source.Id } " ) ; 
> }
>     
> ```
> 
> 其输出为：
> 
> ```
> _id:2942856957231431681 and Value:2942856957231431681
> ```
> 
> 这一切似乎都按预期工作。
> 
> 您可以共享索引和查询代码的映射吗？
> 
> 作为起点，您可以启用 DebugMode 来收集批量操作请求/响应和您的查询请求/响应。首先，仔细检查 JSON 中发送的值。
> 
> 为了进一步调查，我需要一个基于我提供的代码的最小可重现示例。
> 
> 您在项目符号中显示的 JSON 设置。5 与 NEST 使用的无关。
> 
> 最后一个提示：您不需要在代码中创建单独的低级客户端实例。`client.LowLevel`当您使用 NEST 时，您可以通过该属性访问低级客户端。这将确保您重用连接和池信息。

Thank you for your reply

Entity
public class CsmRecordESModel
    {

        public long ID { get; set; }

        [Keyword]
        public string DistrictCode { get; set; }


        [Keyword]
        public string StreetCode { get; set; }


        [Keyword]
        public string CommunityCode { get; set; }


        [Keyword]
        public string ScanIDCard { get; set; }


        [Date]
        public DateTime QueryTime { get; set; }

        [GeoPoint]
        public GeoLocation location { get; set; }


        [Keyword]
        public string Name { get; set; }

        [Keyword]
        public string IdcardType { get; set; }


        [Keyword]
        public string Idcard { get; set; }


        [Keyword]
        public string AgentIdcard { get; set; }


        [Keyword]
        public string Mobile { get; set; }


        [Keyword]
        public string Color { get; set; }


        [Keyword]
        public string ControlState { get; set; }


        [Keyword]
        public string TripValue { get; set; }


        [Keyword]
        public string VaccinationState { get; set; }


        [Keyword]
        public bool? IsTempLicense { get; set; } = false;


        [Keyword]
        public string DataSource { get; set; }

        [Keyword]
        public string ScanType { get; set; }

        [Keyword]
        public string ScanName { get; set; }


        [Keyword]
        public string ScanMobile { get; set; }


        [Keyword]
        public string DeviceNo { get; set; }

        public long? SiteId { get; set; }


        [Keyword]
        public string ResultState { get; set; }


        [Keyword]
        public string GroupCode { get; set; }


        [GeoPoint]
        public GeoLocation scanlocation { get; set; }
    }

CreateKey  
![)Y3LEO5I5VU)_JYKKY0CI88](https://user-images.githubusercontent.com/48375655/160239449-5097a013-5078-469a-9560-5940111fc6c5.png)


Query 
![H6KE})GAZ__9QJ@X4Z



> 嗨，@wzfeilongge。
> 
> 感谢您的信息。不幸的是，我无法在本地复制它。例如，我使用以下方法在 Kibana 中创建了一个索引：
> 
> ```
> PUT precision
> {
>   "mappings": {
>     "properties": {
>       "id": {
>         "type": "long"
>       }
>     }
>   }
> }
> ```
> 
> 然后我根据您的代码索引了一个文档，以尽可能地复制。
> 
> ```cs
> var  client  =  new  ElasticClient (); //配置为必要
> 
> var  thing  =  new  Thing 
> { Id = 2942856957231431681 
> }; var op = new BulkIndexOperation < Thing >( thing ) 
> { Id = thing . 身份证
> }; var bulkRequest = new BulkRequest ( " precision " ) 
> { Operations = new
>       
> 
>     
>       
> 
>     
>        BulkOperationsCollection < IBulkOperation >( new [] { op }) 
> }; var response =等待客户端。BulkAsync ( bulkRequest ); var queryResponse =等待客户端。SearchAsync < Thing >( p => p .Index ( " precision " ). MatchAll ( )); foreach ( var命中queryResponse。_
> 
>     
> 
>       
> 
>    点击）
> {控制台。WriteLine ( $" _id: { hit.Id } and Value : { hit.Source.Id } " ) ; 
> }
>     
> ```
> 
> 其输出为：
> 
> ```
> _id:2942856957231431681 and Value:2942856957231431681
> ```
> 
> 这一切似乎都按预期工作。
> 
> 您可以共享索引和查询代码的映射吗？
> 
> 作为起点，您可以启用 DebugMode 来收集批量操作请求/响应和您的查询请求/响应。首先，仔细检查 JSON 中发送的值。
> 
> 为了进一步调查，我需要一个基于我提供的代码的最小可重现示例。
> 
> 您在项目符号中显示的 JSON 设置。5 与 NEST 使用的无关。
> 
> 最后一个提示：您不需要在代码中创建单独的低级客户端实例。`client.LowLevel`当您使用 NEST 时，您可以通过该属性访问低级客户端。这将确保您重用连接和池信息。

Thank you for your reply

Entity
public class CsmRecordESModel
    {

        public long ID { get; set; }

        [Keyword]
        public string DistrictCode { get; set; }


        [Keyword]
        public string StreetCode { get; set; }


        [Keyword]
        public string CommunityCode { get; set; }


        [Keyword]
        public string ScanIDCard { get; set; }


        [Date]
        public DateTime QueryTime { get; set; }

        [GeoPoint]
        public GeoLocation location { get; set; }


        [Keyword]
        public string Name { get; set; }

        [Keyword]
        public string IdcardType { get; set; }


        [Keyword]
        public string Idcard { get; set; }


        [Keyword]
        public string AgentIdcard { get; set; }


        [Keyword]
        public string Mobile { get; set; }


        [Keyword]
        public string Color { get; set; }


        [Keyword]
        public string ControlState { get; set; }


        [Keyword]
        public string TripValue { get; set; }


        [Keyword]
        public string VaccinationState { get; set; }


        [Keyword]
        public bool? IsTempLicense { get; set; } = false;


        [Keyword]
        public string DataSource { get; set; }

        [Keyword]
        public string ScanType { get; set; }

        [Keyword]
        public string ScanName { get; set; }


        [Keyword]
        public string ScanMobile { get; set; }


        [Keyword]
        public string DeviceNo { get; set; }

        public long? SiteId { get; set; }


        [Keyword]
        public string ResultState { get; set; }


        [Keyword]
        public string GroupCode { get; set; }


        [GeoPoint]
        public GeoLocation scanlocation { get; set; }
    }

CreateKey  
![)Y3LEO5I5VU)_JYKKY0CI88](https://user-images.githubusercontent.com/48375655/160239449-5097a013-5078-469a-9560-5940111fc6c5.png)


Query 
0 Y](https://user-images.githubusercontent.com/48375655/160239455-254097b8-0bcd-47f1-b316-3efd5219fd9f.png)

**Comment by wzfeilongge** [comment] 2022-03-26 12:31
![H6KE})GAZ__9QJ@X4Z0 Y](https://user-images.githubusercontent.com/48375655/160239519-703c4f96-c4f3-4968-889f-e69c2dc9ba19.png)

**Comment by stevejgordon** [comment] 2022-03-26 12:47
@wzfeilongge Could you please past code snippets rather than screenshots?

**Comment by wzfeilongge** [comment] 2022-03-26 12:49
> 

CreateKey 
                    await esClientProvider.ElasticLinqClient.Indices.CreateAsync(csmkeyvalue,
                    c => c.Map<CsmRecordESModel>(
                        m => m.AutoMap<CsmRecordESModel>()
                        )
                    .Settings(
                        s => s.NumberOfShards(4)
                        )
                    );



Query 
               var searchResult = await esClientProvider.ElasticLinqClient.SearchAsync<CsmRecordESModel>(
                x => x.Index($"{key}*")
                .TrackTotalHits(true)
                .TrackScores(true)
                .From((csmQueryDTO.SkipCount - 1) * csmQueryDTO.MaxResultCount)
                .Size(csmQueryDTO.MaxResultCount)
                .Query(q => q.Bool(b => b.Must(boolquery)))
                .Sort(x => x.Ascending(v => v.QueryTime)));
                var response = searchResult.Documents.ToList();
                var total = searchResult.Total;
                if (csmQueryDTO.IsIdCardDesensitization)
                {
                    response.ForEach(x =>
                    {
                        x.Idcard = x.Idcard.DesensitizationIdCard();
                        x.Idcard = x.ScanIDCard.DesensitizationIdCard();                       
                    });
                }
                if (csmQueryDTO.IsMobileDesensitization)
                {
                    response.ForEach(x =>
                    {
                        x.Mobile = x.Mobile.DesensitizationByMobile();
                        x.Mobile = x.ScanMobile.DesensitizationByMobile();
                    });
                }
                return new PagedResultDto<CsmRecordESModel>(total, response);

**Comment by stevejgordon** [comment] 2022-03-26 13:52
@wzfeilongge Based on the code and screenshots I don't see how your app would produce that value in the source. I recommend doing some basic checks in Kibana as your next step. Check your actual mapping for your index to validate how that field is mapped. 

You'll need to capture a request for the bulk request and validate what is actually being sent. Maybe debug through with DebugMode enabled to assess what's happening at each stage.

I'm afraid it's very hard to attempt to understand your app fully and debug through screenshots. I suggest you reduce your scenario down to a much small app and see if you can reproduce this. If you can, please share that and I can assist more easily.

**Comment by wzfeilongge** [comment] 2022-03-26 14:05
> @wzfeilongge根据代码和屏幕截图，我看不到您的应用程序将如何在源代码中产生该值，因为它是浮点类型。我建议您在 Kibana 中进行一些基本检查作为下一步。检查索引的实际映射以验证该字段的映射方式。
> 
> 您需要捕获批量请求的请求并验证实际发送的内容。也许通过启用 DebugMode 进行调试以评估每个阶段发生的情况。
> 
> 恐怕很难尝试完全理解您的应用程序并通过屏幕截图进行调试。我建议你将你的场景缩减为一个非常小的应用程序，看看你是否可以重现这个。如果可以，请分享，我可以更轻松地提供帮助。

**Comment by wzfeilongge** [comment] 2022-03-26 14:40
@stevejgordon
Unfortunately, I can't provide the code, but it's normal for me to use the postman tool. I believe it's still the problem of JSON serialization

![G2NCRT$}}RZH`1)9P9@T`MI](https://user-images.githubusercontent.com/48375655/160244395-622b4a07-0715-4ef2-a576-5cd006d5337f.png)

**Comment by stevejgordon** [comment] 2022-03-26 14:54
Unfortunately, as I've shown in my code, I can round trip a long value and get it back without error. Your examples seem to show different source data in Postman vs. Fiddler. Are these the same server? 

As I say, I can't easily help just by looking at these screenshots. Can you try running my code on your device and check the result? Does the data round-trip successfully? I'm on Windows which is the only difference and I can't see that the OS would affect this. 

NOTE: I'm not asking for you to provide your actual full application code, but you would need to produce a minimal, runnable example application that can demonstrate the problem. You can base it on my code snippet.

**Comment by wzfeilongge** [comment] 2022-03-26 15:05
Thank you for your answer. I don't know where I modified it. After recompiling the code and publishing it to Linux, there is no problem. The accuracy of the query is not lost, but the accuracy of the ES head query result is the same
![APRAA~0%S5P%2ATMJVA(93N](https://user-images.githubusercontent.com/48375655/160245332-983c72a8-77b8-4a96-aa19-f46f7033f4ca.png)
r

**Comment by stevejgordon** [comment] 2022-03-26 15:12
@wzfeilongge What do you mean by "ES head query"? I'm still unsure what the exact issue is now?

**Comment by stevejgordon** [comment] 2022-03-29 10:54
@wzfeilongge Is there anything further I assist with here or can we close?

**Comment by stevejgordon** [comment] 2022-04-11 12:29
Closing due to no further response.

**Closed by stevejgordon** 2022-04-11 12:29 UTC
Labels: Awaiting Response, 7.x
