### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by wjt0818** [elastic/elasticsearch-net#1975] opened 2016-04-01 01:23 UTC
elasticsearch-net\src\Elasticsearch.Net\Transport at   line 102
when i come in an requestData ,this need an requestData.node ,but it is null.......

**Comment by Mpdreamz** [comment] 2016-04-01 04:19
Do you have a stack trace for us as well? Would love to catch this in a test.

**Comment by russcam** [comment] 2016-04-12 07:18
@wjt0818 Would be awesome to get a stack trace for this if you have one? [You have a PR](https://github.com/elastic/elasticsearch-net/pull/1974) that's related to this but would want to ensure that this is a reproducible error before looking at merging.

The `NullReferenceException` in the PR looks like it would happen inside [`ResponseBuilder<TResponse>()`'s `Initialize()` method](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs#L44), when the allowed status codes, uri and method of the request are accessed, but the request data is required in order to make the request in the first place.

If you have any more details, I'd be able to look further into it :+1:

**Comment by Mpdreamz** [comment] 2016-07-13 09:49
Closing as cannot reproduce, @wjt0818 if you have more info on this please respond back to us!

**Closed by Mpdreamz** 2016-07-13 09:49 UTC
