### ISSUE TITLE
NEST SQL Translate no aggregations returned 

### ISSUE THREAD

**Issue by ipxnsv** [elastic/elasticsearch-net#5204] opened 2020-12-21 17:32 UTC
**SQL:**
 "select UDFvarchar1, count(1) from interactions group by UDFvarchar1 order by UDFvarchar1 "
Kibana works with this SQL and translate returns correctly

**Calling Translate:**
var q2 = new TranslateSqlRequest()
{
    Query = "select UDFvarchar1, count(1) from interactions group by UDFvarchar1 order by UDFvarchar1 "

};
var sqlResponse2 = _client.Sql.Translate(q2);
var reqs = sqlResponse2.Result

Reqs.Aggregations is null

**Comment by costin** [comment] 2020-12-22 09:02
This issues is duplicate of https://github.com/elastic/elasticsearch-net/issues/5201.
@ipxnsv please don't copy/paste the repositories with the same report, it's essentially spam which we do not appreciate.
We'll get to the issue as soon as possible.

**Closed by costin** 2020-12-22 09:02 UTC

**Comment by ipxnsv** [comment] 2020-12-22 14:39
Sorry! I realized too late where to actually open the issue.
