### ISSUE TITLE
32 seconds for inserting 1000 documents one by one

### ISSUE THREAD

**Issue by minhhungit** [elastic/elasticsearch-net#4500] opened 2020-03-14 10:48 UTC
**NEST/Elasticsearch.Net version**:
7.6.1
**Elasticsearch version**:
7.6.1

Hello team, I am not sure if this is a bug, I just wonder if it is expected

I installed elactissearch on windows 10 64 bit with default settings (just run elasticsearch.bat file without anything change)

and 24 GB RAM with CPU Xenon

```csharp
var node = new Uri("http://localhost:9200");
var conSettings = new ConnectionSettings(node);
var client = new ElasticClient(conSettings);

Stopwatch stopwatch = Stopwatch.StartNew();
for (int i = 0; i < 1000; i++)
{
	var tweet2 = new Tweet
	{
		Id = i,
		User = "kimchy " + i,
		PostDate = new DateTime(2009, 11, 15),
		Message = "Trying out NEST, so far so good? " + Guid.NewGuid()
	};
	
	var responseIdxxx = client.Index(tweet2, idx => idx.Index("mytweetindex").Id(tweet2.Id));
}
stopwatch.Stop();
Console.WriteLine(stopwatch.Elapsed.TotalMilliseconds);

Console.ReadLine();
```

That is my code, I'm inserting **1000 records** one by one and it took **32 seconds** while if I use bulk insert, it just took **6 seconds** for **1 millions records**

I think that 32 seconds for only 1000 record is quite slow, is it expected.

**Comment by codebrain** [comment] 2020-03-18 03:16
Hi @minhhungit,

Please see the following blog post to give you an idea of the indexing options available using the clients: https://www.elastic.co/blog/indexing-documents-with-the-nest-elasticsearch-net-client

In terms of answering your performance question, it is entirely normal that there would be a difference between looping 1000 times and indexing each document one at a time, and performing a bulk index.

The slowest part of an indexing operation is always the network, it sounds as though you are experiencing slow performance as a result of the repeated HTTP calls to Elasticsearch.

1000 HTTP calls in 32 seconds = 1 call every 32ms

32 ms sounds like a believable round-trip latency for a HTTP call with an index operation, given that I don't have an understanding of the hardware or network topology.

**Comment by minhhungit** [comment] 2020-03-18 05:59
hi @codebrain, thanks for your reply

I am using elasticsearch on my local machine so I am not sure about latency of network. I think because it's local so it should very fast

**Comment by codebrain** [comment] 2020-03-18 06:24
Would you be able to enable debugging and post the results here?
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debugging.html

I am interested to see the debug output for:
`var responseIdxxx = client.Index(tweet2, idx => idx.Index("mytweetindex").Id(tweet2.Id));`

**Comment by russcam** [comment] 2020-03-18 06:27
> I think because it's local so it should very fast

It's not quantifiable how fast it is in a specific environment, without benchmarking with and without network latency. `InMemoryConnection` can be used to remove the network latency.

**Comment by minhhungit** [comment] 2020-03-18 06:49
hi @russcam 
FYI I've just switched to in-memory connection and with in-memory mode, it just took 1.4 second for 1000 records

btw, I also tried to disable antivirus, it reduces about 3-4 second

**Comment by minhhungit** [comment] 2020-03-18 08:23
Hi @codebrain this is debug information

```
Valid NEST response built from a successful (200) low level call on PUT: /mytweetindex/_doc/0
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:01.7304559
# Request:
{"id":0,"user":"kimchy 0","postDate":"2009-11-15T00:00:00","message":"Trying out NEST, so far so good? a909ccb1-5991-4c35-a5de-b418ae29925b"}
# Response:
{"_index":"mytweetindex","_type":"_doc","_id":"0","_version":19,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":37578,"_primary_term":4}

---------------
Successful (200) low level call on PUT: /mytweetindex/_doc/0
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:01.7304559
# Request:
{"id":0,"user":"kimchy 0","postDate":"2009-11-15T00:00:00","message":"Trying out NEST, so far so good? a909ccb1-5991-4c35-a5de-b418ae29925b"}
# Response:
{"_index":"mytweetindex","_type":"_doc","_id":"0","_version":19,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":37578,"_primary_term":4}
```
---
Include a screenshot:

![image](https://user-images.githubusercontent.com/2279508/76940163-4d06f300-692c-11ea-996e-e078933ebba7.png)

**Comment by minhhungit** [comment] 2020-03-18 08:27
More information with **SniffingConnectionPool**

![image](https://user-images.githubusercontent.com/2279508/76940514-fd74f700-692c-11ea-91a9-eb3a739923b1.png)

**Comment by russcam** [comment] 2020-04-02 00:24
Please share source code in (addition to/instead of) screenshots, to allow others to easily reproduce a finding. 

There isn't an objective outcome to this issue so I'm going to close it. There are a few things to consider

-  indexing 1000 documents in 1000 individual HTTP requests is _relatively_ atypical usage. In such instances, the bulk API and batching is a typical approach

- 32 ms sounds like a believable round-trip latency for a HTTP call with an index operation, given that we don't have an understanding of the hardware, network topology, or how Elasticsearch is configured.

- Comparison of `InMemoryConnection` to `HttpConnection` of 1.4 seconds to 32 seconds indicates that the network accounts for 30.6 seconds of the total time, or ~95% of the total time, which sounds plausible.

- Benchmarking is hard! Tests should not set `DisableDirectStreaming()` since it buffers request and response bytes in memory, and extraneous work like `Console.WriteLine()` calls should be removed from the system under test. Using something like [Benchmark.NET](https://github.com/dotnet/BenchmarkDotNet) is a good approach for benchmarking, as it goes to great lengths to try to ensure a test is benchmarking only what you expect it to.

**Closed by russcam** 2020-04-02 00:24 UTC
Labels: Performance

**Comment by minhhungit** [comment] 2020-04-02 16:59
>Please share source code in

I did above ☝️ , here is all code, nothing else, just put it into Main method:

```csharp
var node = new Uri("http://localhost:9200");
var conSettings = new ConnectionSettings(node);
var client = new ElasticClient(conSettings);

Stopwatch stopwatch = Stopwatch.StartNew();
for (int i = 0; i < 1000; i++)
{
	var tweet2 = new Tweet
	{
		Id = i,
		User = "kimchy " + i,
		PostDate = new DateTime(2009, 11, 15),
		Message = "Trying out NEST, so far so good? " + Guid.NewGuid()
	};
	
	var responseIdxxx = client.Index(tweet2, idx => idx.Index("mytweetindex").Id(tweet2.Id));
}
stopwatch.Stop();
Console.WriteLine(stopwatch.Elapsed.TotalMilliseconds);

Console.ReadLine();
```
---

>Comparison of InMemoryConnection to HttpConnection of 1.4 seconds to 32 seconds indicates that the network accounts for 30.6 seconds of the total time, or ~95% of the total time, which sounds plausible.

I am not sure, I just setup elasticsearch on local, same machine, no internet 

Anyway, thank you for responsing @russcam !

**Comment by russcam** [comment] 2020-04-02 23:44
> I am not sure, I just setup elasticsearch on local, same machine, no internet

There are many variables that we simply don't know about though, such as 
- are there services on your machine that could impact benchmarking, like antivirus?
- what other processes are running?
- is paging enabled/disabled?
- how is Elasticsearch configured?

For what it's worth, I've run your code on my local machine in a .NET core 3.1 console application with NEST 7.6.1, with locally running Elasticsearch.

Windows 10 Pro, 64bit with 32GB RAM

```powershell
> Get-ComputerInfo

(abbreviated)

WindowsBuildLabEx                                       : 18362.1.amd64fre.19h1_release.190318-1202
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsProductName                                      : Windows 10 Pro
WindowsVersion                                          : 1909
CsDescription                                           : AT/AT COMPATIBLE
CsNumberOfLogicalProcessors                             : 12
CsNumberOfProcessors                                    : 1
CsProcessors                                            : {Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz}
CsSystemType                                            : x64-based PC
CsTotalPhysicalMemory                                   : 33927790592
CsPhyicallyInstalledMemory                              : 33554432
OsName                                                  : Microsoft Windows 10 Pro
OsVersion                                               : 10.0.18363
OsBuildNumber                                           : 18363
OsTotalVisibleMemorySize                                : 33132608
OsFreePhysicalMemory                                    : 18233900
OsTotalVirtualMemorySize                                : 38867912
OsFreeVirtualMemory                                     : 19724380
OsInUseVirtualMemory                                    : 19143532
OsSizeStoredInPagingFiles                               : 5735304
OsFreeSpaceInPagingFiles                                : 5685268
OsManufacturer                                          : Microsoft Corporation
OsArchitecture                                          : 64-bit
PowerPlatformRole                                       : Mobile
HyperVisorPresent                                       : True

> dotnet --version
3.1.100
```

Elasticsearch 7.5.2 
- default elasticsearch.yml configuration
- default jvm.options configuration

and get the following timings

**Debug configuration**: 10.7 seconds
**Release configuration**: 9.0 seconds

**Comment by minhhungit** [comment] 2020-04-03 02:33
FYI I used production server instead my PC, and this times it took 19 seconds. 
I am not sure if it good but I guess it's okay to close this issue.

Thank you

![image](https://user-images.githubusercontent.com/2279508/78317912-c558ef80-758d-11ea-9359-8fc4c6f61d13.png)
