### ISSUE TITLE
How to support creating index templates“ index.lifecycle.rollover_ Alias "parameter

### ISSUE THREAD

**Issue by Zelin-Tianzhi** [elastic/elasticsearch-net#4844] opened 2020-07-02 06:45 UTC
**Is your feature request related to a problem? Please describe.**
I found that parameters cannot be added when creating index templates using nest“ index.lifecycle.rollover_ Alias "

**Describe the solution you'd like**
How can we support it“ index.lifecycle.rollover_ Alias", thanks

**Comment by russcam** [comment] 2020-07-12 23:41
Hi @Zelin-Tianzhi, 

Any settings can be added using the `.Setting(...)` method. [Taking the example from the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html)

```c#
var client = new ElasticClient();

var putTemplateResponse = client.Indices.PutTemplate("timeseries_template", t => t
	.IndexPatterns("timeseries-*")
	.Settings(s => s
		.NumberOfShards(1)
		.NumberOfReplicas(1)
		.Setting("index.lifecycle.name", "timeseries_policy")
		.Setting("index.lifecycle.rollover_alias", "timeseries")
	)
);
```

Closing this as a duplicate of https://github.com/elastic/elasticsearch-net/issues/4701

**Closed by russcam** 2020-07-12 23:41 UTC
Labels: Feature
