### ISSUE TITLE
UnsupportedProductException for Net Framework 7.14.0 client to 7.14.0 server 

### ISSUE THREAD

**Issue by JoJo2406** [elastic/elasticsearch-net#5938] opened 2021-08-09 14:56 UTC
**NEST/Elasticsearch.Net version**: `7.14.0`

**Elasticsearch version**: `7.14.0`

**.NET runtime version**: `NET 4.8`

**Operating system version**: `Win10`

**Description of the problem including expected versus actual behavior**:

After updating my clients to `7.14.0` I'm getting the following exception for net framework applications (net core seems to be fine). The server is on-prem and is running the latest version `7.14.0`

**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**
For the messages to be sent to a 7.14.0 server without throwing an exception.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

Exception:
```
2021-08-09 15:32:03.6498 Error ElasticSearch: Error while sending log messages Exception: Elasticsearch.Net.UnsupportedProductException: The client noticed that the server is not Elasticsearch and we do not support this unknown product.
   at Elasticsearch.Net.RequestPipeline.FirstPoolUsage(SemaphoreSlim semaphore) in E:\Projects\Elastic\elasticsearch-net-copy\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 327
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in E:\Projects\Elastic\elasticsearch-net-copy\src\Elasticsearch.Net\Transport\Transport.cs:line 65
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in E:\Projects\Elastic\elasticsearch-net-copy\src\Elasticsearch.Net\ElasticLowLevelClient.cs:line 70
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in E:\Projects\Elastic\elasticsearch-net-copy\src\Elasticsearch.Net\ElasticLowLevelClient.NoNamespace.cs:line 296
```

ServerVersion:
```json
{
  "name" : "elastic01.ukgooddeals.local",
  "cluster_name" : "logging-prod",
  "cluster_uuid" : "MIZpBxuzTHyptLMSK1hzwQ",
  "version" : {
    "number" : "7.14.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "dd5a0a2acaa2045ff9624f3729fc8a6f40835aa1",
    "build_date" : "2021-07-29T20:49:32.864135063Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by stevejgordon** [comment] 2021-08-09 15:56
Hi, @JoJo2406. Thanks for raising this. I tested this scenario before release and have just retested it and I'm unable to reproduce this failure on .NET 4.8 runtime. 

Your server version payload certainly appears to be valid. One other thing which could affect the check is if any of the response headers may be stripped by intermediate proxies etc. Specifically, we look for the `X-elastic-product` header on the response as part of the check. If this is missing, the check will fail. Could anything be preventing this from reaching the client?

**Comment by stevejgordon** [comment] 2021-08-11 07:54
Hi, @JoJo2406. I wanted to follow up and see if you made any progress? I would certainly like to deal with any issues if they affect consumers running against supported servers.

**Comment by stevejgordon** [comment] 2021-08-11 08:16
No problem @JoJo2406. Thanks!

**Comment by mcoolidge** [comment] 2021-08-11 14:17
We are seeing the same issue on 7.14 against a 7.7 server. Reverting to 7.12 resolves the issue.

**Comment by vadim-zakharyan** [comment] 2021-08-11 14:53
**NEST/Elasticsearch.Net version**: 7.14.0
**Elasticsearch version**: 7.10.2
**.NET core runtime version**: 5.0
**OS version (docker)**: Alpine Linux v3.13

Got same issue `Elasticsearch.Net.UnsupportedProductException: The client noticed that the server is not a supported distribution of Elasticsearch`

**Temporary solution**: downgrade NEST to 7.13.2
`<PackageReference Include="NEST" Version="7.13.2" />`

**Comment by stevejgordon** [comment] 2021-08-11 14:54
@mcoolidge Sorry to hear that. Is the server running official Elasticsearch with the default distribution (i.e. not oss)? If so, that would not be intended and I'd like to gather some more info.

**Comment by stevejgordon** [comment] 2021-08-11 14:56
@vadim-zakharyan With the `7.11` release of Elasticsearch, we no longer release oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license). Otherwise, you can pin the client version to <7.14 as you've proposed.

**Comment by stevejgordon** [comment] 2021-08-12 08:09
Thanks for confirming that @JoJo2406 and you're very welcome. On that basis, I'll close this issue.

**Closed by stevejgordon** 2021-08-12 08:09 UTC

**Comment by JoJo2406** [comment] 2021-08-12 09:28
@stevejgordon I think I've discovered the issue it was just due to the casing of the headers e.g. "X-elastic-product" vs. "x-elastic-product" and that HttpWebRequestConnection.cs (net-framework) performs a case-sensitive check. Adding ` StringComparer.InvariantCultureIgnoreCase` should fix the issue.

E.g.

```cs
httpWebResponse.Headers.AllKeys.Contains("X-elastic-product")
```

to

```cs
httpWebResponse.Headers.AllKeys.Contains("X-elastic-product", StringComparer.InvariantCultureIgnoreCase)
```

**Comment by stevejgordon** [comment] 2021-08-12 09:59
Ah, good catch @JoJo2406, that should have been case insensitive which is safer for this scenario. In fact, this should be an `OrdinalIgnoreCase` comparison here I think. Is your proxy modifying the casing on route?

**Comment by JoJo2406** [comment] 2021-08-12 10:11
I agree `OrdinalIgnoreCase` would be better, my mistake. It was the proxy converting all headers to lower case as per spec https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2 so I'm pretty sure it would cause issues to all net frameworks clients running es behind a proxy.

**Comment by stevejgordon** [comment] 2021-08-12 13:05
@JoJo2406 - I've pushed a release containing this fix - https://www.nuget.org/packages/NEST/7.14.1. Thanks again for raising and resolving this.

**Comment by JoJo2406** [comment] 2021-08-12 13:10
No problem @stevejgordon, and thanks for the quick release.
