### ISSUE TITLE
Failing to parse empty geo_centroid

### ISSUE THREAD

**Issue by MaJaHa95** [elastic/elasticsearch-net#3000] opened 2018-01-01 12:55 UTC
**NEST/Elasticsearch.Net version**: 5.6.0

**Elasticsearch version**: 6.1.1

**Description of the problem including expected versus actual behavior**:

Geo Centroid aggregate fails to parse with no results.

Essentially, NEST is unable to parse responses that look like this:

```
{
  ...
  "hits" : {
    "total" : 0
    ...
  },
  "aggregations" : {
    "centroid" : {
      "count" : 0
    }
  }
}

```

This resulted from a query that returned no results, with a Geo Centroid aggregation applied. But my actual issue first showed up in an empty sub-aggregation on a Date Histogram. Either way, I believe same root cause (albeit different exceptions).

Looking into the code and stack trace, I believe the issue is happening here:

https://github.com/elastic/elasticsearch-net/blob/3bde31718b7371c798b7829f8fc2040e0f5f3a55/src/Nest/Aggregations/AggregateJsonConverter.cs#L354

The `ReadAggregate` function in `AggregateJsonConverter` is looking at the name of the first property in the aggregation result, finding `count`, and incorrectly concluding that it's a Stats Aggregation. When it tries to parse it as a stats aggregation, it's surprised to find that that's the only property, so an exception is thrown.

Essentially, Elasticsearch doesn't include the `centroid` property when there are no records present, which is logical enough. But NEST doesn't parse that response properly.

I believe the issue itself is relatively clear, but looking at this all, I'm still not sure how to resolve it on my end. Because the parsing is occurring at query time, I'm not given the opportunity to stop it when `doc_count` is 0 on the parent aggregation.

As for a PR, the best I can think would be to check for whether the only property is `count`, and parse it as a `GeoCentroidAggregate` if so, with a `null` `Location`. But assuming an aggregate with only that property is inherently a geo_centroid seems error-prone, even if it does happen to be correct for now.

Any suggestions on a workaround in my code? I'm open to ideas. I might go with the arithmetic mean of the results of a `geo_bounds`, since it doesn't have this same limitation. Of course, that's not necessarily the centroid, but it's probably real-world close enough.

For reference, `geo_bounds` works because it does not include the `count` property (or any properties) when the parent is empty, so it just parses as `null`. Convenient, but not helpful for us here.

**Comment by Mpdreamz** [comment] 2018-01-02 14:51
Opened https://github.com/elastic/elasticsearch-net/pull/3002 to deal with this. 

You will need to use `NEST 6.x` to talk to `Elasticsearch 6.x` we currently have a `6.0.0-rc1` prererelease on nuget. The fix for this will go in the `6.0.0` release which is slated for this week.

**Comment by Mpdreamz** [comment] 2018-01-02 14:52
Forgot to say: thank for the detailed issue 👍 Was super easy for me to reproduce because of that.

**Comment by MaJaHa95** [comment] 2018-01-04 03:29
Thanks @Mpdreamz!

Yep, I'll be moving to NEST 6.0.0 shortly. I had some issues when I first installed it for this project (it's worked great for others, so no doubt something simple on my end), and I put off too much troubleshooting, but I'll get back on that with the new release.


Thanks again,
Matthew

**Comment by russcam** [comment] 2018-01-09 09:17
Change needs to be ported to 5.x into the heuristics based parser (if possible).

**Comment by russcam** [comment] 2018-08-20 07:44
Closing this as #3347 has been merged into 5.x for the next release.

**Closed by russcam** 2018-08-20 07:44 UTC
Labels: Bug, PR Pending, v5.6.4, v6.2.1
