### ISSUE TITLE
Document export memory issue

### ISSUE THREAD

**Issue by akuzhan** [elastic/elasticsearch-net#1696] opened 2015-12-31 11:39 UTC
Hi fellas,

I need to export 100.0000 documents regarding to export functionality. When I check the size of data on fiddler it is around 80 MB, but nevertheless if i check memory usage when I get SearchResponse it is around 1.2 GB. After a while GC collector is utilizing the memory but still even for a few second it is too much memory consumption.

Do you have any idea what might be the issue? 

I do chunk documents 10.000 by 10.000, surprisingly if I increase the number of chunks memory usage improves. So I can assume that it is not related to me forgetting to dispose any object. 

PS: I am not talking about Elasticsearch memory usage, this is all related to .net service layer memory issue. Elasticsearch is coping well. 

Thanks in advance.

**Comment by Mpdreamz** [comment] 2015-12-31 11:48
Oemf that does not sound good, can you share:

* Which version of NEST you are using
* are you able to share an export of the response s in fiddler along with your POCO's and export code? We could use this to reproduce the problem. If you want to share privately: dotnet at elastic.com without the m (scrapers be damned)

**Comment by akuzhan** [comment] 2015-12-31 14:08
I sent email Martijn, many thanks for your helps.

**Comment by Mpdreamz** [comment] 2016-03-07 11:46
Closing this as could not reproduce, if you are still seeing this @akuzhan please reopen !

**Closed by Mpdreamz** 2016-03-07 11:46 UTC
Labels: Next Legacy Release, Research
