### ISSUE TITLE
Nest 7.6 -> GetManyAsync methos -> throw UnexpectedElasticsearchClientException 

### ISSUE THREAD

**Issue by meriturva** [elastic/elasticsearch-net#4462] opened 2020-02-26 08:00 UTC
Using latest version 7.6 we have few problems on tests that use GetManyAsync call.

For example:
`var response = await this.Context.Client.GetManyAsync<TEntity>(ids, this.IndexName);`

Just generate exception:

```
 Elasticsearch.Net.UnexpectedElasticsearchClientException : Index name is null for the given type and no default index is set. Map an index name using ConnectionSettings.DefaultMappingFor<TDocument>() or set a default index using ConnectionSettings.DefaultIndex().
    ---- System.ArgumentException : Index name is null for the given type and no default index is set. Map an index name using ConnectionSettings.DefaultMappingFor<TDocument>() or set a default index using ConnectionSettings.DefaultIndex().
  Stack Trace: 
    Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters) line 149
    GetManyExtensions.GetManyAsync[T](IElasticClient client, IEnumerable`1 ids, IndexName index, CancellationToken cancellationToken) line 68
```

Actually I could give you a more precise reproduction of the problem but not in a short time.
Tell me if necessary.

Ps: i reverted version to 7.5.1 and tests pass again.

**Comment by Mpdreamz** [comment] 2020-02-26 09:32
Can reproduce this as well, will get a fix up shortly

**Comment by Mpdreamz** [comment] 2020-02-26 12:40
@meriturva this should be fixed as per #4463 

Are you able to give the following canary build a try?

`NEST.7.6.0-ci20200226T122106`

From this nuget feed:

https://ci.appveyor.com/nuget/elasticsearch-net


Thanks a ton for reporting this!

**Comment by meriturva** [comment] 2020-02-26 13:18
Thanks @Md right now I'm not able to change CI pipeline to include new feed source and really no time to test it locally (big project here).
If it is really necessary I will try tomorrow!

**Comment by Mpdreamz** [comment] 2020-02-26 13:22
Not necessary :), was just curious if you could give it a quick spin. 

We'll release new versions soon to nuget.org

**Comment by TheFireCookie** [comment] 2020-03-09 13:50
I'm encountering the same bug. I'm glad it has already been corrected. When is a bugfix version planned to work? It prevents me to update to the latest, sweetest version for now.

**Comment by codebrain** [comment] 2020-03-11 05:38
This fix will be going into `7.6.1` and `6.8.5`

**Closed** 2020-03-18 09:42 UTC
Labels: 6.x, 7.x, Bug, v6.8.5, v7.6.1

**Comment by TheFireCookie** [comment] 2020-04-06 10:29
Hello @codebrain & @Mpdreamz , I've tried to update to 7.6.1 but it does not fix the issue for me.

Here is the code that I do to reproduce it:
`var esResponse = await elasticClient.MultiGetAsync(m => m.Index(_fullIndexName).GetMany<EsSdMetadataProfile>(fqns));`

Do you need somethings else? Here is the exception I have:
`System.ArgumentException: 'Index name is null for the given type and no default index is set. Map an index name using ConnectionSettings.DefaultMappingFor<TDocument>() or set a default index using ConnectionSettings.DefaultIndex().'
`
Here is the callstack
![image](https://user-images.githubusercontent.com/10741012/78548689-79ae7c00-7801-11ea-95d3-9e3a7a04ec2b.png)

**Comment by meriturva** [comment] 2020-04-06 12:04
On my side it is fixed with 7.6.1 using: `Client.GetManyAsync<TEntity>(ids, this.IndexName);`

**Comment by TheFireCookie** [comment] 2020-04-06 14:10
I could try to do that. So what would you recommend @codebrain  & @Mpdreamz  what's the best way to multi get documents with a specify index name?
MultiGet with a get many inside (like I this in my example), or calling directly the GetManyAsync at the root level?

**Comment by Mpdreamz** [comment] 2020-04-07 08:46
@TheFireCookie thanks for raising this can confirm the fix does not apply to `MultiGet` and the workaround @meriturva listed should work in `7.6.1` (thanks @meriturva 👍 )

We'll work on fixing this ASAP

**Comment by Mpdreamz** [comment] 2020-04-07 09:06
Coming back to this I don't think this is a bug albeit a very very subtle nuance:

```csharp
var esResponse = await elasticClient.MultiGetAsync(m => m.Index(_fullIndexName).GetMany<EsSdMetadataProfile>(fqns));
```

Means do an `_mget` on `/{_fullIndexName}/_mget` and give me all the `EsSdMetadataProfile` objects where each get operation will be seeded with `IndexName<EsSdMetadataProfile>()`. However unless you configure `EsSdMetadataProfile` default index we have no way of knowing whether that is the default object from the index.

```csharp
var esResponse = await elasticClient.MultiGetAsync(m => m
    .Index(_fullIndexName)
    .GetMany<EsSdMetadataProfile>(fqns)
    .GetMany<OtherObject>(fqns)
);
```

Is equally valid where we don't know if both objects are intended to live in `_fullIndexName` or one of them is. The index in the url of the API only serves as a default e.g if you do an `/blah/_mget` individual gets within the body can still do gets outside of `blah`.

The fix is as the exception describes, configure a default index name on connection settings for the type or be explicit:

```csharp
var esResponse = await elasticClient.MultiGetAsync(m => m
    .Index(_fullIndexName)
    .GetMany<EsSdMetadataProfile>(fqns, (g, id) => g.Index(_fullIndexName))
    .GetMany<OtherObject>(fqns, (g, id) => g.Index("someotherindex"))
);
```

Which is exactly what the helper `client.GetMany()` does for you.

**Comment by TheFireCookie** [comment] 2020-04-07 09:12
Hello,
Thank you for your fast analysis.

The weird thing is that this exact code is working in NEST 7.5.1.
But I can change my code if it seems like the better approach to use GetManyAsync instead of multiget :) What do you think?

Matthias.

**Comment by Mpdreamz** [comment] 2020-04-07 12:17
I think that's the best course of action. With 8.0 we will very likely remove this special routine to try and clean up index on the get operations which will cause the same behaviour.

**Comment by kabcampbell** [comment] 2021-08-06 17:34
Hi there. I'm still seeing this bug in version 6.8.9. I also tried 6.8.5. Rolling back to 6.8.3 works for me, but I wanted to let you know since it seems like the fix didn't get rolled out to version 6 clients.
