### ISSUE TITLE
[test] SerializeTimeSpansAsTicksAndStrings randomly failed on CI 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4423] opened 2020-02-21 09:28 UTC
https://dev.azure.com/azure3/elasticsearch-net/_build/results?buildId=3125&view=logs&j=b43a14c2-2046-5949-944a-5a4631b14be2&t=301652d8-af95-550e-0530-c591704039a1&l=126

```
[xUnit.net 00:00:02.9411802]     Tests.Reproduce.TimeSpanSerialization.SerializeTimeSpansAsTicksAndStrings [FAIL]
  X Tests.Reproduce.TimeSpanSerialization.SerializeTimeSpansAsTicksAndStrings [152ms]
  Error Message:
   Expected 104d, 10h, 38m and 32s, but found 10d, 10h, 38m and 32s.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.SimpleTimeSpanAssertions.Be(TimeSpan expected, String because, Object[] becauseArgs)
   at Tests.Reproduce.TimeSpanSerialization.SerializeTimeSpansAsTicksAndStrings() in /home/vsts/work/1/s/tests/Tests.Reproduce/TimeSpanSerialization.cs:line 30
[xUnit.net 00:00:03.2945958]     Tests.Reproduce.GithubPR3815.CanDeserializeNestedError [SKIP]
  ! Tests.Reproduce.GithubPR3815.CanDeserializeNestedError [1ms]
```

**Comment by russcam** [comment] 2020-02-23 23:56
The test is really simple; it's not obvious how the expected value was ascertained

**Comment by codebrain** [comment] 2020-02-24 00:40
Very strange. This is the test: https://github.com/elastic/elasticsearch-net/blob/fea5445c345c4f041ab5835bb0c2b02d38fac7c0/tests/Tests.Reproduce/TimeSpanSerialization.cs#L15

As @russcam mentions, its very strange how expected is `104` days and not `10` days.

**Comment by russcam** [comment] 2020-02-24 01:01
Couple of potential avenues to explore:

1. Reuse of Memory stream and bytes written from `MemoryStreamFactory`. This seems unlikely because the written bytes would need to match the same JSON structure to deserialize correctly.
2. Concurrency race condition in serialization

**Comment by codebrain** [comment] 2020-02-24 06:41
Side note;
`9023120000000` ticks = 10.10:38:32
`90231200000000` ticks = 104.10:25:20

`90239120000000` ticks = 104.10:38:32

**Comment by russcam** [comment] 2020-02-24 06:53
good catch. May need to dig into https://github.com/elastic/elasticsearch-net/blob/dd5821210f74218a3cfa226da22195294c08d77d/src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs#L791

**Comment by codebrain** [comment] 2020-03-03 23:53
@Mpdreamz I am getting a 404 (build not found) on the above build link...

**Comment by Mpdreamz** [comment] 2020-03-04 12:01
I think its been cleaned up.

**Comment by codebrain** [comment] 2020-03-05 03:57
Ah, OK, I think this is going to be hard to repro without the test run settings (seed). I'll leave the ticket open for the time being and if it occurs again we should document enough for a repro.

**Comment by russcam** [comment] 2020-06-23 01:57
Not seen this issue surface again. Going to close this, and will reopen if resurfaces.

**Closed by russcam** 2020-06-23 01:57 UTC
Labels: Flakey test
