### ISSUE TITLE
Nest Deadlock when running concurrent search calls

### ISSUE THREAD

**Issue by yoav2** [elastic/elasticsearch-net#3272] opened 2018-06-03 19:04 UTC
Using .net core 2.0
Nest 5.5.0
Elasticsearch 5.5.0
(also the same problem reproduces with .net core 2.1, Nest 5.6.2, Elasticsearch 5.5.0)
 
**Short description:** Search queries to elasticsearch are completely stuck when running concurrent search calls. looks like a deadlock in elasticClient insance.

We use a singleton ElasticClient initialized as follow:
 
```
var connectionPool = new SniffingConnectionPool(new List<Node> { new Node(new Uri("http://es1:9200")), new Node(new Uri("http://es2:9200"))});
        var settings = new ConnectionSettings(connectionPool).SniffOnConnectionFault(false).SniffOnStartup(false);
        settings.DefaultIndex(ElasticsearchClient.SM_INDEX_ENGLISH);
        elasticClient= new ElasticClient(settings);
 
```
 
A controller calling elasticClient search is printing the thread id in the beginning and end of the search call:
 
```
 [Route("api/[controller]")]
  public class MyController : Controller
  {
    public IActionResult search([FromBody] SearchQueryRestObject query)
    {
      try
      {
        Log.Information("start Thread: " + Thread.CurrentThread.ManagedThreadId);
 
        result = elasticClient.Search<InteractionData>(s => s
                   .Index("indexName")
                   .From(0)
                   .Size(100)
                   .Query(q => getSearchQuery(query))
                   .Highlight(h => getHighlightDescriptor())
                   .Sort(ss => getSortQuery(query)));
 
         Log.Information("end Thread: " + Thread.CurrentThread.ManagedThreadId);
        return Ok();
      }
      catch (Exception exc)
      {
          Log.ERROR("Error: " + exc);
      }
 }
}
```
 
 
When we call this REST API (using a simple console app), Every 500 milliseconds, Everything work as expected and we get this log
 
2018-06-03 20:56:01.304 [INF] start Thread: 7
2018-06-03 20:56:01.419 [INF] end Thread: 7
2018-06-03 20:56:01.806 [INF] start Thread: 6
2018-06-03 20:56:01.934 [INF] end Thread: 6
2018-06-03 20:56:02.306 [INF] start Thread: 13
2018-06-03 20:56:02.453 [INF] end Thread: 13
2018-06-03 20:56:02.806 [INF] start Thread: 7
2018-06-03 20:56:02.944 [INF] end Thread: 7
2018-06-03 20:56:03.306 [INF] start Thread: 6
2018-06-03 20:56:03.459 [INF] end Thread: 6
2018-06-03 20:56:03.811 [INF] start Thread: 15
2018-06-03 20:56:03.910 [INF] end Thread: 15
…
 
When we call this REST API Every 100 milliseconds we get only  start Thread messages. 
**It looks like there is a deadlock in the  elasticClient.Search. 
New threads are keep getting created and search calls never end.** 
This is the log we get:
 
2018-06-03 21:07:21.961 [INF] start Thread: 7
2018-06-03 21:07:22.057 [INF] start Thread: 13
2018-06-03 21:07:23.052 [INF] start Thread: 22
2018-06-03 21:07:23.064 [INF] end Thread: 7
2018-06-03 21:07:23.070 [INF] start Thread: 7
2018-06-03 21:07:23.070 [INF] end Thread: 12
2018-06-03 21:07:23.075 [INF] start Thread: 12
2018-06-03 21:07:23.097 [INF] end Thread: 6
2018-06-03 21:07:23.104 [INF] start Thread: 6
2018-06-03 21:07:24.049 [INF] start Thread: 21
2018-06-03 21:07:25.049 [INF] start Thread: 20
2018-06-03 21:07:26.049 [INF] start Thread: 15
2018-06-03 21:07:27.050 [INF] start Thread: 23
2018-06-03 21:07:28.051 [INF] start Thread: 24
2018-06-03 21:07:29.050 [INF] start Thread: 25
2018-06-03 21:07:30.051 [INF] start Thread: 26
2018-06-03 21:07:31.050 [INF] start Thread: 27
2018-06-03 21:07:32.050 [INF] start Thread: 28
2018-06-03 21:07:33.050 [INF] start Thread: 29
2018-06-03 21:07:34.051 [INF] start Thread: 30
.
.
.
2018-06-03 21:08:16.051 [INF] start Thread: 490
2018-06-03 21:08:16.051 [INF] start Thread: 491
…
 
 
Only when we kill the test console app, all search calls get free and we get results.

**Comment by t-smirnov** [comment] 2018-06-04 15:23
and why you didnt use async\await in your code?

**Comment by Mpdreamz** [comment] 2018-06-04 15:39
@yoav2 thanks for reporting this we'll dive in asap.

**Comment by yoav2** [comment] 2018-06-04 17:56
Thanks @Mpdreamz. 
You should also know that the test console app is running Async calls without waiting for results. It always sleep the same period of times between the calls, (500 milliseconds in the first test and 100 milliseconds in the second)

**Comment by t-smirnov** [comment] 2018-06-05 10:35
fix ConfigureAwait in ReadError it's ok, but we got slower even on success response

**Comment by yoav2** [comment] 2018-06-14 12:52
Hi @Mpdreamz any update? 
is there going to be a new nuGet (for ES 5.5.x) with a fix?
Thanks

**Comment by Mpdreamz** [comment] 2018-07-31 16:16
Closing as we suspect https://www.nuget.org/packages/NEST/5.6.3 fixes this issue.

Please comment if you feel we closed this too soon! 

Thanks again everyone for the reports and continued testing 👍

**Closed by Mpdreamz** 2018-07-31 16:16 UTC

**Comment by ffMathy** [comment] 2019-03-22 09:07
@Mpdreamz NEST should never block on async code by using `.GetAwaiter().GetResult()` as all current synchronous methods do.

That's really bad practise, and can cause deadlocks in general.

Instead, expose only the async methods, and let the user add `.GetAwaiter().GetResult()` if he wants to.

**Comment by Mpdreamz** [comment] 2019-03-22 13:45
Answer is slightly more nuanced than that:

On full framework our synchronous code path is in fact using blocking WebRequest methods:

https://github.com/elastic/elasticsearch-net/blob/6.x/src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs

On netstandard we do use `.GetAwaiter().GetResult()` which is a best effort which does work well in several synchronization contexts (e.g core asp.net).

On `master` and most likely `7.x` we move to a `netstandard2.0` only build where we will only expose the `HttpClient` backed `IConnection` implementation.

FWIW the [HttpWebRequest in corefx does exactly the same thing on blocking methods](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1005)

Although its not really [the best place to look for best practices](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1106)

Even newer classes like those in [`System.IO.Piplelines`](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipelines/src/System/IO/Pipelines/PipeWriterStream.cs#L56) use `GetAwaiter().GetResult()` to bridge the two worlds which will suffer from the same if used in a bad sync context.

So our conundrum is to either remove sync methods in `7.x` moving forward and break a lot of people who might be okay to begin with or add explicit xmldocs about this behaviour.

cc @codebrain @russcam thoughts?

**Comment by codebrain** [comment] 2019-03-25 06:07
My preference here, personally, would be to leave the sync methods in and then call out this behaviour in xml comments, or in the API conventions: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/api-conventions.html

I'm not against removing them, but I wonder if we need to give a little more forewarning - perhaps for `8.x`?

**Comment by russcam** [comment] 2019-03-25 07:38
Thanks for raising @ffMathy.

I agree with @Mpdreamz that the usage of `GetAwaiter().GetResult()` is a little bit more nuanced than the general advice of calling async methods in synchronous code paths. It's a forced path in this case because of the framework implementation.

Granted we could remove all synchronous code paths, but this is a _huge_ change. I think it would be good to discuss the relative merits/cons in doing so. If we were to take the default approach to be _do nothing_ and keep the current implementation, do we have a clear understanding that there is an issue with the current implementation at this point now? I'm not sure that we do.

We've looked at using a single thread `SynchronizationContext` previously https://github.com/elastic/elasticsearch-net/issues/2364#issuecomment-263780710 instead of `GetAwaiter().GetResult()`. It turned out to be around 17% slower and `GetAwaiter().GetResult()` was actually not the root cause in the end. Curious to see if you've had deadlocks with the client recently, and have a repro for it?
