### ISSUE TITLE
MaxRetryException thrown from RequestHandlerAsync is not catchable

### ISSUE THREAD

**Issue by Entroper** [elastic/elasticsearch-net#1645] opened 2015-12-01 15:43 UTC
`RetryRequestAsync` calls `ThrowMaxRetryExceptionWhenNeeded`, but returns a `Task`.  If you try to `await` this method, the exception is not catchable because it is thrown rather than set on the `Task`.

**Comment by Mpdreamz** [comment] 2016-03-07 14:57
@entroper ty for reporting this and sending 2 PR's. Sorry for not looking into this sooner. 

We had several tests for async and MaxRetryExceptions.

I tried to capture the behaviour in a more explicit tests (no assert library syntax), see the attached commit, but I am unable to reproduce the behaviour you are seeing. 

Can you provide a bit more information on how you are calling and catching `RetryRequestAsync`.

**Comment by Mpdreamz** [comment] 2016-03-23 10:11
Closing this because I need some more information to reproduce this:

See also: https://github.com/elastic/elasticsearch-net/commit/755acae6749fcd51dae64cf866e5f92ba5731d6b

**Closed by Mpdreamz** 2016-03-23 10:11 UTC
