### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by kanwardeepsimsaw** [elastic/elasticsearch-net#7222] opened 2023-02-01 09:40 UTC
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   at Elasticsearch.Net.Extensions.NameValueCollectionExtensions.ToQueryString(NameValueCollection nv)
   at Elasticsearch.Net.RequestData.CreatePathWithQueryStrings(String path, IConnectionConfigurationValues global, IRequestParameters request)
   at Elasticsearch.Net.RequestData..ctor(HttpMethod method, String path, PostData data, IConnectionConfigurationValues global, IRequestParameters local, IMemoryStreamFactory memoryStreamFactory)
   at Elasticsearch.Net.RequestPipeline.CreateRootPathRequestData(Node node)
   at Elasticsearch.Net.RequestPipeline.ProductCheck(Node node)
   at Elasticsearch.Net.RequestPipeline.FirstPoolUsage(SemaphoreSlim semaphore)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.DoRequest[TRequest,TResponse](TRequest p, IRequestParameters parameters, Action`2 forceConfiguration)
   at Nest.Specification.IndicesApi.IndicesNamespace.GetAlias(Indices index, Func`2 selector)
   at Nest.IndicesPointingToAliasExtensions.GetIndicesPointingToAlias(IElasticClient client, Names alias)
   at ThirdPartyServiceClients.ElasticSearchService.ElasticSearchApi..ctor()
   at Mercury.UserControls.ElasticSearchProductCatalogSearchControl..ctor()
   at Mercury.ProductCatalogSearchForm.BindElasticSearchControl(Int32 supplyChainNodeID)
   at Mercury.ProductCatalogSearchForm.SetDataBinding(Int32 supplyChainNodeID)
   at Mercury.ProductCatalogSearchForm..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Mercury.Navigate.DynamicNavigate(String formClassName, String nameValParms)
   at Mercury.LeftNavTree.NavNodeData.Invoke()
   at Mercury.NavControl.navBar_GroupClick(Object sender, GroupEventArgs e)
   at Infragistics.Win.UltraWinExplorerBar.UltraExplorerBar.OnGroupClick(GroupEventArgs e)
   at Infragistics.Win.UltraWinExplorerBar.UltraExplorerBar.FireEvent(UltraExplorerBarEventIds id, EventArgs e)
   at Infragistics.Win.UltraWinExplorerBar.UltraExplorerBarGroup.DoHeaderClick()
   at Infragistics.Win.UltraWinExplorerBar.UltraExplorerBarGroupHeaderUIElement.OnClick()
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUpHelper(Object sender, MouseEventArgs e)
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUp(Object sender, MouseEventArgs e)
   at Infragistics.Win.Utilities.ProcessEvent(Control control, ProcessEvent eventToProcess, EventArgs e)
   at Infragistics.Win.UltraWinExplorerBar.UltraExplorerBar.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by 19M4RT1N97** [comment] 2023-02-03 09:30
Had the same issue, got it working again with pulling the binding redirect version up to version 6.

**Comment by stevejgordon** [comment] 2023-02-03 10:52
Duplicate of #5939

**Closed by stevejgordon** 2023-02-03 10:52 UTC
Labels: 7.x
