### ISSUE TITLE
Nest aggregation need support for raw json

### ISSUE THREAD

**Issue by GaryTurpin** [elastic/elasticsearch-net#3524] opened 2018-12-18 20:29 UTC
**NEST/Elasticsearch.Net version**: 6.2.0

**Elasticsearch version**: 6.3.1

**Describe the feature**: Nest has the ability in the SearchDescriptor to add json for the Query by using Raw.  I dont see the same pattern used for Aggregations.

```var queryJson = GetQueryJson();
var q = new SearchDescriptor<ESDocument>();
q.Query(qq => qq.Raw(queryJson));// I do this today for the query

var aggsJson = GetAggsJson();
q.Aggregation(qa => qa.Raw(aggsJson));// is there a way to do this for aggs?```

**Comment by russcam** [comment] 2018-12-19 05:59
Duplicate of #1016.

There's no feature to be able to do this currently @GaryTurpin. With `typed_keys` now in Elasticsearch, it may be worth revisiting this. I'm going to close this issue so that we can continue to discuss it on #1016.

**Closed by russcam** 2018-12-19 05:59 UTC
