### ISSUE TITLE
mapping time Analyzer is getting removed when defining for analyzer on property directly

### ISSUE THREAD

**Issue by EmilAlipiev** [elastic/elasticsearch-net#2099] opened 2016-05-19 11:10 UTC
I have mixed up analyzers as below.
Number - directly with property
Name- with mapping.

I have recognized that Name is not analyzed with my custom analyzers at all. just standard although I am only using standard for Number property.

When I remove the SearchAnalyzer="standard" from number propery, my custom analyzers for Name filed is take again.

Is it by design like that or an issue? 

I am using 2.3.1 version for Nest and Elasticsearch.net

```
 public class Product
  {

    [Number(NumberType.Integer, Name = "id", Index = NonStringIndexOption.No, Store = true)]
    public int ProductId { get; set; }

    [StringLength(255)]
    [String(Index = FieldIndexOption.Analyzed, Store = true)]
    public string Name { get; set; }

    [StringLength(64)]
    [String(Index = FieldIndexOption.Analyzed, SearchAnalyzer="standard", Store = false)]
    public string Number{ get; set; }

}

```
```
var mapResult = Client.Map<Index.Product>(c => c.AutoMap().Properties(props => props
  .String(s => s
   .Name(p => p.Name).Fields(fs => fs.String(ss => ss.Name(aa => aa.Name.Suffix("raw")).Analyzer("my_delimiter")))
                  .Analyzer("my_analyzer")
                  .SearchAnalyzer("standard"))
```

**Comment by gmarz** [comment] 2016-05-19 17:56
Hey @EmilAlipiev I'm not able to reproduce this, or I'm not understanding the issue entirely.  Here's the JSON that's produced using your snippet above:

```json
{
  "properties": {
    "id": {
      "type": "integer",
      "store": true,
      "index": "no"
    },
    "name": {
      "type": "string",
      "fields": {
        "raw": {
          "type": "string",
          "analyzer": "my_delimiter"
        }
      },
      "analyzer": "my_analyzer",
      "search_analyzer": "standard"
    },
    "number": {
      "type": "string",
      "store": false,
      "index": "analyzed",
      "search_analyzer": "standard"
    }
  }
}
```

Is this not your expectation?

**Comment by gmarz** [comment] 2016-06-17 14:13
Closing.  Feel free to re-open @EmilAlipiev if this is still an issue for you.

**Closed by gmarz** 2016-06-17 14:13 UTC
