### ISSUE TITLE
Using the format=json uri parameter with cat api calls fails

### ISSUE THREAD

**Issue by CraigWh** [elastic/elasticsearch-net#4243] opened 2019-11-28 00:00 UTC
**NEST/Elasticsearch.Net version**: 7.2.1

**Elasticsearch version**: 7.2.1

**Description of the problem including expected versus actual behavior**: Using the Cat.MasterAsync<StringResponse> API and specifying the Format="JSON" parameter returns a response object that has the Success flag set to false but has a status code of 200 and the correct response body. Calling the same method in Elasticsearch.Net 6.8 worked as expected.

I am calling the API like this (this.client is of type IElasticLowLevelClient):
```
await this.client.Cat.MasterAsync<StringResponse>(new CatMasterRequestParameters { Format = "JSON" });
```

**Provide `ConnectionSettings` (if relevant)**:
Using a SingleNodeConnectionPool
Specifying DisableAutomaticProxyDetection and DisablePing

**Provide `DebugInformation` (if relevant)**:
```
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0312765
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 200 from: GET /_cat/master?format=json
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
[{\"id\":\"nodeId\",\"host\":\"hostName\",\"ip\":\"ipaddress\",\"node\":\"nodeName\"}]
```

**Comment by russcam** [comment] 2019-12-09 07:03
Thanks for reporting @CraigWh. This looks like a bug caused by the strictness of the response MIME type against the MIME type that was requested. We'll look at addressing this

**Comment by russcam** [comment] 2019-12-09 07:20
For now, you can set the `Content-Type` and `Accept` headers to allow the call to be deemed successful 

```c#
var response = await client.Cat.MasterAsync<StringResponse>(new CatMasterRequestParameters { 
    RequestConfiguration = new RequestConfiguration 
    {
        ContentType = RequestData.MimeType,
        Accept = RequestData.MimeType
    }
});
```

To be clear, the call using `format=json` is also made, but the MIME type checking means that it ends up being marked as unsuccessful.

**Comment by russcam** [comment] 2019-12-13 07:23
I've opened #4269 to address.

**Closed** 2019-12-17 11:38 UTC
Labels: Bug, v7.5.0
