### ISSUE TITLE
ScriptedUpsert has no effect on BulkUpdateOperation

### ISSUE THREAD

**Issue by MaJaHa95** [elastic/elasticsearch-net#3270] opened 2018-06-01 00:40 UTC
**NEST/Elasticsearch.Net version**: 6.1.0

**Elasticsearch version**: 6.0.0

**Description of the problem including expected versus actual behavior**:

Serialization of `BulkUpdateOperation<>` does not appear to include `scripted_upsert` value in serialized form.

**Steps to reproduce**:

 1. Create a (collection of) `BulkUpdateOperation<object, object>` object, with `Id`, `Index`, `Type`, `Upsert`, and `Script` set to applicable values, and `ScriptedUpsert = true`.
 2. Execute something like...

```
ElasticClient ec = ...;
IList<IBulkOperation> operations = ...; //including from above
await ec.BulkAsync(new BulkRequest { Operations = operations }); 
```
 3. Fiddler shows that there's no accompanying value for `scripted_upsert` in the request body.

Seems like a pretty straight-forward issue; enough that I'm surprised if I'm the first to catch it, albeit a bit of a specialized case. I played around with leaving `Upsert` out and such, but that had no effect on this field.

Are there other prerequisites or something that make the serializer ignore this field?

**Comment by MaJaHa95** [comment] 2018-06-01 00:41
#2662

**Comment by V1tOr** [comment] 2018-06-13 14:33
Hi @MaJaHa95 ,
I'm also able to reproduce this if I create the bulkoperation this was:
`new BulkUpdateOperation<x, x>(product)
{
    ScriptedUpsert = true
};`

This worked for me as a workarround:
`new BulkUpdateDescriptor<x, x>()
    .ScriptedUpsert();
`
both returns an IBulkOperation.
hope it helps

**Comment by russcam** [comment] 2018-06-13 14:51
@MaJaHa95 @V1tOr It looks like `BulkOperation<TDocument,TPartialDocument>` is missing assigning to `_ScriptedUpsert` here

https://github.com/elastic/elasticsearch-net/blob/5798ab8a5706b0b6fa7ef7235de17c7a066a2ec9/src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs#L90

Compare it to

https://github.com/elastic/elasticsearch-net/blob/5798ab8a5706b0b6fa7ef7235de17c7a066a2ec9/src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs#L156

Would someone be up for opening a PR against master to add?

**Closed** 2018-06-22 03:38 UTC
Labels: Bug, PR Pending, Port to master, v5.6.3, v6.2.0
