### ISSUE TITLE
Aggregation throws System.OutOfMemoryException

### ISSUE THREAD

**Issue by jwu-au** [elastic/elasticsearch-net#2810] opened 2017-07-20 12:00 UTC
**NEST/Elasticsearch.Net version**:
5.4

**Elasticsearch version**:
5.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Running aggregation on large amount of data
```C#
                var result = await _elasticClient.SearchAsync<OrderProductAnalyticSearchable>(sd => sd
                    .Size(0)
                    .Query(qcd =>
                        +qcd.Term(opas => opas.IsSuccessful, true) &&
                        +qcd.DateRange(drqd => drqd
                            .Field(oas => oas.OrderCreatedTime)
                            .GreaterThanOrEquals(start)
                            .LessThan(end)
                        )
                    )
                    .Aggregations(acd => acd
                        .DateHistogram("group_by_OrderCreatedTime", dhad => dhad
                            .Field(opas => opas.OrderCreatedTime)
                            .Format("yyyy-MM-dd")
                            .Interval(DateInterval.Day)
                            .Aggregations(acd2 => acd2
                                .Terms("group_by_SellerId", tad => tad
                                    .Size(int.MaxValue)
                                    .Field(opas => opas.SellerId)
                                    .Aggregations(acd3 => acd3
                                        .Terms("group_by_IsFree", tad2 => tad2
                                            .Size(int.MaxValue)
                                            .Field(opas => opas.IsFree)
                                            .Aggregations(acd4 => acd4
                                                .Terms("group_by_CurrencyCode", tad3 => tad3
                                                    .Size(int.MaxValue)
                                                    .Field(opas => opas.CurrencyCode)
                                                    .Aggregations(acd5 => acd5
                                                        .Terms("group_by_ProductId", tad4 => tad4
                                                            .Size(int.MaxValue)
                                                            .Field(opas => opas.ProductId)
                                                            .Aggregations(acd6 => acd6
                                                                .TopHits("top_hits", thad => thad
                                                                    .Size(1)
                                                                )
                                                                .Sum("sum_ProductTotalPrice", sad => sad
                                                                    .Field(opas => opas.ProductTotalPrice)
                                                                )
                                                                .Sum("sum_ProductTotalPriceInBaseCurrency", sad => sad
                                                                    .Field(opas => opas.ProductTotalPriceInBaseCurrency)
                                                                )
                                                                .Sum("sum_ProductTotalDisbursement", sad => sad
                                                                    .Field(opas => opas.ProductTotalDisbursement)
                                                                )
                                                                .Sum("sum_ProductTotalDisbursementInBaseCurrency", sad => sad
                                                                    .Field(opas => opas.ProductTotalDisbursementInBaseCurrency)
                                                                )
                                                                .Filter("filter_IsRecovered", fad => fad
                                                                    .Filter(qcd => qcd
                                                                        .Term(opas => opas.IsRecovered, true)
                                                                    )
                                                                    .Aggregations(acd7 => acd7
                                                                        .Sum("sum_ProductTotalPrice", sad => sad
                                                                            .Field(opas => opas.ProductTotalPrice)
                                                                        )
                                                                        .Sum("sum_ProductTotalPriceInBaseCurrency", sad => sad
                                                                            .Field(opas => opas.ProductTotalPriceInBaseCurrency)
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                );

```

**Provide `DebugInformation` (if relevant)**:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: 引发类型为“System.OutOfMemoryException”的异常。 ---> System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.IO.MemoryStream.ToArray()
   在 Elasticsearch.Net.ResponseBuilder`1.SwapStreams(Stream& responseStream, MemoryStream& ms)
   在 Elasticsearch.Net.ResponseBuilder`1.<SetBodyAsync>d__27.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.ResponseBuilder`1.<ToResponseAsync>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__71`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__261`4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Selz.Core.Hangfire.Jobs.Analytics.DwSalesBySellerByProductAnalyticJob.<PerformTask>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Selz.Core.Hangfire.Jobs.JobBase.<Perform>d__1.MoveNext()
```

**Describe the feature**:
As there is no pagination on aggregation, I wrote above query firstly passed the integration test with small amount of data (only a couple of records). Then I tried to run it on production database where the index size is much much larger. And it throws exception: out of memory. I have no idea how to overcome this issue. Please provides some clues.

Thank you.

**Comment by jwu-au** [comment] 2017-07-20 12:08
Please also see below exception which is slightly different from above one when I tried another run.

```
[22:06:42 WRN] Failed to process the job '59709ca746fec91fb886a95c': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:35.
Elasticsearch.Net.UnexpectedElasticsearchClientException: 引发类型为“System.OutOfMemoryException”的异常。 ---> System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetKeyedBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetKeyedBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetKeyedBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetKeyedBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetDateHistogramBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   在 Nest.JsonNetSerializer.Deserialize[T](Stream stream)
   在 Nest.JsonNetSerializer.DeserializeAsync[T](Stream stream, CancellationToken cancellationToken)
   在 Elasticsearch.Net.ResponseBuilder`1.<SetBodyAsync>d__27.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.ResponseBuilder`1.<ToResponseAsync>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__71`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__261`4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Selz.Core.Hangfire.Jobs.Analytics.DwSalesBySellerByProductAnalyticJob.<PerformTask>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Selz.Core.Hangfire.Jobs.JobBase.<Perform>d__1.MoveNext()
```

**Comment by Mpdreamz** [comment] 2017-07-20 12:12
How big is the returned response in terms of (mega)bytes (maybe you can see it with fiddler/charles proxy/wireshark etcetera)

```
.Size(int.MaxValue)
```

is problematic for high cardinality fields, please consider [partitioning your terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions) and issuing multiple requests instead (or use `_msearch`).

**Comment by jwu-au** [comment] 2017-07-20 15:10
Hi @Mpdreamz 

Just did what you suggested above, but it didn't solve the problem. 
Please see below exceptions.
I guess somehow the memory doesn't release? or any other ideas?

```
[01:06:12 INF] DwSalesBySellerByProductAnalyticJob aggregation from 20/01/2015 to 19/02/2015 running parition 4/4
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation from 20/01/2015 to 19/02/2015 succeed took 485ms
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation took 719ms, updated 4543 data warehouse SalesBySellerByProduct analytics took 250ms
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 cardinality is 19994
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 max partition is 4
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 running parition 1/4
[01:06:13 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 succeed took 547ms
[01:06:14 INF] DwSalesBySellerByProductAnalyticJob aggregation took 890ms, updated 5000 data warehouse SalesBySellerByProduct analytics took 250ms
[01:06:14 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 running parition 2/4
[01:06:16 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 succeed took 2360ms
[01:06:20 INF] DwSalesBySellerByProductAnalyticJob aggregation took 2610ms, updated 4918 data warehouse SalesBySellerByProduct analytics took 3718ms
[01:06:20 INF] DwSalesBySellerByProductAnalyticJob aggregation from 19/02/2015 to 21/03/2015 running parition 3/4
[01:06:25 WRN] Failed to process the job '5970c64846fec93c30702d9f': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:44.
Elasticsearch.Net.UnexpectedElasticsearchClientException: 引发类型为“System.OutOfMemoryException”的异常。 ---> System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Collections.Generic.List`1.set_Capacity(Int32 value)
   在 System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   在 System.Collections.Generic.List`1.Insert(Int32 index, T item)
   在 Newtonsoft.Json.Linq.JPropertyKeyedCollection.InsertItem(Int32 index, JToken item)
   在 System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   在 Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   在 Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   在 Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   在 Newtonsoft.Json.Linq.JContainer.Add(Object content)
   在 Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   在 Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   在 Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   在 Nest.AggregateJsonConverter.GetTopHitsAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetSubAggregates(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetKeyedBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadBucket(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.GetMultiBucketAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadAggregate(JsonReader reader, JsonSerializer serializer)
   在 Nest.AggregateJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   在 Nest.JsonNetSerializer.Deserialize[T](Stream stream)
   在 Nest.JsonNetSerializer.DeserializeAsync[T](Stream stream, CancellationToken cancellationToken)
   在 Elasticsearch.Net.ResponseBuilder`1.<SetBodyAsync>d__27.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.ResponseBuilder`1.<ToResponseAsync>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__71`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__261`4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Selz.Core.Hangfire.Jobs.Analytics.DwSalesBySellerByProductAnalyticJob.<PerformTask>d__8.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Selz.Core.Hangfire.Jobs.JobBase.<Perform>d__1.MoveNext()
```

**Comment by Mpdreamz** [comment] 2017-07-25 21:03
The data you are returning is too big our `Nest.AggregateJsonConverter.GetTopHitsAggregate` to load into memory using `JObject.Load`. We never try to rely on `JObject.Load` in our custom serializers but in some cases it snuck in since it makes parsing just that much easier. For `6.x` we are revisiting the parser completely but in `5.x` we are stuck with what we have.

If you can share your raw response somehow, we could possibly look in to seeing how we could improve here.

**Comment by jwu-au** [comment] 2017-07-26 00:37
Hi @Mpdreamz 
I'll dump the json data sometime and show you later.
But what I don't understand is that, I have limited the size to **5000**, and you can see from the query that the size of tophits is set to **1** only. Shouldn't it be a problem?

**Comment by jwu-au** [comment] 2017-07-31 03:12
Hi @Mpdreamz ,

I have attached data captured by Fiddler. Here giving a summary for it:
Please refer to above OOM exception.

* Request query
```
POST http://elasticsearch.local.selz.com:9200/orderproductanalytics/orderproductanalytic/_search HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: elasticsearch.local.selz.com:9200
Content-Length: 2079

{
  "size": 0,
  "aggs": {
    "group": {
      "terms": {
        "script": {
          "inline": "(int)(doc['orderCreatedTime'].value / (3600000.0 * 24)) + '_' + doc['sellerId'].value + '_' + doc['isFree'].value + '_' + doc['currencyCode'].value + '_' + doc['productId'].value"
        },
        "size": 5000,
        "include": {
          "partition": 3,
          "num_partitions": 5
        }
      },
      "aggs": {
        "top_hits": {
          "top_hits": {
            "size": 1
          }
        },
        "sum_ProductTotalPrice": {
          "sum": {
            "field": "productTotalPrice"
          }
        },
        "sum_ProductTotalPriceInBaseCurrency": {
          "sum": {
            "field": "productTotalPriceInBaseCurrency"
          }
        },
        "sum_ProductTotalDisbursement": {
          "sum": {
            "field": "productTotalDisbursement"
          }
        },
        "sum_ProductTotalDisbursementInBaseCurrency": {
          "sum": {
            "field": "productTotalDisbursementInBaseCurrency"
          }
        },
        "filter_IsRecovered": {
          "filter": {
            "term": {
              "isRecovered": {
                "value": true
              }
            }
          },
          "aggs": {
            "sum_ProductTotalPrice": {
              "sum": {
                "field": "productTotalPrice"
              }
            },
            "sum_ProductTotalPriceInBaseCurrency": {
              "sum": {
                "field": "productTotalPriceInBaseCurrency"
              }
            }
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "isSuccessful": {
              "value": true
            }
          }
        },
        {
          "range": {
            "orderCreatedTime": {
              "gte": "2015-03-21T00:00:00Z",
              "lt": "2015-04-20T00:00:00Z"
            }
          }
        }
      ]
    }
  }
}
```
* Response Header
```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 5017186

```
* Response data (some ids are masked)
[data.zip](https://github.com/elastic/elasticsearch-net/files/1186295/data.zip)

* Data C# class
```c#
    [ElasticsearchType(IdProperty = "Id", Name = "orderproductanalytic")]
    public class OrderProductAnalyticSearchable
    {
        public string Id { get; set; }

        public int SellerId { get; set; }

        public bool IsSuccessful { get; set; }

        public bool IsFree { get; set; }

        public bool IsRecovered { get; set; }

        [Keyword]
        public string CurrencyCode { get; set; }

        [Keyword]
        public string OrderId { get; set; }

        public decimal OrderTotalPrice { get; set; }

        public decimal OrderTotalPriceInBaseCurrency { get; set; }

        public decimal OrderTotalDisbursement { get; set; }

        public decimal OrderTotalDisbursementInBaseCurrency { get; set; }

        public DateTime OrderCreatedTime { get; set; }

        [Keyword]
        public string ProductId { get; set; }

        public ProductType ProductType { get; set; }

        public int ProductQuantity { get; set; }

        public decimal ProductTotalPrice { get; set; }

        public decimal ProductTotalPriceInBaseCurrency { get; set; }

        public decimal ProductTotalDisbursement { get; set; }

        public decimal ProductTotalDisbursementInBaseCurrency { get; set; }
    }

```

Let me know if it does help.

**Comment by Mpdreamz** [comment] 2017-12-08 16:30
Closing this as not able to reproduce and with 6.1 and composite aggregations Elasticsearch and NEST itself will have a much better way to go over ALL the aggregations results.

related to: #2902

**Closed by Mpdreamz** 2017-12-08 16:30 UTC
Labels: Refactoring
