### ISSUE TITLE
Mocking IndicesNamespace?

### ISSUE THREAD

**Issue by ffMathy** [elastic/elasticsearch-net#4287] opened 2019-12-18 09:07 UTC
How do I mock `IElasticClient.Indices`, in other words, the `IndicesNamespace`?

Can we instead have it so that `IElasticClient.Indices` refers to an interface (for instance `IIndicesNamespace` instead)?

Right now, I can't mock indices using `NSubstitute`:

```csharp
var fakeIndicesNamespace = Substitute.For<IndicesNamespace>(); //crashes with message: System.NotSupportedException : Parent does not have a default constructor. The default constructor must be explicitly defined.

var fakeElasticClient = Substitute.For<IElasticClient>();
fakeElasticClient.Indices.Returns(fakeIndicesNamespace);
```

**Comment by codebrain** [comment] 2019-12-19 06:31
Hi @ffMathy - can I ask why you are substituting the `IndicesNamespace`?

The reason for asking is that we have various approaches for mocking the client, some detailed in these issues;

- https://github.com/elastic/elasticsearch-net/issues/4025
- https://github.com/elastic/elasticsearch-net/issues/4076
- https://github.com/elastic/elasticsearch-net/issues/3095

**Comment by ffMathy** [comment] 2019-12-19 06:48
None of those issues are related to mine.

I want to mock it for unit testing 🙂

**Comment by codebrain** [comment] 2019-12-19 06:55
#4076 contains some approaches on how to unit test with the client;

1. Encapsulate client usage in your in own types which you can mock/stub
2. Use `InMemoryConnection` and return a specific response for a given request. Take a look at this [GitHub issue as an example](https://github.com/elastic/elasticsearch-net/blob/b5cf181bbef2269e26a704f0f21bb7f7be6bdf83/src/Tests/Tests.Reproduce/GithubIssue3745.cs)
3. [Use `Elastic.Xunit` and projects](https://github.com/elastic/elasticsearch-net-abstractions) to spin up a cluster as part of your tests. Granted that these will now be integration tests. These can be referenced from our AppVeyor package feed at `https://ci.appveyor.com/nuget/elasticsearch-net-abstractions` which you can reference by adding to Package Sources.

If you feel these approaches are not working for your situation, would you be able to elaborate a little more on what you are trying to acheive?

**Comment by ffMathy** [comment] 2019-12-19 07:10
Why make it so hard? Why can't we just turn IIndicesNamespace into an interface? That way, everyone can mock like they are used to in virtually every single other NuGet package out there, using their own mocking framework?

**Comment by russcam** [comment] 2020-01-28 06:44
It's not just about making `IndicesNamespace` an interface, with a single concrete implementation, though. It also requires making the response types for API calls exposed on `IndicesNamespace` and other namespace clients _mockable_ in some way e.g. virtual members, or again, interfaces with a single concrete implementation for each. This (re)introduces ~280 types (one for each API) into the client, increasing the size of the client binary, and increases the complexity of the async execution paths, just to support the mocking use case. 

Have you taken a look at any of the approaches put forward by @codebrain?

**Comment by codebrain** [comment] 2020-02-24 06:19
Closing this ticket in favour of https://github.com/elastic/elasticsearch-net/issues/4293

**Closed by codebrain** 2020-02-24 06:19 UTC

**Comment by rmadisonhaynie** [comment] 2021-04-03 16:57
> #4076 contains some approaches on how to unit test with the client;
> 
> 1. Encapsulate client usage in your in own types which you can mock/stub
> 2. Use `InMemoryConnection` and return a specific response for a given request. Take a look at this [GitHub issue as an example](https://github.com/elastic/elasticsearch-net/blob/b5cf181bbef2269e26a704f0f21bb7f7be6bdf83/src/Tests/Tests.Reproduce/GithubIssue3745.cs)
> 3. [Use `Elastic.Xunit` and projects](https://github.com/elastic/elasticsearch-net-abstractions) to spin up a cluster as part of your tests. Granted that these will now be integration tests. These can be referenced from our AppVeyor package feed at `https://ci.appveyor.com/nuget/elasticsearch-net-abstractions` which you can reference by adding to Package Sources.
> 
> If you feel these approaches are not working for your situation, would you be able to elaborate a little more on what you are trying to acheive?

@codebrain so I've looked at the suggestions and followed the rabbit hole of linked issues and those issues linked issues and have this output:
1. I don't know if I really want to do a straight 1-1 encapsulation of all the endpoints I'm using just for testing
2. This doesn't work for some how my methods I'm testing that take one client, so one InMemoryConnection and then multiple requests are made within that method with different code paths depending on different responses. It seems like I can only use InMemoryConnection for mocking one response for all requests.
3. I cant remember at the moment why but we've looked at this and cant use, I think it's the companies tech setup, but we already have integration tests anyway.

Would you have a suggestion? Maybe I don't understand InMemoryConnection fully. Context: Migrating from NEST 6.x to NEST 7.x and currently have many UTests mocking the client. cc @russcam

**Comment by mkorman-cat** [comment] 2021-06-04 11:45
I have some concerns with the suggestions raised in #4076

- Essentially, by asking your users to create their own wrappers, you're aking them to do the job that you didn't want to do, which is introduce the interfaces and mockability. You're ignoring some genuine use cases and pushing the complexity to the users
- I don't want to turn my unit tests into integration tests. I just want to mock a specific response to ensure that my code does the right thing when I get a certain response from the library

At the end of the day, use of interfaces and mockability is considered good practices. It would be amazing if your library accepted those. Thanks!
